'use strict';
// Independent mocked transport/DB/DOM QA. Does not call deployed services.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),artifact=process.env.AI_QA_RUN_ID?path.join(root,'_workspace/verification',process.env.AI_QA_RUN_ID,'qa'):null;
const clone=x=>structuredClone(x),results=[];
const jsonbOrder=x=>Array.isArray(x)?x.map(jsonbOrder):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,jsonbOrder(x[k])])):x;
function empty(s){if(s.anyOf)return null;if(s.enum)return s.enum.includes(null)?null:s.enum[0];if(Array.isArray(s.type)&&s.type.includes('null'))return null;if(s.type==='object')return Object.fromEntries(Object.entries(s.properties).map(([k,v])=>[k,empty(v)]));return {array:[],string:'',integer:0,number:0,boolean:true}[s.type];}
async function check(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e.stack);}}
async function main(){
 const api=await import(pathToFileURL(path.join(root,'netlify/functions/api.mjs'))),core=await import(pathToFileURL(path.join(root,'netlify/functions/ai-core.mjs'))),background=await import(pathToFileURL(path.join(root,'netlify/functions/ai-analysis-background.mjs')));
 const env={AI_PROVIDER:'openai',SUPABASE_URL:'https://qa.supabase.test',SUPABASE_SERVICE_ROLE_KEY:'mock-service-key',OPENAI_API_KEY:'mock-ai-key',OPENAI_MODEL:'mock-model',OPENAI_TRANSCRIBE_MODEL:'mock-asr',BACKGROUND_HMAC_SECRET:'mock-hmac-key',URL:'https://qa.netlify.test',DEPLOY_PRIME_URL:'https://qa.netlify.test',AI_DAILY_LIMIT:'2'};
 const dto=()=>empty(core.schema),report=()=>({channel:'kakao',actor:'가상 QA',text:'가상 QA빌라 201호 두 명 고립',kind:'initial',attachments:[]});
 let world;
 const reset=()=>world={ws:{revision:1,document:{schema_version:1,synthetic:true,incidents:[],resources:[],uploads:{}}},jobs:new Map(),calls:[],used:0,quotaLimits:[],objects:new Map(),dispatch:202,redirect:false,dispatchOptions:null,casFail:false,claimed:0,openai:0};
 const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json'}});
 const originalFetch=global.fetch;
 global.fetch=async(url,options={})=>{
  const u=new URL(String(url));world.calls.push({url:u.href,method:options.method||'GET'});
  if(u.hostname==='qa.netlify.test'){world.dispatchOptions=options;if(world.redirect)throw new TypeError('redirect refused');return json({},world.dispatch);}
  if(u.hostname==='api.openai.com'){world.openai++;const body=JSON.parse(options.body);return json({status:'completed',id:'mock-response',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(dto())}]}]});}
  assert.equal(u.hostname,'qa.supabase.test','unexpected fetch destination');
  assert.equal(options.headers.Authorization,'Bearer mock-service-key');
  if(u.pathname==='/rest/v1/rescue_workspace')return json([clone(world.ws)]);
  if(u.pathname.startsWith('/storage/v1/object/authenticated/'))return new Response(world.objects.get(decodeURIComponent(u.pathname.split('/').at(-1)))||Buffer.from(''));
  if(u.pathname==='/storage/v1/object/rescue-private'&&options.method==='DELETE'){for(const k of JSON.parse(options.body).prefixes)world.objects.delete(k);return json({});}
  if(u.pathname.startsWith('/storage/v1/object/rescue-private/')){world.objects.set(decodeURIComponent(u.pathname.split('/').at(-1)),Buffer.from(options.body));return json({});}
  const name=u.pathname.split('/').at(-1),b=JSON.parse(options.body),failure=message=>json({message},400);
  if(name==='rescue_create_job'){world.quotaLimits.push(b.p_limit);if(b.p_limit!==null){if(world.used>=b.p_limit)return failure('AI_DAILY_LIMIT');world.used++;}world.jobs.set(b.p_job.id,clone(b.p_job));return json(b.p_job);}
  if(name==='rescue_get_job')return json(world.jobs.get(b.p_id)||null);
  if(name==='rescue_cas'){if(world.casFail||b.p_revision!==world.ws.revision)return failure('REVISION_CONFLICT');world.ws={revision:world.ws.revision+1,document:clone(b.p_document)};return json(world.ws);}
  if(name==='rescue_claim_job'){let job=world.jobs.get(b.p_id);if(!job||job.status!=='queued'||job.execution.input_sha256!==b.p_hash)return json(null);job.status='running';world.claimed++;return json(job);}
  if(name==='rescue_finish_job'){const job=world.jobs.get(b.p_id);if(job&&['queued','running'].includes(job.status))Object.assign(job,clone(b.p_payload));return json(job||null);}
  if(name==='rescue_confirm_job'){const job=world.jobs.get(b.p_id);if(job.status==='confirmed')return json(job.confirmation);if(world.casFail||b.p_revision!==world.ws.revision)return failure('REVISION_CONFLICT');world.ws={revision:world.ws.revision+1,document:clone(b.p_document)};job.status='confirmed';job.confirmation=clone(b.p_result);return json(b.p_result);}
  throw Error('unhandled RPC '+name);
 };
 const call=async(p,b,method=b?'POST':'GET',override=env)=>{try{const r=await api.handle({path:p,httpMethod:method,...(b?{body:JSON.stringify(b)}:{})},override);return {status:r.statusCode,value:JSON.parse(r.body),raw:r};}catch(e){return {status:e.status||500,value:{error:e.message,code:e.code}};}};
 const create=async()=>{const r=await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()});assert.equal(r.status,202);return world.jobs.get(r.value.id);};
 const ready=job=>{job.status='ready';job.analysis=dto();job.execution={...job.execution,model:'mock-model',response_id:'mock-response'};return job;};
 const confirm=(job,changes={title:'합성 QA',location:'가상 QA빌라 201호',people_count:null,intake119:dto().intake119})=>call(`/api/ai/analyses/${job.id}/confirm`,{synthetic:true,actor:'가상 QA 확인자',expected_revision:job.expected_revision,reason:'합성 원문 근거 확인',changes});
 await check('strict DTO unknown/missing/type/enum/GPS and valid nulls',()=>{const a=dto();core.validateAnalysis(a,report(),[]);for(const mutate of [a=>delete a.summary,a=>a.extra='closed',a=>a.proposed_changes.people_count=true,a=>a.intake119.location.gps={latitude:91,longitude:0},a=>a.intake119.location.gps={latitude:NaN,longitude:0},a=>a.intake119.location.gps={latitude:Infinity,longitude:0},a=>a.authenticity.status='verified']){const b=dto();mutate(b);assert.throws(()=>core.validateAnalysis(b,report(),[]));}});
 await check('evidence allowlist real substring field and proposal requirement',()=>{const a=dto();a.proposed_changes.location='가상 QA빌라';a.evidence=[{field:'location',source_id:'input',quote:'가상 QA빌라',observation:null,type:'text'}];core.validateAnalysis(a,report(),[]);for(const [k,v]of [['source_id','unknown'],['quote','invented'],['field','status'],['type','image_observation']]){const b=clone(a);b.evidence[0][k]=v;assert.throws(()=>core.validateAnalysis(b,report(),[]));}a.evidence=[];assert.throws(()=>core.validateAnalysis(a,report(),[]));});
 await check('text evidence cannot mix image observation overall and remaining counts stay separate',()=>{const r={...report(),text:'가상 세 명 요청, 두 명 구조 후 한 명 남아 있음'},a=dto();a.proposed_changes.people_count=3;a.remaining_people={count:1,basis:'원문 세 명 중 두 명 구조 후 한 명 미확인',needs_human_confirmation:true};a.evidence=[{field:'people_count',source_id:'input',type:'text',quote:'세 명 요청',observation:null}];core.validateAnalysis(a,r,[]);assert.equal(a.proposed_changes.people_count,3);assert.equal(a.remaining_people.count,1);a.evidence[0].observation='사진에서 물 관찰';assert.throws(()=>core.validateAnalysis(a,r,[]));});
 await check('candidate incident/report and person overlap IDs fenced',()=>{const incidents=[{id:'I1',reports:[{id:'R1',text:'가상 원문'}]}];const a=dto();a.duplicate_candidates=[{incident_id:'I1',report_id:'R1',reason:'가능성',needs_human_confirmation:true}];core.validateAnalysis(a,report(),incidents);a.duplicate_candidates[0].report_id='R2';assert.throws(()=>core.validateAnalysis(a,report(),incidents));a.duplicate_candidates=[];a.person_overlap=[{source_ids:['R2'],reason:'가능성',needs_human_confirmation:true}];assert.throws(()=>core.validateAnalysis(a,report(),incidents));});
 await check('citation schema binds each source type exact original ASR and observation form',()=>{
  const r={...report(),text:'합성 한빛 복합센터 원문',attachments:[{id:'P',media_type:'image'},{id:'A',media_type:'audio'},{id:'V',media_type:'video'}]},incidents=[{id:'I1',reports:[{id:'R1',text:'이전 개별 신고 원문'}]}],ts=[{attachment_id:'A',text:'한빛 복합센터 가산동 전사',model:'mock-asr'}],s=core.citationSchema(r,incidents,ts),branches=s.properties.evidence.items.anyOf;
  assert.deepEqual(branches.map(b=>b.properties.source_id.enum[0]),['input','R1','P','A']);
  const valid=[{field:'summary',source_id:'input',type:'text',quote:r.text,observation:null},{field:'summary',source_id:'R1',type:'text',quote:incidents[0].reports[0].text,observation:null},{field:'hazards',source_id:'P',type:'image_observation',quote:null,observation:'사진에서 물 관찰'},{field:'summary',source_id:'A',type:'audio_transcript',quote:ts[0].text,observation:null}];
  for(const e of valid){const a=dto();a.transcripts=clone(ts);a.evidence=[e];core.validateSchema(a,s);core.validateAnalysis(a,r,incidents,ts);for(const [key,value]of [['source_id','unknown'],['type',e.type==='text'?'audio_transcript':'text'],['extra',true]]){const b=clone(a);b.evidence[0][key]=value;assert.throws(()=>core.validateSchema(b,s));}}
  for(const quote of ['한빛복합센터 가산동 전사','한빛 복합센터 가상동 전사','한빛 복합센터']){const a=dto();a.evidence=[{...valid[3],quote}];assert.throws(()=>core.validateSchema(a,s),quote);}
  const mixed=dto();mixed.evidence=[{...valid[0],observation:'사진 관찰'}];assert.throws(()=>core.validateSchema(mixed,s));mixed.evidence=[{...valid[2],quote:'OCR처럼 인용'}];assert.throws(()=>core.validateSchema(mixed,s));
 });
 await check('citation schema is per request cloned base and does not weaken validator',()=>{
  const before=JSON.stringify(core.schema),a=core.citationSchema(report(),[]),b=core.citationSchema({...report(),text:'별도 원문'},[]);assert.equal(JSON.stringify(core.schema),before);assert.notEqual(a,b);assert.equal(b.properties.evidence.items.anyOf[0].properties.quote.enum[0],'별도 원문');a.properties.proposed_changes.properties.location.type='number';assert.equal(JSON.stringify(core.schema),before);
  const dtoSubstring=dto();dtoSubstring.evidence=[{field:'location',source_id:'input',type:'text',quote:'QA빌라',observation:null}];core.validateAnalysis(dtoSubstring,report(),[]);assert.throws(()=>core.validateSchema(dtoSubstring,core.citationSchema(report(),[])));dtoSubstring.evidence[0].quote='존재하지 않는 인용';assert.throws(()=>core.validateAnalysis(dtoSubstring,report(),[]));
 });
 await check('image has observations only and ASR cannot be forged',()=>{const r=report();r.attachments=[{id:'P',media_type:'image'},{id:'A',media_type:'audio'}];const ts=[{attachment_id:'A',text:'반환된 ASR',model:'mock-asr'}],a=dto();a.transcripts=clone(ts);a.evidence=[{field:'hazards',source_id:'P',quote:null,observation:'물 관찰',type:'image_observation'}];core.validateAnalysis(a,r,[],ts);a.evidence[0].quote='가짜 OCR';assert.throws(()=>core.validateAnalysis(a,r,[],ts));a.evidence=[];a.transcripts[0].text='seed 대본';assert.throws(()=>core.validateAnalysis(a,r,[],ts));});
 await check('no DB env API explicit 503; config has no secret',async()=>{reset();assert.equal((await call('/api/incidents',null,'GET',{})).status,503);const r=await call('/api/config',null,'GET',env);assert.equal(r.status,200);assert.equal(r.value.storage,'supabase');for(const secret of ['mock-service-key','mock-ai-key','mock-hmac-key'])assert(!JSON.stringify(r.value).includes(secret));assert.equal((await call('/api/config',null,'GET',{})).value.ai.model,null);assert.equal(world.calls.length,0);});
 await check('analysis queues raw report with zero workspace mutation',async()=>{reset();const before=clone(world.ws),j=await create();assert.deepEqual(world.ws,before);assert.deepEqual(j.report,report());assert.equal(j.status,'queued');assert.equal(j.execution.mode,'live');assert.equal(world.used,1);const r=await call('/api/ai/analyses/'+j.id);assert(!('context_incidents'in r.value));});
 await check('background origin accepts production and exact 24hex same-site preview',()=>{
  const production='qa-site.netlify.app',preview='0123456789abcdef01234567--'+production,settings={URL:'https://'+production};
  for(const host of [production,preview])assert.equal(api.backgroundOrigin({rawUrl:'https://'+host+'/api/ai/analyses?x=1'},settings),'https://'+host);
  assert.equal(api.backgroundOrigin({headers:{host:'attacker.test','x-forwarded-host':'attacker.test'}},settings),'https://'+production);
  assert.equal(api.backgroundOrigin({},{...settings,DEPLOY_URL:'https://'+preview}),'https://'+preview);
 });
 await check('malicious rawUrl schemes ports credentials lookalike previews rejected',()=>{
  const host='qa-site.netlify.app',settings={URL:'https://'+host};
  for(const rawUrl of ['http://'+host+'/api','https://'+host+':443/api','https://'+host+':444/api','https://user@'+host+'/api','https://'+host+'.attacker.test/api','https://other.netlify.app/api','https://'+host+'/\\@attacker.test','https://'+host+'/ space','https://abcdef--'+host+'/api','https://0123456789abcdef01234567--other.netlify.app/api','//'+host+'/api','https://'+host+'@attacker.test/api','https://'+host+'./api'])assert.throws(()=>api.backgroundOrigin({rawUrl},settings),e=>e.status===400&&e.code==='background_origin_invalid',rawUrl);
  for(const settings of [{},{URL:'http://'+host},{URL:'https://'+host+'/prefix'},{URL:'https://'+host+'?x=1'},{URL:'https://'+host,DEPLOY_URL:'https://attacker.test'},{URL:'https://'+host,DEPLOY_PRIME_URL:'http://'+host}])assert.throws(()=>api.backgroundOrigin({},settings),e=>e.status===503);
 });
 await check('API malicious rawUrl never creates job budget or signed dispatch',async()=>{
  for(const rawUrl of ['https://attacker.test/api/ai/analyses','https://qa.netlify.test:443/api/ai/analyses','http://qa.netlify.test/api/ai/analyses','https://user@qa.netlify.test/api/ai/analyses']){
   reset();await assert.rejects(()=>api.handle({path:'/api/ai/analyses',httpMethod:'POST',rawUrl,body:JSON.stringify({synthetic:true,incident_id:null,expected_revision:null,report:report()})},env),e=>e.status===400);assert.equal(world.jobs.size,0);assert.equal(world.used,0);assert.equal(world.dispatchOptions,null);assert(world.calls.every(c=>c.url.startsWith(env.SUPABASE_URL+'/')));
  }
 });
 await check('signed dispatch same-origin redirect error with failed raw job preservation',async()=>{
  reset();const before=clone(world.ws);world.redirect=true;
  const r=await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()});assert.equal(r.status,502);assert.equal(r.value.code,'background_dispatch_failed');assert.equal(world.dispatchOptions.redirect,'error');const job=[...world.jobs.values()][0];assert.equal(job.status,'failed');assert.deepEqual(job.report,report());assert.deepEqual(world.ws,before);assert.equal(world.calls.filter(c=>!c.url.startsWith(env.SUPABASE_URL+'/')).length,1);assert.equal(world.calls.at(-2).url,env.URL+'/.netlify/functions/ai-analysis-background');
 });
 await check('non synthetic malformed report unknown fields kind and revision rejected',async()=>{for(const mutate of [b=>b.synthetic=false,b=>b.provider='codex_cli',b=>b.hooks={command:'sh'},b=>b.report.status='closed',b=>b.report.kind='field',b=>b.expected_revision=0,b=>b.report.channel='email',b=>b.report.occurred_at='today']){reset();const b={synthetic:true,incident_id:null,expected_revision:null,report:report()};mutate(b);assert.equal((await call('/api/ai/analyses',b)).status,400);assert.equal(world.jobs.size,0);assert.equal(world.used,0);}});
 await check('SSRF external media seed MIME and source collision rejected',async()=>{for(const attachment of [{id:'X',url:'https://127.0.0.1/private',media_type:'image',source:'operator_upload'},{id:'input',url:'/media/flood-entrance.png',media_type:'image',source:'ai_generated'},{id:'P',url:'/media/flood-entrance.png',media_type:'audio',source:'ai_generated'}]){reset();const r=report();r.attachments=[{filename:'qa.png',caption:'',...attachment}];assert.equal((await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:r})).status,400);assert.equal(world.jobs.size,0);assert(world.calls.every(c=>c.url.startsWith('https://qa.supabase.test/')));}});
 await check('AI env absent budget 429 and dispatch failure preserves raw failed job',async()=>{reset();assert.equal((await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()},'POST',{...env,OPENAI_API_KEY:''})).status,503);assert.equal(world.used,0);await create();await create();assert.equal((await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()})).status,429);assert.equal(world.jobs.size,2);reset();world.dispatch=500;const r=await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()});assert.equal(r.status,502);const j=[...world.jobs.values()][0];assert.equal(j.status,'failed');assert.deepEqual(j.report,report());assert.equal(world.ws.document.incidents.length,0);});
 await check('null intake GPS/rescue values valid unknown intake keys rejected',async()=>{reset();const j=ready(await create());assert.equal((await confirm(j)).status,200);assert.equal(world.ws.document.incidents[0].people_count,null);assert.equal(world.ws.document.incidents[0].intake119.location.gps,null);reset();const bad={synthetic:true,incident_id:null,expected_revision:null,report:report(),intake119:{received_at:'AI invented'}};assert.equal((await call('/api/ai/analyses',bad)).status,400);});
 await check('confirm atomic raw original metadata audit and idempotency',async()=>{reset();const j=ready(await create());const a=await confirm(j);assert.equal(a.status,200);assert.equal(world.ws.document.incidents.length,1);const i=a.value.incident;assert.equal(i.status,'received');assert.equal(i.outcome,null);assert.equal(i.reports[0].text,report().text);assert.equal(i.reports[0].ai_analysis.analysis_id,j.id);assert.equal(i.audit.at(-1).action,'ai_review_confirmed');const before=clone(world.ws);assert.deepEqual(await confirm(j),a);assert.deepEqual(world.ws,before);});
 await check('failed drafts forbidden changes stale and CAS failures preserve document',async()=>{reset();const j=await create(),before=clone(world.ws);assert.equal((await confirm(j)).status,409);j.status='failed';assert.equal((await confirm(j)).status,409);ready(j);for(const forbidden of ['status','outcome','assigned_team_id','merge']){assert.equal((await confirm(j,{[forbidden]:'closed'})).status,400);assert.deepEqual(world.ws,before);}world.casFail=true;assert.equal((await confirm(j)).status,409);assert.deepEqual(world.ws,before);assert.equal(j.status,'ready');});
 await check('existing stale confirm and wrong revision reject without raw append',async()=>{reset();const j=ready(await create()),i=(await confirm(j)).value.incident;const r=report();r.kind='additional';const q=await call('/api/ai/analyses',{synthetic:true,incident_id:i.id,expected_revision:i.revision,report:r});assert.equal(q.status,202);const job=ready(world.jobs.get(q.value.id));world.ws.document.incidents[0].revision++;const before=clone(world.ws);assert.equal((await confirm(job,{summary:'검토'})).status,409);assert.deepEqual(world.ws,before);const b={synthetic:true,actor:'가상 QA',expected_revision:null,reason:'확인',changes:{summary:'검토'}};assert.equal((await call('/api/ai/analyses/'+job.id+'/confirm',b)).status,409);});
 await check('closed incident confirmed AI addition reopens preserving old outcome/raw',async()=>{reset();const initial=ready(await create()),created=await confirm(initial,{title:'QA',location:'가상 QA',people_count:2});const i=world.ws.document.incidents[0];i.status='closed';i.outcome={outcome:'rescued',confirmed_count:2,basis_report_id:i.reports[0].id,confirmed_at:new Date().toISOString()};const original=clone(i.reports),old=clone(i.outcome),r=report();r.kind='additional';r.text='한 명 추가 미확인';const q=await call('/api/ai/analyses',{synthetic:true,incident_id:i.id,expected_revision:i.revision,report:r});assert.equal(q.status,202);const j=ready(world.jobs.get(q.value.id));const out=await confirm(j,{summary:'새 미확인 대상 확인 필요',people_count:null});assert.equal(out.status,200);assert.equal(out.value.incident.status,'reviewing');assert.equal(out.value.incident.outcome,null);assert.equal(out.value.incident.outcome_history[0].outcome,old.outcome);assert.deepEqual(out.value.incident.reports.slice(0,original.length),original);assert.equal(out.value.incident.reports.at(-1).text,r.text);});
 await check('Node completion refuses negative and residual full-count reports',async()=>{for(const text of ['두 명 구조 확인 못함','2명 중 1명만 구조, 1명 남아 있음','두 명 전원 구조했으나 다른 주민 미확인']){reset();let i=(await call('/api/incidents',{title:'QA',location:'가상 QA',text:'두 명 고립',people_count:2})).value;i=(await call(`/api/incidents/${i.id}/reports`,{expected_revision:i.revision,channel:'field',kind:'field',text,people_count:2})).value;const before=clone(world.ws);assert.equal((await call(`/api/incidents/${i.id}/outcome`,{expected_revision:i.revision,outcome:'rescued',confirmed_count:2,basis_report_id:i.reports.at(-1).id,note:'QA'})).status,400);assert.deepEqual(world.ws,before);}});

 await check('optional quota absent empty null zero maps exactly to DB null',()=>{for(const value of [undefined,null,'',0,'0'])assert.equal(api.optionalDailyLimit({...env,AI_DAILY_LIMIT:value}),null);assert.equal(api.optionalDailyLimit({}),null);});
 await check('optional quota positive boundaries preserved as integers',()=>{for(const value of [1,'1',20,'20',1000,'1000'])assert.equal(api.optionalDailyLimit({...env,AI_DAILY_LIMIT:value}),Number(value));});
 await check('optional quota invalid settings fail closed without coercing objects booleans',()=>{for(const value of [-1,'-1',1001,'1001',1.5,'1.5','no',' ','\n',NaN,Infinity,true,false,{},[]])assert.throws(()=>api.optionalDailyLimit({...env,AI_DAILY_LIMIT:value}),e=>e.status===503);});
 await check('unset empty null zero allow more than20 queued jobs with budget untouched',async()=>{for(const value of [undefined,'',null,0,'0']){reset();const before=clone(world.ws);for(let n=0;n<30;n++){const r=await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()},'POST',{...env,AI_DAILY_LIMIT:value});assert.equal(r.status,202,'quota config '+String(value)+' job '+n);}assert.equal(world.jobs.size,30);assert.equal(world.used,0);assert.deepEqual(world.quotaLimits,Array(30).fill(null));assert.deepEqual(world.ws,before);assert([...world.jobs.values()].every(j=>j.synthetic===true&&j.status==='queued'&&j.report.text===report().text));}});
 await check('positive optional limit passes exact RPC limit and exposes429 contract',async()=>{reset();const limited={...env,AI_DAILY_LIMIT:'3'};const results=await Promise.all(Array.from({length:5},()=>call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()},'POST',limited)));assert.deepEqual(results.map(r=>r.status).sort(),[202,202,202,429,429]);assert.equal(world.used,3);assert.equal(world.jobs.size,3);assert.deepEqual(world.quotaLimits,Array(5).fill(3));assert(results.filter(r=>r.status===429).every(r=>r.value.code==='ai_daily_limit'));});
 await check('invalid quota request never creates or dispatches job',async()=>{for(const value of ['bad',' ',true,-1,1001,1.5]){reset();assert.equal((await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()},'POST',{...env,AI_DAILY_LIMIT:value})).status,503);assert.equal(world.jobs.size,0);assert.equal(world.used,0);assert.equal(world.quotaLimits.length,0);assert(!world.calls.some(c=>c.url.startsWith('https://qa.netlify.test')));}});
 await check('no quota still requires synthetic marker and initial revision null',async()=>{reset();const unlimited={...env,AI_DAILY_LIMIT:undefined};for(const body of [{synthetic:false,incident_id:null,expected_revision:null,report:report()},{synthetic:true,incident_id:null,expected_revision:1,report:report()}])assert.equal((await call('/api/ai/analyses',body,'POST',unlimited)).status,400);assert.equal(world.jobs.size,0);assert.equal(world.quotaLimits.length,0);});
 await check('no quota retains existing incident revision collision protection',async()=>{reset();const r=await call('/api/incidents',{title:'합성 quota QA',location:'가상빌라',text:'가상 두 명',people_count:2});assert.equal(r.status,201);const incident=r.value,unlimited={...env,AI_DAILY_LIMIT:'0'},before=clone(world.ws);const request={synthetic:true,incident_id:incident.id,expected_revision:incident.revision+1,report:{...report(),kind:'additional'}};assert.equal((await call('/api/ai/analyses',request,'POST',unlimited)).status,409);assert.equal(world.jobs.size,0);assert.equal(world.quotaLimits.length,0);request.expected_revision=incident.revision;assert.equal((await call('/api/ai/analyses',request,'POST',unlimited)).status,202);assert.deepEqual(world.ws,before);assert.equal(world.used,0);});
 await check('no quota does not activate default-disabled public provider',async()=>{reset();const disabled={...env,AI_PROVIDER:undefined,AI_DAILY_LIMIT:undefined};assert.equal((await call('/api/ai/analyses',{synthetic:true,incident_id:null,expected_revision:null,report:report()},'POST',disabled)).status,503);assert.equal(world.jobs.size,0);assert.equal(world.quotaLimits.length,0);const config=await call('/api/config',null,'GET',disabled);assert.equal(config.value.ai.provider,'disabled');assert.equal(config.value.ai.enabled,false);});
 await check('additive SQL nullable quota bounds atomic branch role fence old migration preserved',()=>{const sql=fs.readFileSync(path.join(root,'supabase/migrations/20261009_optional_ai_quota.sql'),'utf8');assert.match(sql,/create or replace function public\.rescue_create_job\(p_job jsonb,p_limit integer\)/);assert.match(sql,/p_limit is not null and \(p_limit<1 or p_limit>1000\)/);const branch=sql.match(/if p_limit is not null then([\s\S]*?)\n end if;/i);assert(branch);assert(branch[1].includes('insert into rescue_ai_budget'));assert(branch[1].includes('used<p_limit returning'));assert(branch[1].includes("message='AI_DAILY_LIMIT'"));const outside=sql.replace(branch[0],'');assert(!/insert into rescue_ai_budget|update rescue_ai_budget/i.test(outside));for(const token of ["p_job->>'synthetic' is distinct from 'true'","p_job->>'status' is distinct from 'queued'",'security definer set search_path=public','from public,anon,authenticated','grant execute on function public.rescue_create_job(jsonb,integer) to service_role'])assert(sql.includes(token),token);assert(!/truncate|drop table|delete from/i.test(sql));const old=fs.readFileSync(path.join(root,'supabase/migrations/202610090001_ai_service.sql'));assert.equal(require('node:crypto').createHash('sha256').update(old).digest('hex'),'6c535a7bb5ccec730276965c6ed1b2f137bad6d18d5c80e373bcf8502d90635c');});
 await check('private Storage byte roundtrip header limits and failed CAS cleanup',async()=>{reset();const bytes=fs.readFileSync(path.join(root,'data/media/flood-entrance.png')),body={filename:'qa.png',content_type:'image/png',data_base64:bytes.toString('base64')};const up=await call('/api/uploads',body);assert.equal(up.status,201);assert.equal(up.value.url,'/api/media/'+up.value.id);assert.deepEqual(world.objects.get(up.value.id),bytes);// Binary response is intentionally inspected directly.
 const raw=await api.handle({path:up.value.url,httpMethod:'GET'},env);assert.equal(raw.statusCode,200);assert.equal(raw.headers['Cache-Control'],'private, no-store');assert.deepEqual(Buffer.from(raw.body,'base64'),bytes);assert.equal((await call('/api/uploads',{...body,data_base64:Buffer.from('wrong').toString('base64')})).status,400);assert.equal((await call('/api/uploads',{...body,data_base64:'A'.repeat(4*1024*1024+4)})).status,413);reset();world.casFail=true;assert.equal((await call('/api/uploads',body)).status,409);assert.equal(world.objects.size,0);assert.deepEqual(world.ws.document.uploads,{});});
 await check('HMAC rejects forged expired and hash tampering before claim',async()=>{reset();const j=await create(),signed=core.signedPayload(j,env.BACKGROUND_HMAC_SECRET);assert(core.verifySignature(signed,env.BACKGROUND_HMAC_SECRET));for(const payload of [{id:j.id},{...signed,signature:'0'.repeat(64)},{...signed,input_sha256:'x'},core.signedPayload(j,env.BACKGROUND_HMAC_SECRET,Date.now()-301000)])assert.equal((await background.run({httpMethod:'POST',body:JSON.stringify(payload)},env)).statusCode,403);assert.equal(world.claimed,0);assert.equal(world.openai,0);});
 await check('background claim once successful mocked AI and no-env failure no fallback',async()=>{reset();const j=await create(),event={httpMethod:'POST',body:JSON.stringify(core.signedPayload(j,env.BACKGROUND_HMAC_SECRET))};assert.equal((await background.run(event,env)).statusCode,200);assert.equal(j.status,'ready');assert.equal(world.claimed,1);assert.equal(world.openai,1);await background.run(event,env);assert.equal(world.openai,1);reset();const fail=await create();await background.run({httpMethod:'POST',body:JSON.stringify(core.signedPayload(fail,env.BACKGROUND_HMAC_SECRET))},{...env,OPENAI_API_KEY:''});assert.equal(fail.status,'failed');assert.equal(fail.analysis,null);assert.equal(world.openai,0);});
 await check('background job hash binds raw input even with valid HMAC',async()=>{reset();const j=await create(),event={httpMethod:'POST',body:JSON.stringify(core.signedPayload(j,env.BACKGROUND_HMAC_SECRET))};j.report.text='modified';await background.run(event,env);assert.equal(j.status,'failed');assert.match(j.error,/지문/);assert.equal(world.openai,0);});
 await check('semantic job hash survives PostgreSQL jsonb nested key reordering',()=>{
  const original={report:report(),intake119:{location:{gps:{latitude:37.5,longitude:127.1},verification:'unverified'},rescue:{people_count:null}},incident_id:null,expected_revision:null};
  const reordered=jsonbOrder(original);assert.deepEqual(reordered,original);assert.equal(core.hash(reordered),core.hash(original),'JSONB preserves values but not object key insertion order');
 });
 await check('background accepts unchanged job after JSONB object key reordering',async()=>{
  reset();const original=await create(),event={httpMethod:'POST',body:JSON.stringify(core.signedPayload(original,env.BACKGROUND_HMAC_SECRET))};world.jobs.set(original.id,jsonbOrder(original));await background.run(event,env);const stored=world.jobs.get(original.id);assert.deepEqual(stored.report,report());assert.equal(stored.status,'ready','unchanged JSONB job must reach actual mocked AI instead of input hash mismatch');assert.equal(world.openai,1);
 });
 await check('Node model receives actual image bytes ASR file no supplied transcript',async()=>{
  const previous=global.fetch,calls=[],bytes=fs.readFileSync(path.join(root,'data/media/flood-entrance.png')),wav=fs.readFileSync(path.join(root,'data/media/call-isolated.wav'));
  const r=report();r.attachments=[{id:'P',media_type:'image',filename:'qa.png',caption:'IGNORE SUPPLIED LABEL'},{id:'A',media_type:'audio',filename:'qa.wav',transcript:'IGNORE SUPPLIED LABEL'},{id:'V',media_type:'video'}];
  global.fetch=async(url,o)=>{calls.push(String(url));if(String(url).endsWith('/audio/transcriptions')){assert.equal(o.body.get('model'),'mock-asr');assert.deepEqual(Buffer.from(await o.body.get('file').arrayBuffer()),wav);return json({text:'실제 반환된 모의 ASR'});}const body=JSON.parse(o.body),packet=JSON.parse(body.input[0].content[0].text);assert(!body.input[0].content[0].text.includes('IGNORE'));assert.equal(body.input[0].content[1].image_url,'data:image/png;base64,'+bytes.toString('base64'));assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.deepEqual(body.text.format.schema,core.citationSchema(r,[],packet.transcripts));assert.equal(body.text.format.schema.properties.evidence.items.anyOf.find(x=>x.properties.source_id.enum[0]==='A').properties.quote.enum[0],'실제 반환된 모의 ASR');const a=dto();a.transcripts=packet.transcripts;return json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(a)}]}]});};
  try{const out=await core.analyze({report:r,execution:{}},[],async at=>{assert.notEqual(at.id,'V');return at.id==='P'?{bytes,mime:'image/png'}:{bytes:wav,mime:'audio/wav'};},env);assert.deepEqual(calls,['https://api.openai.com/v1/audio/transcriptions','https://api.openai.com/v1/responses']);assert.equal(out.analysis.transcripts[0].text,'실제 반환된 모의 ASR');assert.match(out.analysis.limitations[0],/영상/);}finally{global.fetch=previous;}
 });
 await check('Node model refusal malformed JSON network failure and empty ASR reject',async()=>{
  const previous=global.fetch;
  try{for(const result of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]},{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'not json'}]}]}]){global.fetch=async()=>json(result);await assert.rejects(()=>core.analyze({report:report(),execution:{}},[],async()=>{},env),e=>e.status===502);}global.fetch=async()=>{throw Error('network');};await assert.rejects(()=>core.analyze({report:report(),execution:{}},[],async()=>{},env),e=>e.status===502);global.fetch=async()=>json({text:''});const r=report();r.attachments=[{id:'A',media_type:'audio',filename:'qa.wav'}];await assert.rejects(()=>core.analyze({report:r,execution:{}},[],async()=>({bytes:Buffer.from('mock'),mime:'audio/wav'}),env),e=>e.status===502);}finally{global.fetch=previous;}
 });
 global.fetch=originalFetch;
 const {createClient}=require('../web/cloud-client.js');
 await check('cloud transport starts explicitly no fallback same-origin and secret-free',async()=>{const calls=[],memory=new Map();const c=createClient({cloudDeployment:true,storage:()=>({getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)}),fetch:async(p,o)=>{calls.push({p,o});if(p==='/api/config')return json({storage:'unconfigured',ai:{configured:false}});return json({error:'저장 실패',code:'qa'},503);}});assert.equal((await c.boot()).mode,'unconfigured');await assert.rejects(()=>c.createAnalysis({}),e=>e.status===503);assert.equal(calls.length,1);await assert.rejects(()=>c.request('https://evil/api'),e=>e.status===400);await assert.rejects(()=>c.request('/api/../private'),e=>e.status===400);await assert.rejects(()=>c.request('/api/incidents'),e=>e.status===503&&e.code==='qa');assert.equal(calls[1].o.credentials,'same-origin');assert.equal(calls[1].o.cache,'no-store');});
 await check('cloud 404 never local fallback; local explicit transport retains legacy',async()=>{const missing=async()=>json({error:'없음'},404);assert.equal((await createClient({fetch:missing,cloudDeployment:true}).boot()).mode,'unavailable');assert.equal((await createClient({fetch:missing,cloudDeployment:false}).boot()).mode,'local');});
 await check('draft remember on create error preserve on confirm success clear',async()=>{const m=new Map();let fail=true;const c=createClient({storage:()=>({getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}),fetch:async p=>p==='/api/config'?json({storage:'supabase',ai:{configured:true}}):p.endsWith('/confirm')?fail?json({error:'다른 수정'},409):json({incident:{id:'I'}}):json({id:'AI-QA',status:'queued'})});await c.boot();await c.createAnalysis({});assert.equal(c.remembered(),'AI-QA');await assert.rejects(()=>c.confirm('AI-QA',{}),e=>e.status===409);assert.equal(c.remembered(),'AI-QA');fail=false;await c.confirm('AI-QA',{});assert.equal(c.remembered(),null);});
 await check('polling terminal and cancellation ignore late updates clear interval and deadline abort',async()=>{
  const timers=new Map(),cleared=[],updates=[];let serial=0,signal;
  const c=createClient({setTimer:(fn,ms)=>{timers.set(++serial,{fn,ms});return serial;},clearTimer:id=>{cleared.push(id);timers.delete(id);},fetch:async(_p,o)=>{signal=o.signal;return json({status:'queued'});}});
  const stop=c.startPolling('AI',{onUpdate:v=>updates.push(v.status)});await new Promise(r=>setImmediate(r));
  assert.deepEqual(updates,['queued']);assert.deepEqual([...timers.values()].map(t=>t.ms).sort((a,b)=>a-b),[1800,600000]);
  stop();assert.equal(timers.size,0);assert.deepEqual(new Set(cleared),new Set([1,2]));assert.equal(signal.aborted,true);
  let resolve,n=0;const late=createClient({fetch:()=>new Promise(r=>resolve=r)});const cancel=late.startPolling('AI',{onUpdate:()=>n++});cancel();resolve(json({status:'ready'}));await new Promise(r=>setImmediate(r));assert.equal(n,0);
  const terminalTimers=new Map();let terminalSerial=0;const done=createClient({setTimer:(fn,ms)=>{terminalTimers.set(++terminalSerial,{fn,ms});return terminalSerial;},clearTimer:id=>terminalTimers.delete(id),fetch:async()=>json({status:'ready'})});
  done.startPolling('AI',{onUpdate:v=>updates.push(v.status)});await new Promise(r=>setImmediate(r));assert.equal(updates.at(-1),'ready');assert.equal(terminalSerial,1);assert.equal(terminalTimers.size,0);
 });
 // Execute actual app render/parsing functions with a deliberately small DOM seam.
 const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{id,innerHTML:'',textContent:'',hidden:false,disabled:false,open:true,addEventListener(){},querySelectorAll(){return [];},querySelector(){return element('mock-child');},setAttribute(){},replaceChildren(){},append(){},focus(){},showModal(){this.open=true;},close(){this.open=false;}});return elements.get(id);};
 const session=new Map(),context={console,Intl,Date,setTimeout:()=>1,clearTimeout(){},document:{getElementById:element,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},documentElement:{dataset:{serviceMode:'cloud'}}},window:{addEventListener(){},scrollTo(){},RescueCloud:{mode:'unconfigured',config:{ai:{configured:false}},remembered:()=>null,boot:async()=>({mode:'unconfigured'})}},location:{hash:''},history:{},sessionStorage:{getItem:k=>session.get(k),setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},URL,AbortController};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'web/app.js'),'utf8'),context);await new Promise(r=>setImmediate(r));
 await check('UI actual review renders escaped raw media ASR evidence limitations human guard',()=>{context.qaDraft={id:'AI-QA',status:'ready',incident_id:null,report:{text:'<script>raw</script>',channel:'sms',actor:'가상 QA',attachments:[{url:'/api/media/UPL-qa',filename:'qa.png'}]},execution:{mode:'live',model:'mock-model'},analysis:dto()};context.qaDraft.analysis.transcripts=[{attachment_id:'A',text:'실제 반환된 모의 ASR',model:'qa-asr'}];context.qaDraft.analysis.evidence=[{field:'location',source_id:'input',quote:'원문 인용',type:'text'}];context.qaDraft.analysis.handoff=['인계 메모'];context.qaDraft.analysis.limitations=['영상 미지원'];vm.runInContext('aiState={stale:false,busy:false};renderAIReview(qaDraft)',context);const html=element('ai-fields').innerHTML;for(const text of ['&lt;script&gt;raw','/api/media/UPL-qa','실제 반환된 모의 ASR','원문 인용','영상 미지원','미확인 인원','name="reviewed"','name="reason"','name="intake_location_gps"'])assert(html.includes(text),text);assert(!html.includes('<script>raw'));});
 await check('UI nullable intake and unsafe media URLs preserve boundary',()=>{context.qaIntake=dto().intake119;context.qaValues={};const intake=vm.runInContext('intakeChanges(qaValues,qaIntake)',context);assert.equal(intake.location.gps,null);assert.equal(intake.rescue.people_count,null);assert.equal(intake.location.verification,'unverified');assert.equal(vm.runInContext('safeMedia("https://evil/secret")',context),null);assert.equal(vm.runInContext('safeMedia("/api/media/UPL-qa")',context),'/api/media/UPL-qa');context.qaValues.intake_rescue_people_count='-1';assert.throws(()=>vm.runInContext('intakeChanges(qaValues,qaIntake)',context));});
 await check('UI stale draft blocks confirm and errors preserve original input',()=>{vm.runInContext('aiState={stale:true,busy:false};renderAIReview(qaDraft)',context);assert.equal(element('ai-submit').disabled,true);assert.match(element('ai-error').textContent,/再|변경|재분석/);context.qaDraft.report.text='원문 보존';vm.runInContext('aiState={busy:false,draft:qaDraft};renderAIFailure("모의 API 오류")',context);assert.equal(element('ai-retry').hidden,false);assert.equal(element('ai-submit').hidden,true);assert.match(element('ai-error').textContent,/원문은 보존/);assert.equal(context.qaDraft.report.text,'원문 보존');});
 await check('configured UI says settings connected without promising AI success',()=>{context.window.RescueCloud.mode='cloud';context.window.RescueCloud.config={ai:{configured:true}};vm.runInContext('renderConnection()',context);const html=element('connection-status').innerHTML;assert(html.includes('OpenAI API 서버 설정 연결'));for(const bad of ['AI 분석 사용 가능','실제 AI 성공','AI 검증 완료'])assert(!html.includes(bad));context.window.RescueCloud.mode='unconfigured';vm.runInContext('renderConnection()',context);});
 await check('cloud index semantic docs links explicit offline no implicit fixture',()=>{const html=fs.readFileSync(path.join(root,'web/index.html'),'utf8'),store=fs.readFileSync(path.join(root,'web/pages-store.js'),'utf8');for(const p of ['/about/','/guide/','/references/','/judge/'])assert(html.includes('href="'+p+'"'));assert(html.includes('cloud-client.js'));assert(element('connection-status').innerHTML.includes('합성 사례 둘러보기'));assert.equal(context.window.RescuePages,undefined);assert.match(element('view').innerHTML,/업무 서버 연결 확인/);assert(store.includes("dataset.serviceMode !== 'cloud'"));});
 await check('SQL static guards CAS budget atomic claim timeout RLS private fence',()=>{const sql=fs.readFileSync(path.join(root,'supabase/migrations/202610090001_ai_service.sql'),'utf8');for(const p of ['revision=p_revision','used<p_limit',"payload->>'status'='queued'",'for update',"interval '10 minutes'",'enable row level security','from public,anon,authenticated','as restrictive',"'rescue-private','rescue-private',false"])assert(sql.includes(p),p);assert(!/truncate|drop table|delete from/i.test(sql));});
 if(artifact){fs.mkdirSync(artifact,{recursive:true});fs.writeFileSync(path.join(artifact,'node-checks.json'),JSON.stringify({mode:'mocked_fetch_and_DOM',live_calls:false,checks:results},null,2)+'\n');}
 console.log(JSON.stringify({passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length}));if(results.some(r=>r.status==='failed'))process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
