'use strict';
// Independent local/provider/retry QA. Model, SDK, Whisper, DB calls are mocked.
const assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const cp=require('node:child_process'),{syncBuiltinESMExports}=require('node:module'),{PassThrough}=require('node:stream'),{EventEmitter}=require('node:events'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),checks=[];
const artifact=process.env.AI_QA_RUN_ID?path.join(root,'_workspace/verification',process.env.AI_QA_RUN_ID,'qa'):null;
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json'}});
const clone=x=>structuredClone(x);
function empty(s){if(s.anyOf)return null;if(s.enum)return s.enum.includes(null)?null:s.enum[0];if(Array.isArray(s.type)&&s.type.includes('null'))return null;if(s.type==='object')return Object.fromEntries(Object.entries(s.properties).map(([k,v])=>[k,empty(v)]));return {array:[],string:'',integer:0,number:0,boolean:true}[s.type];}
async function check(name,fn){try{await fn();checks.push({name,status:'passed'});console.log('PASS',name);}catch(e){checks.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e.stack);}}
function fakeSpawn(handler){const old=cp.spawn;cp.spawn=(exe,args,options)=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{queueMicrotask(()=>child.emit('close',143));return true;};queueMicrotask(async()=>{try{const out=await handler(exe,args,options);child.stdout.write(out?.stdout||'available');child.stderr.write(out?.stderr||'');child.emit('close',out?.code||0);}catch{child.emit('error',new Error('mock launch'));}});return child;};syncBuiltinESMExports();return()=>{cp.spawn=old;syncBuiltinESMExports();};}
async function main(){
 const core=await import(pathToFileURL(path.join(root,'netlify/functions/ai-core.mjs'))),cli=await import(pathToFileURL(path.join(root,'scripts/analyzer_codex.mjs'))),server=await import(pathToFileURL(path.join(root,'scripts/serve_codex_demo.mjs'))),api=await import(pathToFileURL(path.join(root,'netlify/functions/api.mjs'))),background=await import(pathToFileURL(path.join(root,'netlify/functions/ai-analysis-background.mjs')));
 const dto=()=>empty(core.schema),png=fs.readFileSync(path.join(root,'data/media/flood-entrance.png')),wav=fs.readFileSync(path.join(root,'data/media/call-isolated.wav'));
 const report=()=>({channel:'sms',actor:'가상 담당자',kind:'initial',text:'가상 QA빌라 두 명 고립; $(touch injected) " ; <script>data</script>',attachments:[]});
 const job=(attachments=[])=>({id:'AI-QA',incident_id:null,expected_revision:null,report:{...report(),attachments},context_incidents:[],execution:{}});
 const attachments=[{id:'P',url:'/api/media/P',filename:'evil name $(touch injected).png',media_type:'image',caption:'NOT ACTUAL VISION'},{id:'A',url:'/api/media/A',filename:'audio name.wav',media_type:'audio',transcript:'NOT ACTUAL ASR'}];
 const actual='  실제 모의 ASR  원문 .\n';
 const reader=async at=>at.media_type==='image'?{bytes:png,mime:'image/png'}:{bytes:wav,mime:'audio/wav'};
 function executor({invalid=0,alterASR=false,overflow=false,advance}={}){
  const calls=[],temps=new Set();let attempts=0,asr=0;
  const execute=async(exe,args,options)=>{
   calls.push({exe,args:[...args],options});temps.add(options.cwd);
   if(exe!=='codex'){asr++;assert(args.includes('--file'));const file=args[args.indexOf('--file')+1];assert.deepEqual(fs.readFileSync(file),wav);return {stdout:JSON.stringify({text:actual,model:'openai-whisper/small'}),stderr:'',code:0};}
   attempts++;if(attempts>1){const invalidFile=path.join(options.cwd,'invalid-attempt-1.json');assert.equal(fs.statSync(invalidFile).mode&0o777,0o600);}const packet=JSON.parse(options.stdin.slice(options.stdin.indexOf('{"synthetic"')));const a=dto();a.transcripts=clone(packet.transcripts);
   if(attempts<=invalid)a.evidence=[{field:'summary',source_id:'input',quote:'없는 인용',observation:null,type:'text'}];
   if(alterASR&&a.transcripts.length)a.transcripts[0].text=a.transcripts[0].text.trim();
   const output=args[args.indexOf('--output-last-message')+1];await fsp.writeFile(output,JSON.stringify(a));
   if(advance)advance();
   return {stdout:overflow?'x'.repeat(4*1024*1024+1):JSON.stringify({type:'thread.started',thread_id:'mock-cli-'+attempts})+'\n'+JSON.stringify({type:'turn.completed',usage:{input_tokens:10,output_tokens:2}}),stderr:'',code:0};
  };
  return {execute,calls,temps,get attempts(){return attempts;},get asr(){return asr;}};
 }
 async function cleaned(h){for(const temp of h.temps)assert.equal(fs.existsSync(temp),false,'isolated temp must be removed after success/failure');}
 await check('Codex fixed argv read-only schema stdin images spaces inherited model env isolation',async()=>{
  const sentinel={SUPABASE_SERVICE_ROLE_KEY:'secret-qa-db',SUPABASE_URL:'https://secret.invalid',OPENAI_API_KEY:'secret-qa-ai',BACKGROUND_HMAC_SECRET:'secret-qa-hmac'};const previous={};for(const[k,v]of Object.entries(sentinel)){previous[k]=process.env[k];process.env[k]=v;}
  const h=executor();try{const out=await cli.analyzeCodex(job(attachments),[],reader,{LOCAL_WHISPER_MODEL:'small'},{execute:h.execute});assert.equal(h.attempts,1);assert.equal(h.asr,1);const call=h.calls.find(c=>c.exe==='codex'),args=call.args;assert.equal(args[0],'exec');assert.equal(args[args.indexOf('--sandbox')+1],'read-only');assert(args.includes('--ephemeral'));assert(args.includes('--skip-git-repo-check'));assert.equal(args.at(-1),'-');assert(!args.includes('--model'));assert(!args.includes('--dangerously-bypass-approvals-and-sandbox'));assert(args[args.indexOf('--output-schema')+1].includes('Codex 2026 Hack'));assert.equal(args.filter(x=>x==='--image').length,1);assert(!args.some(x=>x.includes('$(touch')));assert(call.options.stdin.includes('$(touch injected)'));assert(!call.options.stdin.includes('NOT ACTUAL'));for(const key of Object.keys(sentinel))assert.equal(call.options.env[key],undefined,key);assert.equal(out.execution.model_inherited,true);assert.equal(out.execution.provider,'codex_cli');assert.equal(out.execution.cli_session_id,'mock-cli-1');assert.equal(out.execution.asr_model,'openai-whisper/small');assert.equal(out.analysis.transcripts[0].text,actual);assert.equal(out.execution.attempt_count,1);assert.equal(out.execution.regeneration_count,0);assert.equal(out.execution.model,undefined);await cleaned(h);}finally{for(const[k,v]of Object.entries(previous))if(v===undefined)delete process.env[k];else process.env[k]=v;}
 });
 await check('Codex max one regeneration preserves exact packet images and ASR once metadata',async()=>{const h=executor({invalid:1});const out=await cli.analyzeCodex(job(attachments),[],reader,{LOCAL_WHISPER_MODEL:'small'},{execute:h.execute});assert.equal(h.attempts,2);assert.equal(h.asr,1);const runs=h.calls.filter(c=>c.exe==='codex'),packets=runs.map(c=>JSON.parse(c.options.stdin.slice(c.options.stdin.indexOf('{"synthetic"'))));assert.deepEqual(packets[1].report,packets[0].report);assert.deepEqual(packets[1].transcripts,packets[0].transcripts);assert.deepEqual(packets[1].allowed_sources,packets[0].allowed_sources);assert.deepEqual(runs[1].args.filter((v,n,a)=>n&&a[n-1]==='--image'),runs[0].args.filter((v,n,a)=>n&&a[n-1]==='--image'));assert(packets[1].validation_feedback.previous_invalid_response.includes('없는 인용'));assert.equal(out.execution.attempts[0].status,'validation_failed');assert.equal(out.execution.attempts[1].status,'validated');assert.equal(out.execution.attempt_count,2);assert.equal(out.execution.regeneration_count,1);assert.deepEqual(out.execution.usage,{input_tokens:20,output_tokens:4});assert(out.execution.completed_at);assert(out.execution.elapsed_ms>=0);await cleaned(h);});
 await check('Codex two strict failures produce failure execution and no third attempt',async()=>{const h=executor({invalid:99});await assert.rejects(()=>cli.analyzeCodex(job(attachments),[],reader,{LOCAL_WHISPER_MODEL:'small'},{execute:h.execute}),e=>{assert.equal(e.execution.attempt_count,2);assert.equal(e.execution.regeneration_count,1);assert(e.execution.attempts.every(a=>a.status==='validation_failed'));assert.equal(e.execution.usage.input_tokens,20);return e.status===502;});assert.equal(h.attempts,2);assert.equal(h.asr,1);await cleaned(h);});
 await check('Codex normalized ASR rejected both attempts preserving actual whitespace',async()=>{const h=executor({alterASR:true});await assert.rejects(()=>cli.analyzeCodex(job(attachments),[],reader,{LOCAL_WHISPER_MODEL:'small'},{execute:h.execute}),e=>e.status===502&&e.execution.attempt_count===2);assert.equal(h.asr,1);await cleaned(h);});
 await check('Codex bad MIME/header and unsupported video never fabricates perception',async()=>{let n=0;await assert.rejects(()=>cli.analyzeCodex(job([attachments[0]]),[],async()=>({bytes:Buffer.from('bad'),mime:'image/png'}),{}, {execute:async()=>n++}),e=>e.status===400);assert.equal(n,0);const h=executor();const out=await cli.analyzeCodex(job([{id:'V',media_type:'video'}]),[],async()=>{throw Error('video cannot be read');},{},{execute:h.execute});assert.match(out.analysis.limitations[0],/영상/);assert.equal(h.attempts,1);await cleaned(h);});
 await check('Codex output 4MiB and total 540sec budget blocks runaway retry',async()=>{let h=executor({overflow:true});await assert.rejects(()=>cli.analyzeCodex(job(),[],reader,{}, {execute:h.execute}),e=>e.status===502&&e.execution.attempt_count===1);assert.equal(h.attempts,1);await cleaned(h);const old=Date.now;let time=old();Date.now=()=>time;h=executor({invalid:1,advance:()=>time+=540001});try{await assert.rejects(()=>cli.analyzeCodex(job(),[],reader,{}, {execute:h.execute}),e=>e.status===502&&e.execution.attempt_count===1);assert.equal(h.attempts,1);assert(h.calls[0].options.timeout<=480000);assert(h.calls[0].options.maxBuffer<=4*1024*1024);await cleaned(h);}finally{Date.now=old;}});
 await check('boundedSpawn array shell false stdin opaque spaces and execution limits',async()=>{const temp=await fsp.mkdtemp(path.join(os.tmpdir(),'qa spawn spaces '));try{const opaque='$(touch injected); quote " raw';const out=await cli.boundedSpawn(process.execPath,['-e','let s="";process.stdin.on("data",x=>s+=x);process.stdin.on("end",()=>console.log(JSON.stringify({args:process.argv.slice(1),stdin:s,cwd:process.cwd()})))',opaque],{cwd:temp,env:{PATH:process.env.PATH},stdin:opaque,timeout:2000,maxBuffer:4096});const value=JSON.parse(out.stdout);assert.equal(value.args[0],opaque);assert.equal(value.stdin,opaque);assert.equal(value.cwd,fs.realpathSync(temp));assert.equal(fs.existsSync(path.join(temp,'injected')),false);await assert.rejects(()=>cli.boundedSpawn(process.execPath,['-e','process.stdout.write("A".repeat(2000));setTimeout(()=>{},1000)'],{timeout:2000,maxBuffer:100}),e=>e.status===502);await assert.rejects(()=>cli.boundedSpawn(process.execPath,['-e','setTimeout(()=>{},1000)'],{timeout:30,maxBuffer:1024}),e=>e.status===502);await assert.rejects(()=>cli.boundedSpawn('/nonexistent-qa-executable',[],{timeout:100}),e=>e.status===503);}finally{await fsp.rm(temp,{recursive:true,force:true});}});
 await check('CLI status uses fixed login status and sanitizes server secrets',async()=>{const previous=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='secret-qa';let observed;const restore=fakeSpawn((exe,args,o)=>{observed={exe,args,o};return{stdout:'Logged in using ChatGPT'};});try{const result=await cli.cliStatus();assert.equal(result.logged_in,true);assert.equal(observed.exe,'codex');assert.deepEqual(observed.args,['login','status']);assert.equal(observed.o.env.OPENAI_API_KEY,undefined);assert.equal(observed.o.shell,false);}finally{restore();if(previous===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=previous;}});
 const apiEnv={SUPABASE_URL:'https://qa.supabase.test',SUPABASE_SERVICE_ROLE_KEY:'mock-server-db',OPENAI_API_KEY:'mock-server-openai',OPENAI_MODEL:'mock-model',BACKGROUND_HMAC_SECRET:'mock-hmac',URL:'https://qa.netlify.app'};
 await check('public provider defaults disabled settings read-only no keys',async()=>{const config=await api.handle({path:'/api/config',httpMethod:'GET'},apiEnv),a=JSON.parse(config.body);assert.equal(a.ai.provider,'disabled');assert.equal(a.ai.enabled,false);assert.equal(a.ai.configured,false);const settings=await api.handle({path:'/api/settings',httpMethod:'GET'},apiEnv);assert.equal(JSON.parse(settings.body).mutable,false);for(const secret of Object.values(apiEnv).filter(x=>x.startsWith('mock-server')))assert(!settings.body.includes(secret));await assert.rejects(()=>api.handle({path:'/api/settings',httpMethod:'POST',body:'{"provider":"openai"}'},apiEnv),e=>e.status===405);const enabled=JSON.parse((await api.handle({path:'/api/config',httpMethod:'GET'},{...apiEnv,AI_PROVIDER:'openai'})).body);assert.equal(enabled.ai.enabled,true);assert.equal(enabled.ai.local_demo,false);const impossible=JSON.parse((await api.handle({path:'/api/config',httpMethod:'GET'},{...apiEnv,AI_PROVIDER:'codex_cli'})).body);assert.equal(impossible.ai.enabled,false);});
 const restoreProbe=fakeSpawn(()=>({stdout:'available'}));
 try{
  const origin='http://127.0.0.1:8769',headers={host:'127.0.0.1:8769'};
  const runtime=()=>server.createDemoRuntime({env:apiEnv,origin,probe:async()=>({installed:true,logged_in:true,login_status:'mock ChatGPT'})});
  const request=(r,path,method='GET',body,h=headers)=>r.request({path,httpMethod:method,headers:h,...(body?{body:JSON.stringify(body)}:{})});
  await check('local exact loopback constructor and hostile Host Origin reject',async()=>{for(const origin of ['https://127.0.0.1:8769','http://localhost:8769','http://0.0.0.0:8769','http://127.0.0.1:8769/path','http://u@127.0.0.1:8769'])assert.throws(()=>server.createDemoRuntime({origin}));const r=runtime();for(const h of [{host:'attacker.test'},{host:'localhost:8769'},{host:'127.0.0.1:8768'},{host:'127.0.0.1:8769',origin:'https://attacker.test'},{host:'127.0.0.1:8769',origin:'null'}])assert.equal((await request(r,'/api/config','GET',null,h)).statusCode,403);assert.equal((await request(r,'/api/config')).statusCode,200);});
  await check('local session HttpOnly SameSite CSRF and exact Origin protect setting',async()=>{const r=runtime(),initial=await request(r,'/api/settings'),settings=JSON.parse(initial.body),cookie=initial.headers['Set-Cookie'].split(';')[0];assert.match(initial.headers['Set-Cookie'],/HttpOnly; SameSite=Strict/);assert.equal(settings.local_demo,true);assert.equal(settings.mutable,true);assert.match(settings.csrf_token,/^[a-f0-9]{64}$/);assert(!initial.body.includes('mock-server-db'));const valid={...headers,origin,cookie,'x-csrf-token':settings.csrf_token};for(const bad of [{...valid,origin:undefined},{...valid,cookie:''},{...valid,'x-csrf-token':'0'.repeat(64)},{...valid,origin:'http://127.0.0.1:8768'}])assert.equal((await request(r,'/api/settings','POST',{provider:'disabled'},bad)).statusCode,403);const changed=await request(r,'/api/settings','POST',{provider:'disabled'},valid);assert.equal(changed.statusCode,200);assert.equal(JSON.parse(changed.body).provider,'disabled');assert.equal((await r.aiConfig()).enabled,false);});
  await check('local setting accepts provider only no key hook command env writes',async()=>{const r=runtime(),first=await request(r,'/api/settings'),value=JSON.parse(first.body),h={...headers,origin,cookie:first.headers['Set-Cookie'].split(';')[0],'x-csrf-token':value.csrf_token};for(const body of [{provider:'openai',OPENAI_API_KEY:'attempt'},{provider:'codex_cli',command:'sh'},{provider:'openai',hooks:{}},{provider:'unknown'},{provider:'openai',env:{}},[]])assert.equal((await request(r,'/api/settings','POST',body,h)).statusCode,400);assert.equal((await request(r,'/api/settings','POST',{provider:'openai'},h)).statusCode,200);assert.equal((await r.aiConfig()).provider,'openai');const missing=server.createDemoRuntime({env:{},origin,probe:async()=>({installed:false,logged_in:false})}),get=await request(missing,'/api/settings'),s=JSON.parse(get.body),mh={...headers,origin,cookie:get.headers['Set-Cookie'].split(';')[0],'x-csrf-token':s.csrf_token};assert.equal((await request(missing,'/api/settings','POST',{provider:'openai'},mh)).statusCode,503);});
  await check('local expired session cannot change provider and public SDK cannot write',async()=>{const r=runtime(),first=await request(r,'/api/settings'),s=JSON.parse(first.body),h={...headers,origin,cookie:first.headers['Set-Cookie'].split(';')[0],'x-csrf-token':s.csrf_token};const old=Date.now;Date.now=()=>old()+3600001;try{assert.equal((await request(r,'/api/settings','POST',{provider:'disabled'},h)).statusCode,403);}finally{Date.now=old;}const {createClient}=require('../web/cloud-client.js');const writes=[],storage=[];const publicClient=createClient({storage:()=>({setItem:(...a)=>storage.push(a)}),fetch:async(p,o)=>{writes.push({p,o});return json({provider:'disabled',local_demo:false,mutable:false});}});await publicClient.getSettings();await assert.rejects(()=>publicClient.setProvider('openai'),e=>e.status===403);assert.equal(writes.length,1);assert.equal(storage.length,0);});
 }finally{restoreProbe();}
 await check('SDK local provider sends only provider and CSRF token without storage',async()=>{const {createClient}=require('../web/cloud-client.js'),calls=[],stores=[];const c=createClient({storage:()=>({setItem:(...a)=>stores.push(a)}),fetch:async(p,o)=>{calls.push({p,o});if(p==='/api/config')return json({storage:'supabase',ai:{provider:'openai',enabled:true}});return json({local_demo:true,mutable:true,csrf_token:'mock-csrf',provider:'codex_cli'});}});await c.getSettings();await c.setProvider('openai');const write=calls.find(x=>x.o.method==='POST');assert.deepEqual(JSON.parse(write.o.body),{provider:'openai'});assert.equal(write.o.headers['X-CSRF-Token'],'mock-csrf');assert.equal(write.o.credentials,'same-origin');assert.equal(stores.length,0);await assert.rejects(()=>c.setProvider('sh'),e=>e.status===400);});
 await check('local worker serial concurrency queue limit and stored provider binding',async()=>{
  let release;const gate=new Promise(r=>release=r),processed=[],models=[];let active=0,maxActive=0;
  const jobs=new Map([['J1',{id:'J1',execution:{provider:'codex_cli',input_sha256:'h1'}}],['J2',{id:'J2',execution:{provider:'codex_cli',input_sha256:'h2'}}]]);
  const r=server.createDemoRuntime({env:apiEnv,maxQueued:1,probe:async()=>({installed:true,logged_in:true}),cliAnalyzer:async j=>{models.push(j.execution.provider);return{};},worker:async(id,h,e,hooks)=>{active++;maxActive=Math.max(maxActive,active);if(id==='J1')await gate;await hooks.analyze(jobs.get(id),[],async()=>{});processed.push(id);active--;}});
  await r.hooks.dispatch(jobs.get('J1'));await r.hooks.dispatch(jobs.get('J2'));await assert.rejects(()=>r.hooks.dispatch({id:'J3',execution:{input_sha256:'h3'}}),e=>e.status===503);assert.equal(active,1);release();await new Promise(r=>setImmediate(r));assert.deepEqual(processed,['J1','J2']);assert.deepEqual(models,['codex_cli','codex_cli']);assert.equal(maxActive,1);
 });
 await check('strict DTO shape does not prove reporter factual accuracy',()=>{const a=dto();a.intake119.reporter.display_name='가상 담당자';core.validateAnalysis(a,report(),[]);assert.notEqual(report().text.includes(a.intake119.reporter.display_name),true);assert.equal(a.authenticity.status,'unverified');});
 await check('background failure preserves attempts metadata local provider blocked on cloud',async()=>{let stored,jobValue=job();jobValue.execution={provider:'codex_cli'};jobValue.execution.input_sha256=core.hash({report:jobValue.report,intake119:null,incident_id:null,expected_revision:null});const db={rpc:async(name,b)=>name==='rescue_claim_job'?jobValue:(stored=b.p_payload),workspace:async()=>({document:{uploads:{}}})};let analyzed=0;await background.processJob(jobValue.id,jobValue.execution.input_sha256,apiEnv,{database:db,analyze:async()=>analyzed++});assert.equal(stored.status,'failed');assert.equal(analyzed,0);jobValue.execution.provider='openai';const failure=new core.APIError(502,'strict failure');failure.execution={provider:'openai',attempt_count:2,regeneration_count:1,attempts:[{status:'validation_failed'},{status:'validation_failed'}]};await background.processJob(jobValue.id,jobValue.execution.input_sha256,{...apiEnv,AI_PROVIDER:'openai'},{database:db,analyze:async()=>{throw failure;}});assert.equal(stored.status,'failed');assert.deepEqual(stored.execution,failure.execution);});
 const originalFetch=global.fetch;
 const ownedTemps=[],originalMkdtemp=fsp.mkdtemp;fsp.mkdtemp=async prefix=>{const temp=await originalMkdtemp(prefix);if(prefix.includes('rescue-openai-'))ownedTemps.push(temp);return temp;};syncBuiltinESMExports();
 const tempDirs=()=>ownedTemps.filter(temp=>fs.existsSync(temp)).sort();
 await check('OpenAI one regeneration identical bytes ASR once exact text and metadata cleanup',async()=>{const before=tempDirs(),calls=[];let asr=0,n=0;global.fetch=async(url,o)=>{calls.push({url:String(url),o});if(String(url).endsWith('/audio/transcriptions')){asr++;assert.deepEqual(Buffer.from(await o.body.get('file').arrayBuffer()),wav);return json({text:actual});}n++;const body=JSON.parse(o.body),packet=JSON.parse(body.input[0].content[0].text),a=dto();a.transcripts=clone(packet.transcripts);if(n===1)a.evidence=[{field:'summary',source_id:'input',quote:'없는 인용',observation:null,type:'text'}];return json({status:'completed',id:'mock-response-'+n,usage:{input_tokens:7,output_tokens:3},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(a)}]}]});};try{const out=await core.analyze(job(attachments),[],reader,{...apiEnv,OPENAI_TRANSCRIBE_MODEL:'mock-asr'});assert.equal(n,2);assert.equal(asr,1);const responseCalls=calls.filter(c=>c.url.endsWith('/responses')).map(c=>JSON.parse(c.o.body));const packets=responseCalls.map(b=>JSON.parse(b.input[0].content[0].text));assert.deepEqual(packets[0].report,packets[1].report);assert.deepEqual(packets[0].transcripts,packets[1].transcripts);assert.deepEqual(responseCalls[0].input[0].content.slice(1),responseCalls[1].input[0].content.slice(1));assert.equal(out.analysis.transcripts[0].text,actual);assert.equal(out.execution.attempt_count,2);assert.equal(out.execution.regeneration_count,1);assert.deepEqual(out.execution.usage,{input_tokens:14,output_tokens:6});assert.equal(out.execution.attempts[0].response_id,'mock-response-1');assert.equal(out.execution.attempts[0].status,'validation_failed');assert.equal(out.execution.attempts[1].status,'validated');assert.deepEqual(tempDirs(),before);}finally{global.fetch=originalFetch;}});
 await check('OpenAI strict second failure remains failed with two attempts and no fallback',async()=>{const before=tempDirs();let n=0;global.fetch=async()=>{n++;const a=dto();a.extra='closed';return json({status:'completed',id:'mock-'+n,output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(a)}]}]});};try{await assert.rejects(()=>core.analyze(job(),[],reader,apiEnv),e=>e.status===502&&e.execution.attempt_count===2&&e.execution.regeneration_count===1&&e.execution.attempts.every(a=>a.status==='validation_failed'));assert.equal(n,2);assert.deepEqual(tempDirs(),before);}finally{global.fetch=originalFetch;}});
 await check('OpenAI refusal network output and total time limits do not retry execution errors',async()=>{for(const mode of ['refusal','network','buffer','deadline']){const before=tempDirs();let n=0;const oldNow=Date.now;let current=oldNow();global.fetch=async()=>{n++;if(mode==='network')throw Error('network');if(mode==='buffer')return new Response('X'.repeat(4*1024*1024+1));return json({status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]});};try{if(mode==='deadline')Date.now=()=>current;const j=mode==='deadline'?job([attachments[0]]):job();await assert.rejects(()=>core.analyze(j,[],async at=>{current+=540001;return reader(at);},apiEnv),e=>e.status===502);assert.equal(n,mode==='deadline'?0:1);assert.deepEqual(tempDirs(),before);}finally{Date.now=oldNow;global.fetch=originalFetch;}}});
 fsp.mkdtemp=originalMkdtemp;syncBuiltinESMExports();
 // Execute real frontend startup/navigation against a minimal DOM and mock service.
 function ui({failList=false,local=false}={}){
  const elements=new Map(),calls=[];let listFailure=failList;
  const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',hidden:false,disabled:false,isConnected:true,classList:{toggle(){}},addEventListener(){},querySelectorAll(){return [];},querySelector(){return el('child');},setAttribute(){},removeAttribute(){},replaceChildren(){},append(){},focus(){},close(){},showModal(){}});return elements.get(id);};
  const seed=JSON.parse(fs.readFileSync(path.join(root,'data/seed.json'))),settings={provider:local?'codex_cli':'disabled',local_demo:local,mutable:local,capabilities:{codex_cli:{installed:true,logged_in:true},openai:{configured:false},asr:{available:false}}};
  const context={console,Intl,Date,URL,AbortController,setTimeout:()=>1,clearTimeout(){},document:{getElementById:el,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},createElement:()=>el('created')},window:{addEventListener(){},scrollTo(){},RescueCloud:{mode:'cloud',config:{ai:{provider:settings.provider,enabled:local}},boot:async()=>{},getSettings:async()=>{calls.push('settings');return clone(settings);},remembered:()=>null,request:async p=>{calls.push(p);if(listFailure)throw Error('목록 연결 실패');return p==='/api/incidents'?clone(seed):clone(seed.incidents.find(i=>p.endsWith(i.id)));}}},location:{hash:'#settings'},history:{pushState(){}},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'web/app.js'),'utf8'),context);return {context,el,calls,allowList:()=>listFailure=false};
 }
 await check('cold #settings loads workspace before field active navigation no false empty',async()=>{for(const local of [false,true]){const u=ui({local});await new Promise(r=>setImmediate(r));assert(u.calls.includes('/api/incidents'));assert(u.calls.includes('settings'));assert.match(u.el('view').innerHTML,/설정 · AI 연결/);assert.equal(vm.runInContext('state.listLoaded',u.context),true);u.context.location.hash='#field';await vm.runInContext('route(false)',u.context);assert(u.el('view').innerHTML.includes('INC-20261008'));assert(!u.el('view').innerHTML.includes('진행 사건이 없습니다'));u.context.location.hash='#active';await vm.runInContext('route(false)',u.context);assert.match(u.el('view').innerHTML,/진행 사건/);assert(u.el('incident-rows').innerHTML.includes('INC-20261008'));}});
 await check('cold settings list failure is explicit retriable and recovers workspace',async()=>{const u=ui({failList:true});await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('state.listLoaded',u.context),false);assert.equal(u.el('page-error').hidden,false);assert.match(u.el('view').innerHTML,/설정 · AI 연결/);u.context.location.hash='#field';await vm.runInContext('route(false)',u.context);assert.match(u.el('view').innerHTML,/사건 목록을 불러오지 못했습니다/);assert(!u.el('view').innerHTML.includes('진행 사건이 없습니다'));u.allowList();await vm.runInContext('route(false)',u.context);assert.equal(vm.runInContext('state.listLoaded',u.context),true);assert(u.el('view').innerHTML.includes('INC-20261008'));});
 await check('public settings UI no secret form local explicit link no automatic localhost request',async()=>{const u=ui();await new Promise(r=>setImmediate(r));const html=u.el('view').innerHTML;assert(html.includes('http://127.0.0.1:8769/#settings'));assert(!html.includes('<form id="provider-form"'));assert(!/type="password"|name="OPENAI_API_KEY"/.test(html));assert(u.calls.every(c=>!c.startsWith('http:')));assert(html.includes('공개 사이트에서는 분석 제공자나 서버 키를 변경할 수 없습니다'));});
 if(artifact){fs.mkdirSync(artifact,{recursive:true});fs.writeFileSync(path.join(artifact,'codex-checks.json'),JSON.stringify({mode:'mocked_model_sdk_runtime_DOM_and_actual_bounded_child_process',actual_model:false,checks},null,2)+'\n');}
 const summary={passed:checks.filter(c=>c.status==='passed').length,failed:checks.filter(c=>c.status==='failed').length};console.log(JSON.stringify(summary));if(summary.failed)process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
