/* Independent contract fixtures. Mock DOM checks are not a real browser run. */
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'service/route-engine.js'), 'utf8');
const routing = require('../service/route-engine.js');
const checks = [];
function check(name, fn) {try {fn();checks.push({name,status:'passed'});}catch(error){checks.push({name,status:'failed',error:error.message.split('\n')[0],code:error.code||null});}}
const opts = {destination_id:'target', vehicle_width_m:2.5, vehicle_height_m:3.2, clearance_m:.25, mode:'training', closed_edge_ids:[]};
const positions = {o:[126.94,37.47], a:[126.941,37.47], b:[126.942,37.47], c:[126.941,37.471], d:[126.943,37.47]};
function edge(id, from, to, length=100, tags={}, highway='residential', way=id) {
  return {id,from,to,length_m:length,tags,highway,way_id:way,name:id,geometry:[positions[from],positions[to]]};
}
function network(edges, destination='d', restrictions=[]) {
  return {schema_version:1, meta:{bbox:[126.94,37.47,126.943,37.471],unsupported_restriction_count:0}, nodes:Object.fromEntries(Object.entries(positions).map(([id,[lon,lat]])=>[id,{lon,lat}])),edges,restrictions,roads:edges,waterways:[],origin:{node_id:'o',name:'합성 출발',lon:126.94,lat:37.47,snap_distance_m:0},destinations:[{id:'target',node_id:destination,name:'합성 목적지',lon:positions[destination][0],lat:positions[destination][1],report:'SYN-QA 합성 원문',synthetic:true}],closures:[]};
}
function plan(n, change={}) {return routing.plan(n,{...opts,...change});}
function assertRoute(n, route, target, closed=[]) {
  assert.ok(route); assert.equal(route.node_ids[0],String(n.origin.node_id)); assert.equal(route.node_ids.at(-1),String(target));
  const edges = new Map(n.edges.map(e=>[e.id,e]));
  let last=String(n.origin.node_id), distance=0;const geometry=[];
  for(const id of route.edge_ids) {
    const e=edges.get(id);assert.ok(e);assert.equal(String(e.from),last);assert.ok(!closed.includes(id));last=String(e.to);distance+=e.length_m;
    const from=n.nodes[e.from],to=n.nodes[e.to];assert.deepEqual(e.geometry[0],[from.lon,from.lat]);assert.deepEqual(e.geometry.at(-1),[to.lon,to.lat]);
    for(const point of e.geometry)if(!geometry.length||geometry.at(-1)[0]!==point[0]||geometry.at(-1)[1]!==point[1])geometry.push(point);
  }
  assert.deepEqual(route.geometry,geometry.length?geometry:[[n.origin.lon,n.origin.lat]]);
  assert.ok(Math.abs(route.distance_m-distance)<.011);assert.ok(Number.isFinite(route.estimated_minutes));
  assert.deepEqual(route.steps.flatMap(s=>s.edge_ids),route.edge_ids);
  assert.ok(Math.abs(route.steps.reduce((sum,s)=>sum+s.distance_m,0)-route.distance_m)<route.steps.length*.011+.011);
}
check('CommonJS and browser UMD use the identical engine',()=>{
  const context={};vm.runInNewContext(source,context);assert.equal(typeof context.RescueRouting.plan,'function');
  const n=network([edge('direct','o','d')]);assert.equal(JSON.stringify(context.RescueRouting.plan(n,opts)),JSON.stringify(plan(n)));
});
const choice = network([edge('narrow','o','d',100,{width:'2.9'}),edge('wide1','o','c',90,{},'tertiary'),edge('wide2','c','d',90,{},'tertiary')]);
check('Vehicle width makes the recommendation longer than shortest',()=>{const r=plan(choice);assert.deepEqual(r.shortest.edge_ids,['narrow']);assert.deepEqual(r.recommended.edge_ids,['wide1','wide2']);assert.equal(r.recommended.distance_m,180);assert.equal(r.shortest.distance_m,100);assertRoute(choice,r.recommended,'d');assert.match(r.shortest.warnings.join(' '),/여유 필터는 제외/);});
check('Clearance counts on both sides; exact boundary accepted',()=>{const n=network([edge('direct','o','d',100,{width:'3 m'})]);assert.ok(plan(n).recommended);assert.equal(plan(n,{clearance_m:.25001}).recommended,null);assert.ok(plan(n,{vehicle_width_m:2.8,clearance_m:.1}).recommended);});
check('OSM width caps the training class assumption',()=>{const n=network([edge('direct','o','d',100,{width:'20'},'service')]);assert.equal(plan(n).recommended,null);assert.ok(plan(n).shortest);});
check('maxwidth checks vehicle width without adding clearance',()=>{const n=network([edge('direct','o','d',100,{maxwidth:'2.5'},'tertiary')]);assert.ok(plan(n).recommended);const r=plan(n,{vehicle_width_m:2.51});assert.equal(r.recommended,null);assert.equal(r.shortest,null);assert.equal(r.rejected.shortest.maxwidth,1);});
check('maxheight applies to both recommendation and shortest',()=>{const n=network([edge('direct','o','d',100,{maxheight:'320 cm'})]);assert.ok(plan(n).recommended);const r=plan(n,{vehicle_height_m:3.21});assert.equal(r.shortest,null);assert.equal(r.rejected.recommended.maxheight,1);});
check('Physical maxwidth/maxheight and node-tag restrictions apply',()=>{for(const tags of [{'maxwidth:physical':'2.4'},{'maxheight:physical':'3.1'},{'node:42:maxwidth':'2.4'},{'node:42:access':'no'},{'node:42:barrier':'gate'}]){const r=plan(network([edge('direct','o','d',100,tags)]));assert.equal(r.recommended,null);assert.equal(r.shortest,null);}});
check('Meter, feet and foot-inch legal limits parse',()=>{for(const tags of [{maxheight:'11 ft'},{maxheight:'10\' 6"'},{maxwidth:'250 cm'},{maxwidth:'2.5 metres'}])assert.ok(plan(network([edge('direct','o','d',100,tags)])).recommended);});
check('Unparsed width and legal or conditional limits fail closed',()=>{for(const tags of [{width:'unknown'},{maxwidth:'none'},{maxheight:'3;4'},{'maxheight:conditional':'4 @ (wet)'},{'width:conditional':'4 @ (Mo-Fr)'},{'access:conditional':'yes @ (delivery)'},{'node:1:maxwidth':'bad'},{'rescue:verified_width':'bad'}]){const r=plan(network([edge('direct','o','d',100,tags)]));assert.equal(r.recommended,null);assert.equal(r.shortest,null);assert.equal(r.rejected.recommended.unparsed_restriction,1);}});
check('Nested physical/directional conditional restrictions fail closed',()=>{for(const tags of [{'maxheight:physical:conditional':'2 @ (wet)'},{'maxwidth:forward:conditional':'2 @ (wet)'},{'motor_vehicle:forward:conditional':'no @ (wet)'},{'oneway:conditional':'yes @ (wet)'},{'node:42:maxheight:physical:conditional':'2 @ (wet)'}]){const r=plan(network([edge('direct','o','d',100,tags)]));assert.equal(r.recommended,null,JSON.stringify(tags));assert.equal(r.shortest,null);assert.equal(r.rejected.recommended.unparsed_restriction,1);}});
check('Unsupported directional limits never become unconditional permission',()=>{for(const key of ['maxwidth:forward','maxheight:backward','width:forward','access:backward','motor_vehicle:forward','node:42:maxwidth:forward','node:42:width:backward']){const r=plan(network([edge('direct','o','d',100,{[key]:'yes'})]));assert.equal(r.recommended,null,key);assert.equal(r.shortest,null,key);assert.equal(r.rejected.shortest.unparsed_restriction,1,key);}});
check('Excluded highways and access/barrier restrictions cannot route',()=>{for(const highway of ['footway','steps','construction','path'])assert.equal(plan(network([edge('direct','o','d',100,{},highway)])).shortest,null);for(const tags of [{access:'private'},{vehicle:'no'},{motor_vehicle:'no'},{motorcar:'private'},{barrier:'bollard'}])assert.equal(plan(network([edge('direct','o','d',100,tags)])).shortest,null);});
check('Directed edges permit only the available direction',()=>{const n=network([edge('oneway','o','d',100,{oneway:'yes'})]);assert.ok(plan(n).recommended);n.origin={...n.nodes.d,node_id:'d'};n.destinations[0].node_id='o';assert.equal(plan(n).shortest,null);});
const turns=()=>network([edge('oa','o','a',10,{},'tertiary','incoming'),edge('ad','a','d',10,{},'tertiary','straight'),edge('ac','a','c',30,{},'tertiary','allowed'),edge('cd','c','d',30,{},'tertiary','finish')]);
check('via-node no-turn forces a legal detour',()=>{const n=turns();n.restrictions=[{from_way:'incoming',via_node:'a',to_way:'straight',restriction:'no_right_turn'}];const r=plan(n);assert.deepEqual(r.shortest.edge_ids,['oa','ac','cd']);assert.ok(r.rejected.shortest.turn_restriction);assertRoute(n,r.recommended,'d');});
check('via-node only-turn excludes other outgoing ways',()=>{const n=turns();n.restrictions=[{from_way:'incoming',via_node:'a',to_way:'allowed',restriction:'only_left_turn'}];assert.deepEqual(plan(n).shortest.edge_ids,['oa','ac','cd']);});
check('no_u_turn blocks reversal while permitting same-way continuation',()=>{const n=network([edge('oa','o','a',10,{},'tertiary','incoming'),edge('ab','a','b',10,{},'tertiary','branch'),edge('ba','b','a',10,{},'tertiary','branch'),edge('ad','a','d',10,{},'tertiary','finish')]);n.restrictions=[{from_way:'incoming',via_node:'a',to_way:'branch',restriction:'only_right_turn'}];assert.deepEqual(plan(n).shortest.edge_ids,['oa','ab','ba','ad']);n.restrictions.push({from_way:'branch',via_node:'b',to_way:'branch',restriction:'no_u_turn'});assert.equal(plan(n).shortest,null);const straight=network([edge('oa','o','a',10,{},'tertiary','same'),edge('ad','a','d',10,{},'tertiary','same')]);straight.restrictions=[{from_way:'same',via_node:'a',to_way:'same',restriction:'no_u_turn'}];assert.ok(plan(straight).shortest);});
check('Closures cause avoidance and complete disconnection',()=>{const r=plan(choice,{closed_edge_ids:['wide1']});assert.equal(r.recommended,null);assert.deepEqual(r.shortest.edge_ids,['narrow']);const r2=plan(choice,{closed_edge_ids:['narrow']});assert.deepEqual(r2.shortest.edge_ids,['wide1','wide2']);assertRoute(choice,r2.shortest,'d',['narrow']);const r3=plan(choice,{closed_edge_ids:['narrow','wide1']});assert.equal(r3.status,'no_route');assert.equal(r3.shortest,null);});
check('Strict excludes unknown and OSM-only width; accepts verified route',()=>{assert.equal(plan(choice,{mode:'strict'}).recommended,null);assert.ok(plan(choice,{mode:'strict'}).shortest);const n=network([edge('direct','o','d',100,{'rescue:verified_width':'3'})]);let r=plan(n,{mode:'strict'});assert.ok(r.recommended);assert.equal(r.recommended.unknown_width_count,0);assert.equal(r.recommended.assumed_width_count,0);n.edges[0].tags.width='2.9';assert.equal(plan(n,{mode:'strict'}).recommended,null);});
check('Invalid numeric ranges, NaN, ids and modes give Korean errors',()=>{const n=choice;const changes=[{vehicle_width_m:NaN},{vehicle_width_m:Infinity},{vehicle_width_m:'2.5'},{vehicle_width_m:1.49},{vehicle_width_m:3.51},{vehicle_height_m:4.51},{vehicle_height_m:1.49},{clearance_m:.09},{clearance_m:.81},{destination_id:'missing'},{mode:'free'},{closed_edge_ids:['missing']},{closed_edge_ids:[1]},{closed_edge_ids:'narrow'}];for(const change of changes)assert.throws(()=>plan(n,change),/[가-힣]/);assert.throws(()=>routing.plan(n,null),/[가-힣]/);});
check('Route planning preserves network and options',()=>{const n=structuredClone(choice),input={...opts,closed_edge_ids:['narrow','narrow']};const before=JSON.stringify({n,input});routing.plan(n,input);assert.equal(JSON.stringify({n,input}),before);});
const snapshot=JSON.parse(fs.readFileSync(path.join(root,'data/routing/network.json')));
for(const dest of snapshot.destinations)for(const [vehicle_width_m,vehicle_height_m,clearance_m] of [[1.8,2.2,.2],[2.5,3.2,.25],[2.8,3.8,.3]])for(const closure of [false,true]) {
  check(`OSM ${dest.id} width=${vehicle_width_m} closure=${closure} training/strict`,()=>{
    const closed_edge_ids=closure?snapshot.closures.flatMap(c=>c.edge_ids):[];
    const input={destination_id:dest.id,vehicle_width_m,vehicle_height_m,clearance_m,closed_edge_ids,mode:'training'};
    const r=routing.plan(snapshot,input);assertRoute(snapshot,r.shortest,dest.node_id,closed_edge_ids);assert.equal(r.assumptions.real_time_traffic,false);
    if(vehicle_width_m===2.8) {assert.equal(r.status,'no_route');assert.equal(r.recommended,null);assert.ok(r.rejected.recommended.effective_width>0);}
    else {assert.equal(r.status,'ok');assertRoute(snapshot,r.recommended,dest.node_id,closed_edge_ids);assert.ok(r.recommended.distance_m>=r.shortest.distance_m-.02);assert.ok(r.recommended.unknown_width_count>0);}
    const strict=routing.plan(snapshot,{...input,mode:'strict'});assert.equal(strict.status,'no_route');assert.equal(strict.recommended,null);assert.ok(strict.shortest);assert.ok(strict.rejected.recommended.unknown_width>0);
  });
}

// Independent, hand-calculated exposure fixtures; GIS calculations run separately.
const publicFlood=JSON.parse(fs.readFileSync(path.join(root,'data/routing/flood-history.json')));
function floodFixture(exposure={}) {
  return {schema_version:1,meta:{years_available:[2022,2023,2025],years_in_bbox:[2022,2023],nearby_buffer_m:10,risk_penalty_per_year_m:8,provider:'합성 QA',license:'합성',source_url:'https://example.invalid',license_url:'https://example.invalid',dataset_updated_at:'2026-04-27',downloaded_at:'2026-10-09'},traces:{type:'FeatureCollection',features:[]},edge_exposure:exposure};
}
const floodChoice=network([edge('direct','o','d',100,{},'primary'),edge('via1','o','a',80,{},'primary'),edge('via2','a','d',80,{},'primary')]);
const repeatFlood=floodFixture({direct:{by_year:[{year:2022,trace_m:2,nearby_m:5},{year:2023,trace_m:2,nearby_m:5}],trace_union_m:2,nearby_union_m:5}});
function floodPlan(n=floodChoice,f=repeatFlood,change={}) {return routing.plan(n,{...opts,...change},f);}
function exposureOracle(route,f,year='all') {
  const expected={trace_m:0,nearby_m:0,year_weighted_m:0};const years=new Set();
  for(const id of route.edge_ids){const row=f.edge_exposure[id];if(!row)continue;const selected=row.by_year.filter(r=>year==='all'||r.year===year);expected.trace_m+=year==='all'?row.trace_union_m:selected.reduce((a,r)=>a+r.trace_m,0);expected.nearby_m+=year==='all'?row.nearby_union_m:selected.reduce((a,r)=>a+r.nearby_m,0);for(const r of selected){expected.year_weighted_m+=r.nearby_m;if(r.nearby_m||r.trace_m)years.add(r.year);}}
  for(const key of Object.keys(expected))assert.ok(Math.abs(route.flood_exposure[key]-expected[key])<1e-7,key);
  assert.deepEqual(route.flood_exposure.years,[...years].sort((a,b)=>a-b));assert.equal(route.flood_exposure.selected_year,year);assert.equal(route.flood_exposure.buffer_m,10);
  for(const step of route.steps)exposureOracle({...step,steps:[]},f,year);
  if(route.steps.length)for(const key of Object.keys(expected))assert.ok(Math.abs(route.steps.reduce((a,s)=>a+s.flood_exposure[key],0)-expected[key])<1e-7,key);
}
check('Flood cumulative repeated years change cost, annual union is counted once',()=>{const r=floodPlan();assert.equal(r.flood_status,'ok');assert.deepEqual(r.recommended.edge_ids,['direct']);assert.deepEqual(r.shortest.edge_ids,['direct']);assert.deepEqual(r.flood_aware.edge_ids,['via1','via2']);assert.equal(r.recommended.flood_exposure.nearby_m,5);assert.equal(r.recommended.flood_exposure.year_weighted_m,10);for(const year of [2022,2023])assert.deepEqual(floodPlan(floodChoice,repeatFlood,{flood_year:year}).flood_aware.edge_ids,['direct']);for(const route of [r.recommended,r.shortest,r.flood_aware])exposureOracle(route,repeatFlood);});
check('Flood no-record supplied year gives zero exposure and the original route',()=>{const r=floodPlan(floodChoice,repeatFlood,{flood_year:2025});assert.deepEqual(r.flood_aware.edge_ids,r.recommended.edge_ids);assert.equal(r.flood_aware.flood_exposure.year_weighted_m,0);assert.deepEqual(r.flood_aware.flood_exposure.years,[]);});
check('Flood penalty coefficient is exactly eight, not hard exclusion',()=>{const n=structuredClone(floodChoice);const f=floodFixture({direct:{by_year:[{year:2022,trace_m:7,nearby_m:7}],trace_union_m:7,nearby_union_m:7}});assert.deepEqual(floodPlan(n,f).flood_aware.edge_ids,['direct']);f.edge_exposure.direct.by_year[0].nearby_m=9;f.edge_exposure.direct.nearby_union_m=9;assert.deepEqual(floodPlan(n,f).flood_aware.edge_ids,['via1','via2']);n.edges=n.edges.filter(e=>e.id==='direct');assert.deepEqual(floodPlan(n,f).flood_aware.edge_ids,['direct']);});
check('Flood legal conditions, width, height and strict remain hard filters',()=>{for(const tags of [{width:'2.9'},{maxheight:'3.1'},{maxwidth:'2.4'},{access:'no'},{'width:conditional':'5 @ (wet)'}]){const n=network([edge('blocked','o','d',100,tags)]);assert.equal(floodPlan(n,floodFixture()).flood_status,'no_route');}assert.equal(floodPlan(floodChoice,repeatFlood,{mode:'strict'}).flood_aware,null);const n=structuredClone(floodChoice);n.edges.forEach(e=>e.tags['rescue:verified_width']='5');assert.ok(floodPlan(n,repeatFlood,{mode:'strict'}).flood_aware);});
check('Flood closures and via-node turn restrictions remain hard filters',()=>{const r=floodPlan(floodChoice,repeatFlood,{closed_edge_ids:['via1']});assert.deepEqual(r.flood_aware.edge_ids,['direct']);assert.equal(floodPlan(floodChoice,repeatFlood,{closed_edge_ids:['direct','via1']}).flood_status,'no_route');const n=turns();n.restrictions=[{from_way:'incoming',via_node:'a',to_way:'straight',restriction:'no_right_turn'}];assert.deepEqual(floodPlan(n,floodFixture()).flood_aware.edge_ids,['oa','ac','cd']);});
check('Flood selection errors are Korean and missing payload preserves old routes',()=>{for(const year of [2015,2021,2026])assert.throws(()=>floodPlan(floodChoice,repeatFlood,{flood_year:year}),/[가-힣]/);for(const year of ['2022',null,NaN,Infinity,2022.5,{},true])assert.throws(()=>floodPlan(floodChoice,repeatFlood,{flood_year:year}),/[가-힣]/);const r=floodPlan(floodChoice,null);assert.equal(r.flood_status,'unavailable');assert.match(r.flood_message,/[가-힣]/);assert.deepEqual(r.recommended.edge_ids,['direct']);assert.equal(r.flood_aware,null);});
const badFloodCases=[
 ['negative length',f=>f.edge_exposure.direct.by_year[0].nearby_m=-1],['NaN length',f=>f.edge_exposure.direct.trace_union_m=NaN],['infinite length',f=>f.edge_exposure.direct.nearby_union_m=Infinity],['string length',f=>f.edge_exposure.direct.trace_union_m='2'],['edge-length overflow',f=>f.edge_exposure.direct.nearby_union_m=100.011],['duplicate row year',f=>f.edge_exposure.direct.by_year.push({...f.edge_exposure.direct.by_year[0]})],['unknown row year',f=>f.edge_exposure.direct.by_year[0].year=1900],['trace exceeds nearby',f=>f.edge_exposure.direct.by_year[0].trace_m=6],['row exceeds union',f=>f.edge_exposure.direct.nearby_union_m=4],['union exceeds sum',f=>f.edge_exposure.direct.nearby_union_m=11],['unknown edge',f=>f.edge_exposure.unknown=f.edge_exposure.direct],['duplicate available year',f=>f.meta.years_available.push(2022)],['wrong buffer',f=>f.meta.nearby_buffer_m=20],['wrong weight',f=>f.meta.risk_penalty_per_year_m=9],['array exposure table',f=>f.edge_exposure=[]],['malformed features',f=>f.traces.features=null],['wrong version',f=>f.schema_version=2]
];
for(const [name,mutate] of badFloodCases)check('Flood corrupt payload: '+name,()=>{const f=structuredClone(repeatFlood);mutate(f);const r=floodPlan(floodChoice,f);assert.equal(r.flood_status,'unavailable');assert.equal(r.flood_aware,null);assert.ok(r.flood_message);assert.deepEqual(r.recommended.edge_ids,['direct']);assert.deepEqual(r.shortest.edge_ids,['direct']);assert.equal(r.recommended.flood_exposure,undefined);});
check('Flood planning never mutates caller-owned inputs',()=>{const n=structuredClone(floodChoice),f=structuredClone(repeatFlood),input={...opts};const before=JSON.stringify({n,f,input});routing.plan(n,input,f);assert.equal(JSON.stringify({n,f,input}),before);});
for(const [name,mutate] of [
 ['unsupported geometry',f=>f.traces.features[0].geometry.type='LineString'],['unclosed ring',f=>f.traces.features[0].geometry.coordinates[0].pop()],['nonfinite coordinate',f=>f.traces.features[0].geometry.coordinates[0][0][0]=NaN],['coordinate out of range',f=>f.traces.features[0].geometry.coordinates[0][0][1]=91],['empty polygon',f=>f.traces.features[0].geometry.coordinates=[]],['duplicate feature year',f=>f.traces.features.push(structuredClone(f.traces.features[0]))],['unknown feature year',f=>f.traces.features[0].properties.year=2026],['missing nearby geometry',f=>delete f.traces.features[0].nearby_geometry]
])check('Flood malformed geometry: '+name,()=>{const f=mockFlood();f.edge_exposure={};mutate(f);const r=floodPlan(floodChoice,f);assert.equal(r.flood_status,'unavailable');assert.equal(r.flood_aware,null);assert.ok(r.recommended);assert.ok(r.shortest);});
for(const dest of snapshot.destinations)for(const year of ['all',...publicFlood.meta.years_available])check(`Public flood ${dest.id} ${year}: all routes and totals`,()=>{const input={...opts,destination_id:dest.id,flood_year:year};const baseline=routing.plan(snapshot,input),r=routing.plan(snapshot,input,publicFlood);assert.equal(r.flood_status,'ok');assert.deepEqual(r.recommended.edge_ids,baseline.recommended.edge_ids);assert.deepEqual(r.shortest.edge_ids,baseline.shortest.edge_ids);for(const route of [r.recommended,r.shortest,r.flood_aware]){assertRoute(snapshot,route,dest.node_id);exposureOracle(route,publicFlood,year);}const strict=routing.plan(snapshot,{...input,mode:'strict'},publicFlood);assert.equal(strict.flood_status,'no_route');assert.equal(strict.flood_aware,null);assert.ok(strict.shortest);});
for(const dest of snapshot.destinations)for(const [vehicle_width_m,vehicle_height_m,clearance_m] of [[1.8,2.2,.2],[2.5,3.2,.25],[2.8,3.8,.3]])for(const closure of [false,true])check(`Public flood ${dest.id} width=${vehicle_width_m} closure=${closure}`,()=>{const closed_edge_ids=closure?snapshot.closures.flatMap(c=>c.edge_ids):[];const input={...opts,destination_id:dest.id,vehicle_width_m,vehicle_height_m,clearance_m,closed_edge_ids};const baseline=routing.plan(snapshot,input),r=routing.plan(snapshot,input,publicFlood);assert.deepEqual(r.recommended?.edge_ids,baseline.recommended?.edge_ids);assert.deepEqual(r.shortest?.edge_ids,baseline.shortest?.edge_ids);if(vehicle_width_m===2.8){assert.equal(r.flood_status,'no_route');assert.equal(r.flood_aware,null);}else{assert.equal(r.flood_status,'ok');assertRoute(snapshot,r.flood_aware,dest.node_id,closed_edge_ids);exposureOracle(r.flood_aware,publicFlood);}});
function mockFlood() {
  const f=floodFixture({wide1:{by_year:[{year:2022,trace_m:2,nearby_m:5}],trace_union_m:2,nearby_union_m:5}});
  const outer=[[126.94,37.47],[126.942,37.47],[126.942,37.472],[126.94,37.472],[126.94,37.47]],hole=[[126.9405,37.4705],[126.9415,37.4705],[126.9415,37.4715],[126.9405,37.4715],[126.9405,37.4705]];
  f.traces.features=[{type:'Feature',properties:{year:2022,source_record_count:2},geometry:{type:'Polygon',coordinates:[outer,hole]},nearby_geometry:{type:'MultiPolygon',coordinates:[[outer,hole],[outer]]}}];return f;
}
class Element {
  constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.children=[];this.parent=null;this.dataset={};this.attrs={};this.handlers={};this.hidden=false;this.disabled=false;this.checked=false;this._value='';this._text='';this.labels=[{textContent:id}];this.classList={toggle(){},add(){},remove(){}};}
  set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>typeof c==='string'?c:c.textContent).join('');}
  set value(v){this._value=String(v);}get value(){return this._value||(this.tagName==='SELECT'&&this.children[0]?.value)||'';}
  append(...items){for(const child of items){this.children.push(child);if(typeof child==='object')child.parent=this;}}
  replaceChildren(...items){this.children=[];this._text='';this.append(...items);}
  addEventListener(type,fn){(this.handlers[type]??=[]).push(fn);}fire(type,event={}){for(const fn of this.handlers[type]||[])fn({preventDefault(){},...event});}
  setAttribute(name,v){this.attrs[name]=v;}getAttribute(name){return this.attrs[name];}
  checkValidity(){return this.value!==''&&Number.isFinite(Number(this.value));}
  getBoundingClientRect(){return {width:900,height:500,left:0,top:0};}setPointerCapture(){}
  closest(tag){return this.tagName===tag.toUpperCase()?this:this.parent?.closest(tag);}
  querySelectorAll(selector){const descendants=[];function walk(el){for(const c of el.children)if(typeof c==='object'){descendants.push(c);walk(c);}}walk(this);return descendants.filter(c=>selector==='input:checked'?c.tagName==='INPUT'&&c.checked:selector==='button[data-route]'?c.tagName==='BUTTON'&&c.dataset.route:false);}
}
async function mockApp({fail=false,missingEngine=false,failFlood=false,floodOverride=undefined}={}) {
  const html=fs.readFileSync(path.join(root,'web/routes/index.html'),'utf8');const elements=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],new Element(['destination','flood-year','vehicle-preset'].includes(m[1])?'select':'div',m[1])]));
  for(const [id,value] of [['vehicle-width','2.5'],['vehicle-height','3.2'],['clearance','.25'],['vehicle-preset','rescue'],['flood-year','all']])elements.get(id).value=value;
  elements.get('flood-visible').checked=true;
  const paint=[], calls=[];let rings=[];
  const drawing=new Proxy({measureText(text){return {width:text.length*6};},beginPath(){rings=[];},moveTo(x,y){rings.push([[x,y]]);},lineTo(x,y){rings.at(-1)?.push([x,y]);},fill(rule){if(rule==='evenodd')paint.push({rule,rings:structuredClone(rings)});}},{get(o,p){return p in o?o[p]:()=>{};},set(o,p,v){o[p]=v;return true;}});elements.get('route-map').getContext=()=>drawing;
  const frames=[],requests=[];const n=structuredClone(choice);n.closures=[{id:'test-flood',label:'합성 통제',edge_ids:['wide1','narrow'],synthetic:true}];
  const sandbox={document:{getElementById:id=>elements.get(id),createElement:tag=>new Element(tag)},requestAnimationFrame:fn=>frames.push(fn),fetch:async url=>{requests.push(url);if(fail)throw Error('QA 로딩 실패');if(url==='flood-history.json'&&failFlood)throw Error('QA 침수 자료 실패');return {ok:true,json:async()=>url==='network.json'?n:(floodOverride===undefined?mockFlood():floodOverride)};},ResizeObserver:class{observe(){}},console};sandbox.window={devicePixelRatio:1,ResizeObserver:sandbox.ResizeObserver,addEventListener(){},...(missingEngine?{}:{RescueRouting:{plan(...args){calls.push(args[1]);return routing.plan(...args);}}})};
  vm.runInNewContext(fs.readFileSync(path.join(root,'web/routes/app.js'),'utf8'),sandbox);
  await new Promise(resolve=>setImmediate(resolve));
  const flush=()=>{while(frames.length)frames.shift()();};return {elements,frames,requests,flush,n,paint,calls};
}
async function main() {
  const ui=await mockApp();ui.flush();
  check('Mock DOM renders initial route and fetches only local snapshot',()=>{assert.ok(Number(ui.elements.get('route-map').dataset.routeEdges)>0);assert.equal(ui.elements.get('steps-panel').hidden,false);assert.deepEqual(ui.requests,['network.json','flood-history.json']);});
  check('Mock DOM strict immediately clears old route and remains empty after RAF',()=>{ui.elements.get('strict-mode').checked=true;ui.elements.get('strict-mode').fire('change');assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');assert.equal(ui.elements.get('steps-panel').hidden,true);ui.flush();assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');assert.match(ui.elements.get('route-status').textContent,/추천 경로가 없습니다/);assert.equal(ui.elements.get('route-comparison').querySelectorAll('button[data-route]').length,1);});
  check('Mock DOM shortest requires explicit selection after strict no-route',()=>{const button=ui.elements.get('route-comparison').querySelectorAll('button[data-route]')[0];assert.equal(button.dataset.route,'shortest');button.fire('click');assert.ok(Number(ui.elements.get('route-map').dataset.routeEdges)>0);assert.match(ui.elements.get('map-description').textContent,/물리 폭/);});
  check('Mock DOM invalid input removes selected shortest and shows Korean error',()=>{ui.elements.get('vehicle-width').value='';ui.elements.get('vehicle-width').fire('input');assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');ui.flush();assert.equal(ui.elements.get('route-error').hidden,false);assert.match(ui.elements.get('route-error').textContent,/[가-힣]/);assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');});
  check('Mock DOM rapid changes do not commit stale calculation',()=>{ui.elements.get('vehicle-width').value='2.5';ui.elements.get('strict-mode').checked=false;ui.elements.get('strict-mode').fire('change');ui.elements.get('strict-mode').checked=true;ui.elements.get('strict-mode').fire('change');ui.flush();assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');assert.equal(ui.elements.get('calculate').disabled,false);});
  check('Mock DOM training recovery and closure remove unreachable route',()=>{ui.elements.get('strict-mode').checked=false;ui.elements.get('strict-mode').fire('change');ui.flush();assert.ok(Number(ui.elements.get('route-map').dataset.routeEdges)>0);const label=ui.elements.get('closures').children.find(c=>c.tagName==='LABEL');label.children[0].checked=true;ui.elements.get('closures').fire('change');assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');ui.flush();assert.equal(ui.elements.get('route-map').dataset.routeEdges,'0');});
  const floodUI=await mockApp();floodUI.flush();const el=id=>floodUI.elements.get(id),buttons=()=>el('route-comparison').querySelectorAll('button[data-route]');
  check('Mock flood three cards require explicit third-route selection',()=>{assert.equal(buttons().length,3);assert.equal(el('route-map').dataset.selectedRoute,'recommended');assert.equal(el('route-map').dataset.floodRouteEdges,'0');buttons().find(b=>b.dataset.route==='flood_aware').fire('click');assert.equal(el('route-map').dataset.selectedRoute,'flood_aware');assert.ok(Number(el('route-map').dataset.floodRouteEdges)>0);assert.match(el('route-map').getAttribute('aria-label'),/침수 이력 고려/);assert.match(el('steps-title').textContent,/침수 이력 고려/);assert.match(el('route-steps').textContent,/등록 흔적 교차/);assert.equal(buttons().find(b=>b.dataset.route==='flood_aware').getAttribute('aria-pressed'),'true');});
  check('Mock flood Polygon/MultiPolygon holes use separate rings and evenodd',()=>{assert.ok(floodUI.paint.some(p=>p.rule==='evenodd'&&p.rings.length===2));assert.ok(floodUI.paint.some(p=>p.rings.length===1));for(const p of floodUI.paint)for(const ring of p.rings){assert.equal(ring.length,5);assert.deepEqual(ring[0],ring.at(-1));}});
  check('Mock flood visibility hides only layers without recalculation',()=>{const before=el('route-comparison').textContent,calls=floodUI.calls.length,paint=floodUI.paint.length;el('flood-visible').checked=false;el('flood-visible').fire('change');assert.equal(floodUI.calls.length,calls);assert.equal(floodUI.paint.length,paint);assert.equal(el('route-comparison').textContent,before);assert.equal(el('route-map').dataset.selectedRoute,'flood_aware');assert.equal(el('route-map').dataset.floodVisible,'false');assert.equal(el('trace-key').hidden,true);assert.match(el('flood-layer-status').textContent,/경로 계산 유지/);});
  check('Mock flood annual selection clears stale route, reuses explicit selection, no-record stays valid',()=>{el('flood-year').value='2025';el('flood-year').fire('change');assert.equal(el('route-map').dataset.floodRouteEdges,'0');floodUI.flush();assert.equal(el('route-map').dataset.selectedRoute,'flood_aware');assert.equal(floodUI.calls.at(-1).flood_year,2025);assert.match(el('flood-layer-status').textContent,/등록 기록 없음/);assert.equal(buttons().length,3);assert.equal(el('route-map').dataset.floodYear,'2025');});
  check('Mock flood nonexistent annual choice displays error and removes selection',()=>{el('flood-year').value='2026';el('flood-year').fire('change');floodUI.flush();assert.equal(el('route-map').dataset.selectedRoute,'none');assert.equal(el('route-map').dataset.floodRouteEdges,'0');assert.equal(el('route-error').hidden,false);assert.match(el('route-error').textContent,/연도/);});
  check('Mock flood strict and width error remove previous third-route ARIA and steps',()=>{el('flood-year').value='all';el('flood-year').fire('change');floodUI.flush();buttons().find(b=>b.dataset.route==='flood_aware').fire('click');el('strict-mode').checked=true;el('strict-mode').fire('change');assert.equal(el('route-map').dataset.floodRouteEdges,'0');floodUI.flush();assert.equal(buttons().length,1);assert.equal(el('route-map').dataset.selectedRoute,'none');assert.equal(el('steps-panel').hidden,true);el('strict-mode').checked=false;el('vehicle-width').value='';el('vehicle-width').fire('input');floodUI.flush();assert.equal(el('route-error').hidden,false);assert.match(el('route-map').getAttribute('aria-label'),/선택 경로 없음/);});
  const unavailableUI=await mockApp({failFlood:true});unavailableUI.flush();check('Mock flood fetch failure preserves two routes and explains unavailability',()=>{assert.equal(unavailableUI.elements.get('route-comparison').querySelectorAll('button[data-route]').length,2);assert.match(unavailableUI.elements.get('route-comparison').textContent,/QA 침수 자료 실패/);assert.equal(unavailableUI.elements.get('flood-year').disabled,true);assert.ok(Number(unavailableUI.elements.get('route-map').dataset.routeEdges)>0);});
  const malformedUI=await mockApp({floodOverride:{schema_version:2}});malformedUI.flush();check('Mock malformed flood payload preserves original route and no polygons',()=>{assert.equal(malformedUI.elements.get('route-comparison').querySelectorAll('button[data-route]').length,2);assert.equal(malformedUI.paint.length,0);assert.equal(malformedUI.elements.get('route-map').dataset.floodRouteEdges,'0');assert.match(malformedUI.elements.get('route-comparison').textContent,/형식/);});
  const loadFailed=await mockApp({fail:true});check('Mock DOM loading failure shows error with zero route',()=>{assert.equal(loadFailed.elements.get('route-error').hidden,false);assert.equal(loadFailed.elements.get('route-map').dataset.routeEdges,'0');assert.match(loadFailed.elements.get('route-status').textContent,/실패/);});
  const missing=await mockApp({missingEngine:true});check('Mock DOM missing engine produces actionable loading error',()=>{assert.equal(missing.elements.get('route-error').hidden,false);assert.match(missing.elements.get('route-error').textContent,/엔진/);assert.equal(missing.requests.length,0);});
  const failedCount=checks.filter(c=>c.status==='failed').length;
  console.log(JSON.stringify({status:failedCount?'failed':'passed',count:checks.length,passed:checks.length-failedCount,failed:failedCount,checks,scope:'deterministic Node engine and mocked DOM; no actual browser, LLM, OCR, ASR or field driving'},null,2));
  if(failedCount)process.exitCode=1;
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
