'use strict';
// Independent actual JS stores/readers and mocked DOM. No live services/model.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {pathToFileURL}=require('node:url'),Pages=require('../web/pages-store.js');
const root=path.resolve(__dirname,'..'),checks=[],seed=JSON.parse(fs.readFileSync(path.join(root,'data/seed.json'))),featured='INC-20261009-100',duplicate='INC-20261009-101';
const media=['flood-entrance.png','flood-stairwell.png','call-isolated.wav','call-proxy.wav','parking-pillar-dark.png','parking-stair-flood.png','parking-call-noisy.wav','parking-call-enhanced.wav'];
const clone=x=>structuredClone(x);let shared;
async function check(name,fn){try{await fn();checks.push({name,status:'passed'});console.log('PASS',name);}catch(e){checks.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e.stack);}}
function store(seedValue=seed){const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};return {store:Pages.createStore({seed:seedValue,storage}),storage,memory};}
async function main(){
await check('JS featured first strictbool raw priority and reload preserved',async()=>{shared=store();const list=await shared.store.request('/api/incidents');assert.equal(list.incidents.length,12);assert.equal(list.incidents[0].id,featured);const i=await shared.store.request('/api/incidents/'+featured);assert.equal(i.demo_featured,true);assert.equal(i.people_count,3);assert.equal(i.status,'rescuing');assert.equal(i.outcome,null);const after=await shared.store.request('/api/incidents/'+featured,{method:'PATCH',body:{expected_revision:i.revision,reason:'합성 위치 재확인',location:i.location+' QA'}});assert.equal(after.demo_featured,true);assert.equal(after.priority,i.priority);assert.deepEqual(after.reports,i.reports);const again=Pages.createStore({storage:shared.storage,seed});assert.equal((await again.request('/api/incidents')).incidents[0].id,featured);for(const value of ['true',1,null]){const broken=clone(seed);broken.incidents.find(i=>i.id===featured).demo_featured=value;await assert.rejects(()=>store(broken).store.request('/api/incidents'),e=>e.status===400);}});
await check('JS duplicate IDs and two of three partial/residual cannot close',async()=>{const s=store().store,i=await s.request('/api/incidents/'+featured),d=await s.request('/api/incidents/'+duplicate);assert.equal(d.people_count,null);assert.equal(d.assigned_team_id,null);assert.deepEqual(d.reports.map(r=>r.id),['REP-101-01','REP-101-02']);for(const basis of ['REP-100-06','REP-100-08','REP-101-01'])for(const n of [2,3])await assert.rejects(()=>s.request('/api/incidents/'+featured+'/outcome',{method:'POST',body:{expected_revision:i.revision,outcome:'rescued',confirmed_count:n,basis_report_id:basis,note:'합성 인원 대조'}}),e=>e.status===400);assert.deepEqual(await s.request('/api/incidents/'+featured),i);const next=await s.request('/api/incidents/'+featured+'/reports',{method:'POST',body:{expected_revision:i.revision,kind:'field',channel:'field',text:'두 명만 구조, 한 명 남아 있음',people_count:3}});await assert.rejects(()=>s.request('/api/incidents/'+featured+'/outcome',{method:'POST',body:{expected_revision:next.revision,outcome:'rescued',confirmed_count:3,basis_report_id:next.reports.at(-1).id,note:'합성 인원 대조'}}),e=>e.status===400);});
await check('JS eight real media registry and operator upload header boundaries',async()=>{const s=store().store;let i=await s.request('/api/incidents/'+featured);const attachments=media.map((name,n)=>({id:'QA-media-'+n,url:'/media/'+name,filename:name,media_type:name.endsWith('.wav')?'audio':'image',caption:'합성 원문',source:name.endsWith('.wav')?'tts_synthetic':'ai_generated'}));i=await s.request('/api/incidents/'+featured+'/reports',{method:'POST',body:{expected_revision:i.revision,kind:'additional',channel:'mms',text:'합성 여덟 매체 대조',attachments}});assert.deepEqual(i.reports.at(-1).attachments,attachments);await assert.rejects(()=>s.request('/api/uploads',{method:'POST',body:{filename:'bad.png',content_type:'image/png',data_base64:Buffer.from('not PNG').toString('base64')}}),e=>e.status===400);await assert.rejects(()=>s.request('/api/uploads',{method:'POST',body:{filename:'huge.png',content_type:'image/png',data_base64:Buffer.alloc(8*1024*1024+1).toString('base64')}}),e=>e.status===413);});
await check('actual allowed parking PNG uploads preserve bytes and safe registry',async()=>{const local=store(),s=local.store;for(const name of ['parking-pillar-dark.png','parking-stair-flood.png']){const bytes=fs.readFileSync(path.join(root,'data/media',name)),out=await s.request('/api/uploads',{method:'POST',body:{filename:name,content_type:'image/png',data_base64:bytes.toString('base64')}});assert.equal(out.media_type,'image');assert(out.url.startsWith('/media/uploads/'));const raw=JSON.parse([...local.memory.values()][0]),encoded=raw.uploads[out.id].data_url.split(',')[1];assert.deepEqual(Buffer.from(encoded,'base64'),bytes);}});
await check('Node background seed reader loads all eight actual bytes no arbitrary URLs',async()=>{const core=await import(pathToFileURL(path.join(root,'netlify/functions/ai-core.mjs'))),background=await import(pathToFileURL(path.join(root,'netlify/functions/ai-analysis-background.mjs')));const report={channel:'mms',actor:'가상 QA',kind:'initial',text:'합성 실제바이트 검증',attachments:media.map((n,k)=>({id:'M-'+k,url:'/media/'+n,media_type:n.endsWith('.wav')?'audio':'image'}))};const job={id:'AI-QA-showcase',report,incident_id:null,expected_revision:null,context_incidents:[],execution:{provider:'openai'}};job.execution.input_sha256=core.hash({report,intake119:null,incident_id:null,expected_revision:null});let result;const db={rpc:async(name,b)=>name==='rescue_claim_job'?clone(job):(result=b.p_payload),workspace:async()=>({document:{uploads:{}}})};let read=0;await background.processJob(job.id,job.execution.input_sha256,{AI_PROVIDER:'openai'},{database:db,analyze:async(j,incidents,reader)=>{for(let n=0;n<j.report.attachments.length;n++){const value=await reader(j.report.attachments[n]);assert.deepEqual(value.bytes,fs.readFileSync(path.join(root,'data/media',media[n])));assert.equal(value.mime,media[n].endsWith('.wav')?'audio/wav':'image/png');read++;}await assert.rejects(()=>reader({id:'outside',url:'https://evil.invalid/audio.wav',media_type:'audio'}),e=>e.status===400);return {analysis:{},execution:{mode:'mocked'}};}});assert.equal(result.status,'ready');assert.equal(read,8);});
await check('actual app mocked dashboard field/detail featured labels raw and media',async()=>{const s=store().store,elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',hidden:false,disabled:false,classList:{toggle(){}},addEventListener(){},querySelectorAll:()=>[],querySelector:()=>el('child'),setAttribute(){},removeAttribute(){},replaceChildren(){},append(){},focus(){},showModal(){},close(){}});return elements.get(id);};const context={console,Intl,Date,URL,AbortController,setTimeout:()=>1,clearTimeout(){},document:{getElementById:el,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},documentElement:{dataset:{serviceMode:'cloud'}}},window:{addEventListener(){},scrollTo(){},RescueCloud:{mode:'cloud',config:{ai:{provider:'disabled',enabled:false}},boot:async()=>{},remembered:()=>null,request:(...a)=>s.request(...a)}},location:{hash:'#dashboard'},history:{pushState(){}},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'web/app.js'),'utf8'),context);await new Promise(r=>setImmediate(r));assert(el('incident-rows').innerHTML.indexOf(featured)<el('incident-rows').innerHTML.indexOf('INC-20261008-'));assert(el('incident-rows').innerHTML.includes('발표 대표 사례'));context.location.hash='#field';await vm.runInContext('route(false)',context);assert(el('view').innerHTML.includes(featured));assert(el('view').innerHTML.includes('data-ai-incident="'+featured+'"'));context.location.hash='#incident/'+featured;await vm.runInContext('route(false)',context);assert(el('view').innerHTML.includes('발표용 상단 고정'));assert(el('view').innerHTML.includes('자동 연결되지 않습니다'));const detail=el('detail-content').innerHTML;for(const name of media.slice(4))assert(detail.includes('/media/'+name),name);for(const r of seed.incidents.find(i=>i.id===featured).reports)assert(detail.includes(r.text),r.id);assert(!detail.includes('실제 전사 (TTS'));});
const summary={passed:checks.filter(c=>c.status==='passed').length,failed:checks.filter(c=>c.status==='failed').length,actual_model:false,actual_browser:false};console.log(JSON.stringify(summary));if(process.env.AI_QA_RUN_ID){const out=path.join(root,'_workspace/verification',process.env.AI_QA_RUN_ID,'qa/showcase-node-checks.json');fs.writeFileSync(out,JSON.stringify({checks,summary},null,2)+'\n');}if(summary.failed)process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
