'use strict';
const $ = id => document.getElementById(id);
const statusLabels = {received:'접수',dispatched:'출동',on_scene:'현장 도착',rescuing:'구조 진행',reviewing:'확인 필요',closed:'처리 완료'};
const channelLabels = {voice:'음성 신고',sms:'문자',mms:'사진·영상',app:'앱 신고',video_call:'영상통화',web:'인터넷',kakao:'카카오톡 합성 접수',field:'현장 보고'};
const categoryLabels = {flood:'침수·고립',fire:'화재',rescue:'구조',medical:'구급',other:'기타'};
const priorityLabels = {urgent:'긴급',high:'높음',normal:'보통'};
const outcomeLabels = {rescued:'구조 완료',self_evacuated:'자력 대피 확인',transferred:'다른 팀 인계'};
const kindLabels = {initial:'최초 접수',additional:'추가 정보',field:'현장 보고',correction:'인원·위치 정정'};
const actionLabels = {incident_updated:'사건 수정',progress_added:'진행 변경',progress_changed:'진행 변경',outcome_confirmed:'처리 결과 확정',incident_reopened:'완료 사건 재개',create:'사건 접수',created:'사건 접수',report:'보고 등록',report_added:'보고 등록',add_report:'보고 등록',update:'사건 수정',updated:'사건 수정',edit:'사건 수정',progress:'진행 변경',outcome:'처리 결과 확정',reopen:'완료 사건 재개',auto_reopen:'새 정보로 재개',ai_review_confirmed:'AI 초안 담당자 확인'};
const fieldLabels = {title:'사건명',location:'위치',people_count:'인원',priority:'우선도',status:'진행 상태',assigned_team_id:'담당팀',summary:'요약',outcome:'처리 결과',intake119:'119 접수 항목'};
const state = {incidents:[],resources:[],incident:null,view:'dashboard',filters:{query:'',status:'all',channel:'all',priority:'all'},reportTab:'all',detailTab:'reports',loading:false,listLoaded:false};
let toastTimer, loadToken=0, modal=null, restoreFocus=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function date(v,full=false){if(!v)return '기록 없음';const d=new Date(v);if(Number.isNaN(d.valueOf()))return String(v);return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',...(full?{month:'2-digit',day:'2-digit'}:{}),hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function count(v){return v===null||v===undefined?'확인 필요':`${v}명`;}
function teamName(id){return state.resources.find(r=>r.id===id)?.name||'미배정';}
function statusBadge(s){return `<span class="status ${esc(s)}">${esc(statusLabels[s]||s)}</span>`;}
function priorityBadge(p){return `<span class="priority ${esc(p)}">${esc(priorityLabels[p]||p)}</span>`;}
function incidentLink(i){return `#incident/${encodeURIComponent(i.id)}`;}
function featuredBadge(i){return i.demo_featured===true?'<span class="featured-badge" title="발표용 상단 고정이며 긴급도 점수가 아닙니다.">발표 대표 사례</span>':'';}
function notices(i){return (i.checks||[]).filter(c=>c.level==='warning');}
const attentionLevels={immediate:'즉시 확인',decision:'판단 필요',follow_up:'후속 확인'};
const attentionOrder={immediate:0,decision:1,follow_up:2};
const operatorOrder={urgent:0,high:1,normal:2};
function tasks(i){return i.status==='closed'?[]:[...(i.attention||[])].sort((a,b)=>(attentionOrder[a.level]??3)-(attentionOrder[b.level]??3));}
function actionOrder(a,b){return (attentionOrder[tasks(a)[0]?.level]??3)-(attentionOrder[tasks(b)[0]?.level]??3)||(operatorOrder[a.priority]??3)-(operatorOrder[b.priority]??3)||new Date(a.created_at)-new Date(b.created_at)||String(a.id).localeCompare(String(b.id));}
function attentionIncidents(){return state.incidents.filter(i=>tasks(i).length).sort(actionOrder);}
function taskBadge(t){return `<span class="attention-level ${esc(t.level)}">${esc(attentionLevels[t.level]||'확인 필요')}</span>`;}
function renderAttentionStrip(){
 const targets=attentionIncidents(),top=targets[0],task=top&&tasks(top)[0],immediate=targets.filter(i=>tasks(i)[0].level==='immediate').length,decision=targets.filter(i=>tasks(i)[0].level==='decision').length;
 $('attention-nav-count').textContent=targets.length;
 const box=$('attention-strip');box.hidden=false;box.className=`attention-strip ${esc(task?.level||'clear')}`;
 box.innerHTML=`<div class="attention-strip-counts"><span class="strip-label">현재 미처리 사건 알림</span><div><strong>즉시 확인 ${immediate}건</strong><span>판단 필요 ${decision}건</span>${targets.length?`<span>전체 대상 ${targets.length}건</span>`:''}</div></div>${top?`<div class="attention-strip-top" data-incident-surface><span class="strip-label">최우선 확인 · ${esc(attentionLevels[task.level])}</span><a href="${incidentLink(top)}" data-incident-link>${esc(top.title)} <small>${esc(top.id)}</small></a><p>${esc(task.reason)}</p></div><a class="strip-open" href="#attention">전체 판단·조치 보기 →</a>`:'<p class="strip-clear">현재 판단·조치 과제가 없습니다.</p>'}`;
}
function attentionTask(i,t){return `<article class="attention-task ${esc(t.level)}"><div class="attention-task-head">${taskBadge(t)}<span class="rule-label">규칙 기반 권고 · 담당자 판단 필요</span></div><h3>${esc(t.title)}</h3><dl class="attention-explanation"><div><dt>현재 상황</dt><dd>${esc(t.situation)}</dd></div><div><dt>확인이 시급한 이유</dt><dd>${esc(t.reason)}</dd></div></dl><div class="attention-evidence">${(t.evidence||[]).length?t.evidence.map(e=>`<blockquote><p>“${esc(e.quote)}”</p><footer><span>접수 ${esc(date(e.received_at,true))}</span><button type="button" class="link-button" data-attention-incident="${esc(i.id)}" data-attention-report="${esc(e.report_id)}" aria-label="${esc(e.report_id)} 원문 보기">원문 보기 →</button></footer></blockquote>`).join(''):'<p class="attention-no-evidence">인용할 신고 원문이 없습니다. 담당자가 현재 사건 정보를 확인하세요.</p>'}</div><div class="attention-next"><span class="strip-label">다음 업무</span><p>${esc(t.next_action)}</p><button type="button" data-attention-incident="${esc(i.id)}" data-attention-action="${esc(t.action)}">${esc({progress:'담당팀·진행 확인', 'field-report':'현장 보고 등록',report:'추가 정보 확인·등록',edit:'사건 정보 대조·수정'}[t.action]||'사건 확인')} →</button></div></article>`;}
function attentionCard(i,{allTasks=false}={}){const list=tasks(i);return `<section class="attention-card"${allTasks?'':' data-incident-surface'}><div class="attention-card-head">${featuredBadge(i)}<span class="incident-id">${esc(i.id)}</span><h2>${allTasks?`<span>${esc(i.title)}</span>`:`<a href="${incidentLink(i)}" data-incident-link>${esc(i.title)}</a>`}</h2><p>${esc(i.location)}</p><div class="attention-context">${statusBadge(i.status)}<span>${esc(teamName(i.assigned_team_id))}</span><span class="operator-priority">담당자 우선도 ${priorityBadge(i.priority)}</span></div></div>${(allTasks?list:list.slice(0,1)).map(t=>attentionTask(i,t)).join('')}${!allTasks&&list.length>1?`<a class="attention-more" href="${incidentLink(i)}" tabindex="-1">이 사건의 판단 과제 ${list.length}개 모두 보기 →</a>`:''}</section>`;}
function attentionSection({detail=false}={}){
 const targets=detail?(tasks(state.incident).length?[state.incident]:[]):attentionIncidents(),all=state.view==='attention'||detail,shown=all?targets:targets.slice(0,3);
 return `<section class="attention-section" aria-label="${detail?'이 사건의 판단·조치':'우선 판단·조치 사건'}"><div class="attention-section-head"><div><h2>${detail?'이 사건의 판단·조치':'지금 판단·조치할 사건'} <span>${detail?tasks(state.incident).length:targets.length}${detail?'개 과제':'건'}</span></h2><p>${detail?'현재 확인할 과제와 원문 근거를 대조하고 다음 업무를 기록하세요.':'즉시 확인 → 판단 필요 → 후속 확인 순. 같은 단계에서는 담당자 우선도와 접수 순으로 표시합니다.'}</p></div>${all?'':`<a href="#attention">전체 ${targets.length}건 보기 →</a>`}</div>${shown.length?`<div class="attention-grid ${detail?'detail-attention':all?'all-attention':''}">${shown.map(i=>attentionCard(i,{allTasks:detail})).join('')}</div>`:'<div class="attention-empty"><strong>현재 판단·조치 과제가 없습니다.</strong><p>새 보고 또는 사건 변경 후 최신 과제가 표시됩니다.</p></div>'}</section>`;
}
function renderAttention(){ $('view').innerHTML=`<div class="page-head"><div><h1>지금 판단·조치</h1><p>담당자 판단이 필요한 현재 미처리 사건과 다음 업무를 확인합니다.</p></div><div class="head-actions"><button type="button" class="primary" data-action="ai-new">＋ 신규 신고 AI 분석</button><button type="button" data-action="new">AI 없이 담당자 직접 입력</button></div></div>${attentionSection()}`; }
async function openAttentionWork(button){
 const id=button.dataset.attentionIncident,action=button.dataset.attentionAction,reportId=button.dataset.attentionReport;
 if(action&&!['progress','field-report','report','edit'].includes(action))return;
 button.disabled=true;
 try{
  await loadList();
  const hash=`#incident/${encodeURIComponent(id)}`;if(location.hash!==hash)history.pushState(null,'',hash);
  await route(false);
  if(state.incident?.id!==id||state.view!=='detail')return;
  if(reportId)focusReport(reportId);else if(state.incident.status==='closed')toast('이미 완료된 사건입니다. 최신 처리 결과를 확인하세요.');else openTask(action);
 }catch(error){pageError(error.message);}finally{button.disabled=false;}
}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
async function api(path,{method='GET',body}={}){
 if(window.RescuePages)return window.RescuePages.request(path,{method,body});
 if(window.RescueCloud)return window.RescueCloud.request(path,{method,body});
 const response=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});
 let data;try{data=await response.json();}catch(_){throw new Error('서버 응답을 읽지 못했습니다. 연결 상태를 확인하세요.');}
 if(!response.ok){const error=new Error(data.error||'정보를 저장하지 못했습니다. 다시 확인하세요.');error.status=response.status;throw error;}return data;
}
function pageError(message){const box=$('page-error');box.replaceChildren();box.hidden=!message;if(message){const span=document.createElement('span');span.textContent=message;const retry=document.createElement('button');retry.type='button';retry.textContent='다시 불러오기';retry.className='small';retry.addEventListener('click',()=>refresh());box.append(span,retry);}}
async function loadList(){const d=await api('/api/incidents');if(!Array.isArray(d.incidents)||!Array.isArray(d.resources))throw new Error('사건 목록 형식을 확인할 수 없습니다.');state.incidents=d.incidents;state.resources=d.resources;state.listLoaded=true;$('active-nav-count').textContent=d.incidents.filter(i=>i.status!=='closed').length;$('refreshed-at').textContent=`${date(new Date().toISOString())} 갱신`;renderAttentionStrip();}
async function refresh(){const b=$('refresh');b.disabled=true;try{if(window.RescueCloud&&!window.RescuePages){await window.RescueCloud.boot();renderConnection();if(['unconfigured','unavailable'].includes(window.RescueCloud.mode)){if(routeTarget().view==='settings')await route(false);else renderDisconnected();return;}}await loadList();await route(false);pageError(null);toast('최신 사건 정보를 불러왔습니다.');}catch(e){pageError(e.message);}finally{b.disabled=false;}}
function routeTarget(){const h=location.hash.slice(1)||'dashboard';if(h.startsWith('incident/'))return {view:'detail',id:decodeURIComponent(h.slice(9))};return {view:['dashboard','attention','active','results','resources','field','settings'].includes(h)?h:'dashboard'};}
let listInitialization=null;
async function ensureList(){if(state.listLoaded)return;if(!listInitialization)listInitialization=loadList().finally(()=>{listInitialization=null;});await listInitialization;}
async function initializeWorkspace(){
 if(window.RescueCloud){await window.RescueCloud.boot();renderConnection();if(['unconfigured','unavailable'].includes(window.RescueCloud.mode)){if(routeTarget().view==='settings')await route(false);else renderDisconnected();return;}}
 try{await ensureList();}catch(error){if(routeTarget().view!=='settings')throw error;await route(false);pageError(error.message);return;}
 await route(false);renderDraftRecovery();
}
async function route(focus=true){
 if(routeTarget().view!=='settings'&&window.RescueCloud&&!window.RescuePages&&['unconfigured','unavailable'].includes(window.RescueCloud.mode)){renderDisconnected();return;}
 const token=++loadToken;const target=routeTarget();state.view=target.view;document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===target.view||(target.view==='detail'&&a.dataset.nav==='active');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});pageError(null);
 if(target.view!=='settings'){
  try{await ensureList();if(token!==loadToken)return;}catch(error){if(token!==loadToken)return;pageError(error.message);$('view').innerHTML='<div class="empty"><strong>사건 목록을 불러오지 못했습니다.</strong>연결 상태를 확인하고 다시 불러오기를 선택하세요.</div>';return;}
 }
 if(target.view==='detail'){
  state.incident=null;
  $('view').innerHTML='<div class="loading">사건 원문과 진행 기록을 불러오고 있습니다.</div>';
  try{const i=await api(`/api/incidents/${encodeURIComponent(target.id)}`);if(token!==loadToken)return;state.incident=i;state.incidents=state.incidents.map(existing=>existing.id===i.id?i:existing);renderAttentionStrip();state.detailTab='reports';state.reportTab='all';renderDetail();}catch(e){if(token!==loadToken)return;pageError(e.message);$('view').innerHTML='<div class="empty"><strong>사건을 열 수 없습니다.</strong><a href="#dashboard">사건 목록으로 돌아가기</a></div>';}
 }else {state.incident=null;if(target.view==='settings')await renderSettings();else if(target.view==='field')renderField();else if(target.view==='resources')renderResources();else if(target.view==='attention')renderAttention();else renderDashboard();}
 if(focus){$('workspace').focus({preventScroll:true});window.scrollTo(0,0);}
}
function statSummary(){const open=state.incidents.filter(i=>i.status!=='closed'),review=open.filter(i=>tasks(i).length),closed=state.incidents.filter(i=>i.status==='closed'),available=state.resources.filter(r=>r.status==='available');return `<div class="stats" aria-label="업무 요약"><div class="stat"><span class="stat-label">미처리 사건</span><span class="stat-number">${open.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">판단·조치 대상</span><span class="stat-number warning">${review.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">처리 완료</span><span class="stat-number done">${closed.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">가용 대응팀</span><span class="stat-number">${available.length}<small> 팀</small></span></div></div>`;}
function optionList(labels,selected,allLabel){return `${allLabel?`<option value="all">${esc(allLabel)}</option>`:''}${Object.entries(labels).map(([v,l])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(l)}</option>`).join('')}`;}
function renderDashboard(){
 const title=state.view==='results'?'처리 결과':state.view==='active'?'진행 사건':'상황 대시보드';
 const desc=state.view==='results'?'담당자 확인 결과와 이전 처리 이력을 조회합니다.':state.view==='active'?'접수부터 현장 진행까지, 남아 있는 사건을 확인합니다.':'접수 현황과 현장 진행을 대조하고, 다음 인계를 준비합니다.';
 $('view').innerHTML=`<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="head-actions"><button type="button" class="primary" data-action="ai-new">＋ 신규 신고 AI 분석</button><button type="button" data-action="new">AI 없이 담당자 직접 입력</button></div></div>${statSummary()}${state.view==='results'?'':attentionSection()}<div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>${state.view==='results'?'완료 사건 목록':'사건 목록'}</h2><small>${state.view==='results'?'최근 변경 순':state.incidents.some(i=>i.demo_featured===true)?'발표 대표 사례 상단 · 나머지 판단·조치 순':'판단·조치 순'}</small></div><div class="filters"><div class="filter-row"><div class="search-wrap"><label for="incident-search"><span aria-hidden="true">⌕</span><span class="sr-only">사건 검색</span></label><input id="incident-search" type="search" placeholder="사건번호, 신고 내용, 위치 검색" value="${esc(state.filters.query)}"></div><label class="sr-only" for="channel-filter">접수 채널 필터</label><select id="channel-filter" class="filter-select">${optionList(channelLabels,state.filters.channel,'모든 채널')}</select><label class="sr-only" for="priority-filter">우선도 필터</label><select id="priority-filter" class="filter-select">${optionList(priorityLabels,state.filters.priority,'모든 우선도')}</select></div><div class="filter-row">${[['all','전체'],['unresolved','미처리'],['review','확인 필요'],['closed','처리 완료']].map(([v,l])=>`<button type="button" class="filter-chip ${state.filters.status===v?'active':''}" data-filter="${v}" aria-pressed="${state.filters.status===v}">${l}</button>`).join('')}<span class="filter-count" id="filtered-count"></span><button type="button" class="link-button" data-action="clear-filters">필터 초기화</button></div></div><div class="table-container"><table><thead><tr><th scope="col">사건 / 핵심 판단 과제</th><th scope="col">위치 / 인원</th><th scope="col">신고 채널</th><th scope="col">담당자 우선도</th><th scope="col">진행 상태</th><th scope="col">담당팀</th><th scope="col">최근 변경</th></tr></thead><tbody id="incident-rows"></tbody></table></div><div class="table-foot"><span id="table-total"></span><span>사건을 선택하면 원문과 처리 이력을 볼 수 있습니다.</span></div></section><aside class="side-stack" aria-label="자원과 인계 확인">${resourcePanel()}${handoffPanel()}</aside></div>`;
 updateTable();$('incident-search').addEventListener('input',e=>{state.filters.query=e.target.value;updateTable();});$('channel-filter').addEventListener('change',e=>{state.filters.channel=e.target.value;updateTable();});$('priority-filter').addEventListener('change',e=>{state.filters.priority=e.target.value;updateTable();});
}
function visibleIncidents(){const f=state.filters,q=f.query.trim().toLocaleLowerCase();const filtered=state.incidents.filter(i=>{
 if(state.view==='results'&&i.status!=='closed'||state.view==='active'&&i.status==='closed')return false;
 if(f.status==='unresolved'&&i.status==='closed'||f.status==='closed'&&i.status!=='closed'||f.status==='review'&&!tasks(i).length)return false;
 if(f.channel!=='all'&&!(i.reports||[]).some(r=>r.channel===f.channel))return false;
 if(f.priority!=='all'&&i.priority!==f.priority)return false;
 if(q&&![i.id,i.title,i.location,i.summary,...(i.reports||[]).map(r=>r.text)].join(' ').toLocaleLowerCase().includes(q))return false;return true;
 });return state.view==='results'?filtered.sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)):filtered;}
function updateTable(){const rows=visibleIncidents();$('filtered-count').textContent=`${rows.length}건`;$('table-total').textContent=`조회 ${rows.length}건 / 전체 ${state.incidents.length}건`;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===state.filters.status);b.setAttribute('aria-pressed',b.dataset.filter===state.filters.status);});$('incident-rows').innerHTML=rows.length?rows.map(i=>`<tr data-incident-surface><td class="incident-cell">${featuredBadge(i)}<a class="incident-link" href="${incidentLink(i)}" data-incident-link>${esc(i.title)}</a><span class="incident-id">${esc(i.id)}</span>${tasks(i).length?`<span class="table-attention ${esc(tasks(i)[0].level)}">${esc(attentionLevels[tasks(i)[0].level])} · ${esc(tasks(i)[0].title)}</span>`:''}</td><td class="location-cell">${esc(i.location)}<small>${esc(count(i.people_count))}</small></td><td class="channel-cell">${esc([...new Set((i.reports||[]).map(r=>channelLabels[r.channel]||r.channel))].join(', '))}</td><td>${priorityBadge(i.priority)}</td><td>${statusBadge(i.status)}</td><td class="channel-cell">${esc(teamName(i.assigned_team_id))}</td><td class="cell-time">${esc(date(i.updated_at,true))}</td></tr>`).join(''):`<tr><td colspan="7"><div class="empty"><strong>조회 조건에 맞는 사건이 없습니다.</strong>검색어와 필터를 변경하거나 새 사건을 접수하세요.</div></td></tr>`;}
function resourcePanel(){const available=state.resources.filter(r=>r.status==='available');return `<section class="panel"><div class="panel-head"><h2>대응 자원</h2><a href="#resources" class="muted">전체 보기</a></div><div class="side-body">${state.resources.slice(0,5).map(r=>`<div class="resource-row"><div><strong>${esc(r.name)}</strong><small>${esc(r.type)} / ${r.crew_count}명</small></div><span class="${r.status==='available'?'available':'assigned'}">${r.status==='available'?'가용':'배정 중'}</span></div>`).join('')||'<p class="empty">등록된 대응팀이 없습니다.</p>'}<p class="operation-note">가용 ${available.length}팀 / 전체 ${state.resources.length}팀</p></div></section>`;}
function handoffPanel(){const targets=attentionIncidents().slice(0,4);return `<section class="panel"><div class="panel-head"><h2>판단·조치 요약</h2><a href="#attention" class="muted">전체 보기</a></div><div class="side-body">${targets.length?targets.map(i=>`<a class="handoff-link" href="${incidentLink(i)}"><span class="incident-id">${esc(i.id)}</span><strong>${esc(i.title)}</strong><small>${esc(tasks(i)[0].title)}</small></a>`).join(''):'<p class="empty">현재 판단·조치 과제가 없습니다.</p>'}</div></section>`;}
function renderResources(){
 $('view').innerHTML=`<div class="page-head"><div><h1>대응 자원</h1><p>가용팀을 확인하고 진행 중인 사건에 배정합니다.</p></div><a href="#active">진행 사건 보기</a></div>${statSummary()}<div class="resource-grid">${state.resources.map(r=>{const i=state.incidents.find(x=>x.id===r.incident_id);return `<section class="resource-card"${i?' data-incident-surface':''}><span class="${r.status==='available'?'available':'assigned'}">${r.status==='available'?'배정 가능':'사건 대응 중'}</span><h2>${esc(r.name)}</h2><span class="resource-type">${esc(r.type)} / 대원 ${r.crew_count}명</span><p>${i?esc(i.title)+'<br>'+esc(i.location):'새로운 사건에 배정할 수 있습니다.'}</p>${i?`<div class="button-row"><a href="${incidentLink(i)}" data-incident-link aria-label="${esc(r.name)} 배정 사건 ${esc(i.title)} 열기">배정 사건 열기</a>${statusBadge(i.status)}</div>`:`<label class="sr-only" for="assign-${esc(r.id)}">${esc(r.name)} 배정할 사건</label><select id="assign-${esc(r.id)}"><option value="">배정할 사건 선택</option>${state.incidents.filter(x=>x.status!=='closed').map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')}</select><div class="button-row"><button type="button" class="small" data-action="assign-resource" data-resource="${esc(r.id)}">팀 배정</button></div>`}</section>`;}).join('')||'<div class="empty">등록된 대응 자원이 없습니다.</div>'}</div>`;
}
function renderDetail(){const i=state.incident;if(!i)return;const closed=i.status==='closed';
 $('view').innerHTML=`<div class="page-head"><div><div class="page-meta"><a href="#${closed?'results':'active'}">‹ 사건 목록</a><span>/</span><span>${esc(i.id)}</span><span>${esc(categoryLabels[i.category]||i.category)}</span></div>${featuredBadge(i)}<h1>${esc(i.title)}</h1><p>${esc(i.summary||'접수 원문과 최신 현장 정보를 대조하세요.')}</p></div><div class="head-actions"><span class="operator-priority">담당자 우선도 ${priorityBadge(i.priority)}</span>${statusBadge(i.status)}<button type="button" data-action="edit">사건 수정</button></div></div><dl class="facts-strip"><div class="fact"><dt>구조 대상 위치</dt><dd>${esc(i.location)}</dd></div><div class="fact"><dt>접수 인원</dt><dd>${esc(count(i.people_count))}</dd></div><div class="fact"><dt>담당팀</dt><dd>${esc(teamName(i.assigned_team_id))}</dd></div><div class="fact"><dt>접수 / 최근 변경</dt><dd>${esc(date(i.created_at,true))}<small>최근 ${esc(date(i.updated_at,true))}</small></dd></div></dl>${i.demo_featured===true?'<p class="featured-context">발표용 상단 고정 · 긴급도는 담당자 우선도와 규칙 기반 확인 과제로 표시합니다. 아래 원문·현장 진행·미확인 인원을 대조하세요. 가상 B2 위치는 더포엠 공간목업·관악 출동경로와 자동 연결되지 않습니다.</p>':''}${confirmedIntake(i)}${attentionSection({detail:true})}<div class="detail-grid"><div class="detail-main"><section class="panel"><div class="panel-head"><h2>접수 원문과 보고</h2><span class="muted">${(i.reports||[]).length}개 기록</span></div><div class="section-tabs" role="tablist" aria-label="사건 기록">${[['reports','신고·현장 보고'],['history','변경·결과 이력']].map(([v,l])=>`<button type="button" role="tab" id="tab-${v}" aria-controls="detail-content" aria-selected="${state.detailTab===v}" class="${state.detailTab===v?'active':''}" data-detail-tab="${v}">${l}</button>`).join('')}</div><div id="detail-content" role="tabpanel" aria-labelledby="tab-${state.detailTab}"></div></section></div><aside class="detail-side"><section class="panel"><div class="panel-head"><h2>근거 대조 · 확인 사항</h2><span class="rule-label">규칙 기반 대조</span></div><div class="check-list">${(i.checks||[]).length?(i.checks||[]).map(c=>`<article class="check ${esc(c.level)}"><div class="check-title"><span class="check-marker" aria-hidden="true">${c.level==='warning'?'!':'i'}</span><strong>${esc(c.title)}</strong></div><p>${esc(c.detail)}</p><div class="check-links">${(c.report_ids||[]).map((id,index)=>`<button type="button" data-report-link="${esc(id)}" aria-label="${esc(id)} 원문 보기">원문 ${index+1} 보기</button>`).join('')}</div></article>`).join(''):'<div class="empty">추가 대조 사항이 없습니다.<br>결과 확정 전 현장 근거를 확인하세요.</div>'}</div></section>${closed?outcomePanel():operationsPanel()}${closed?'':`<section class="panel"><div class="panel-head"><h2>처리 결과</h2><span class="muted">미확정</span></div><div class="outcome-body"><p class="operation-note">구조·자력 대피·인계의 현장 근거와 접수 인원을 대조한 뒤 담당자가 확정합니다.</p><div class="action-stack"><button type="button" class="primary" data-action="outcome">처리 결과 확인</button></div></div></section>`}</aside></div>`;
 renderDetailContent();
}
function operationsPanel(){const i=state.incident;return `<section class="panel"><div class="panel-head"><h2>현장 진행</h2>${statusBadge(i.status)}</div><div class="operations-body"><div class="team-assignment"><div><strong>${esc(teamName(i.assigned_team_id))}</strong><small>${i.assigned_team_id?'담당팀의 보고를 대조하세요.':'대응팀을 배정하고 진행 상황을 기록하세요.'}</small></div><button type="button" class="small" data-action="progress">진행 변경</button></div>${progressList(i.progress||[])}<div class="action-stack"><button type="button" class="primary" data-action="ai-report">추가 신고·현장 정보 AI 분석</button><button type="button" data-action="report">AI 없이 추가 정보 직접 입력</button><button type="button" data-action="field-report">현장 보고 등록</button></div><p class="operation-note">배정·현장 도착·부분 구조만으로 처리 완료가 되지 않습니다.</p></div></section>`;}
function progressList(items,limit=4){return items.length?`<ol class="progress-list">${[...items].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,limit).map(p=>`<li class="progress-item"><strong>${esc(statusLabels[p.status]||p.status)}${p.team_id?' / '+esc(teamName(p.team_id)):''}</strong><p>${esc(p.note)}</p><small>${esc(p.actor)} / ${esc(date(p.created_at,true))}</small></li>`).join('')}</ol>`:'<p class="muted">등록된 현장 진행 기록이 없습니다.</p>';}
function outcomePanel(){const i=state.incident,o=i.outcome||{},basis=(i.reports||[]).find(r=>r.id===o.basis_report_id);return `<section class="panel"><div class="panel-head"><h2>확정 처리 결과</h2>${statusBadge('closed')}</div><div class="outcome-body"><div class="outcome-summary"><strong>${esc(outcomeLabels[o.outcome]||'처리 완료')}</strong><p>확인 인원 ${esc(count(o.confirmed_count))}</p></div><dl class="outcome-detail"><dt>확정 담당자</dt><dd>${esc(o.actor||'기록 확인 필요')}</dd><dt>확정 시각</dt><dd>${esc(date(o.confirmed_at||o.created_at,true))}</dd><dt>현장 근거</dt><dd>${o.basis_report_id?`<button type="button" class="link-button" data-report-link="${esc(o.basis_report_id)}" aria-label="현장 근거 ${esc(o.basis_report_id)} 원문 보기">근거 원문 보기</button>`:'기록 확인 필요'}</dd><dt>확인 내용</dt><dd>${esc(o.note||basis?.text||'기록 확인 필요')}</dd></dl><div class="action-stack"><button type="button" data-action="reopen">완료 재개 · 결과 정정</button><button type="button" data-action="report">추가 정보 등록</button></div><p class="operation-note">결과를 정정하면 재개 이유와 이전 결과를 보존하고 새 근거로 다시 확정합니다.</p></div></section>`;}
function renderDetailContent(){const i=state.incident,target=$('detail-content');if(!target)return;if(state.detailTab==='history'){target.innerHTML=historyContent(i);return;}
 const reports=[...(i.reports||[])].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).filter(r=>state.reportTab==='all'||state.reportTab==='field'&&(r.kind==='field'||r.channel==='field')||state.reportTab==='media'&&(r.attachments||[]).length);
 target.innerHTML=`<div class="report-toolbar">${[['all','전체 원문'],['field','현장 보고'],['media','첨부 자료']].map(([v,l])=>`<button type="button" class="filter-chip ${state.reportTab===v?'active':''}" data-report-tab="${v}" aria-pressed="${state.reportTab===v}">${l}</button>`).join('')}<span class="filter-count">최신 접수 순</span></div><div class="timeline">${reports.length?reports.map(reportCard).join(''):'<div class="empty">이 분류에 등록된 보고가 없습니다.</div>'}</div>`;
}
function safeMedia(url){if(typeof url==='string'&&/^\/api\/media\/[a-zA-Z0-9_-]+$/.test(url))return url;if(window.RescuePages)return window.RescuePages.mediaUrl(url);return typeof url==='string'&&/^\/media\/[a-zA-Z0-9._\-/]+$/.test(url)&&!url.split('/').includes('..')?url:null;}
function reportCard(r){return `<article class="report" id="report-${esc(r.id)}" tabindex="-1"><div class="report-head"><div class="report-source"><span class="channel-tag">${esc(channelLabels[r.channel]||r.channel)}</span><span class="report-kind">${esc(kindLabels[r.kind]||'접수 기록')}</span><span>${esc(r.actor)}</span></div><span>${esc(r.id)}</span></div><p class="report-text">${esc(r.text)}</p>${r.people_count!==undefined||r.location?`<div class="report-proposal">${r.people_count!==undefined?`<span>보고 인원 ${esc(count(r.people_count))}</span>`:''}${r.location?`<span>보고 위치 ${esc(r.location)}</span>`:''}</div>`:''}${r.ai_analysis?confirmedAIRecord(r.ai_analysis):''}<p class="report-time">발생 ${esc(date(r.occurred_at,true))} / 접수 ${esc(date(r.received_at,true))}</p>${(r.attachments||[]).length?`<div class="attachments">${r.attachments.map((a,idx)=>mediaCard(a,r.id,idx)).join('')}</div>`:''}</article>`;}
function mediaCard(a,rid,idx){const url=safeMedia(a.url);if(!url)return '<p class="media-caption">첨부 경로를 확인할 수 없습니다. 담당자에게 자료를 요청하세요.</p>';const caption=a.caption||a.filename||'첨부 자료';const source={ai_generated:'생성 사진',tts_synthetic:'합성 음성',operator_upload:'담당자 업로드'}[a.source]||'접수 첨부';
 if(a.media_type==='image')return `<div><button type="button" class="image-preview" data-image-report="${esc(rid)}" data-image-index="${idx}" aria-label="${esc(caption)} 확대"><img src="${esc(url)}" alt="${esc(caption)}" loading="lazy"><span>사진 확대</span></button><p class="media-caption">${esc(caption)} / ${source}</p></div>`;
 if(a.media_type==='audio'){const comparisonLabel={'parking-call-noisy.wav':'잡음 포함 신고 원본','parking-call-enhanced.wav':'DSP 처리 비교 음성'}[a.filename];return `<div class="audio-box"><strong>${esc(comparisonLabel||a.filename||'신고 음성')}</strong><audio controls preload="metadata" src="${esc(url)}" aria-label="${esc(caption)}">브라우저에서 음성 재생을 지원하지 않습니다.</audio><p class="media-caption">${esc(caption)} / ${source}</p>${comparisonLabel?'<p class="media-caption">합성 음성의 실제 파일 비교입니다. DSP 처리는 의미 복구·화자 분리·실제 ASR을 보장하지 않습니다.</p>':''}${a.transcript?`<details class="transcript"><summary>음성 원문 보기</summary><p>${esc(a.transcript)}</p><small>합성 대본 또는 담당자 기록입니다. 자동 음성 인식 결과가 아닙니다.</small></details>`:''}</div>`;}
 if(a.media_type==='video')return `<div><video controls preload="metadata" src="${esc(url)}" aria-label="${esc(caption)}">브라우저에서 영상 재생을 지원하지 않습니다.</video><p class="media-caption">${esc(caption)} / ${source}</p>${a.transcript?`<details class="transcript"><summary>영상 기록 보기</summary><p>${esc(a.transcript)}</p></details>`:''}</div>`;return '<p class="media-caption">첨부 형식을 확인할 수 없습니다.</p>';}
function displayValue(k,v){if(v===null||v===undefined)return '없음';if(k==='status')return statusLabels[v]||v;if(k==='priority')return priorityLabels[v]||v;if(k==='people_count')return count(v);if(k==='assigned_team_id')return teamName(v);if(k==='outcome')return typeof v==='object'?outcomeLabels[v.outcome]||'처리 결과':outcomeLabels[v]||v;return typeof v==='object'?'기록 보존':String(v);}
function historyContent(i){const history=i.outcome_history||[],audit=[...(i.audit||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return `<div class="audit-list">${history.length?`<p class="history-label">이전 처리 결과 ${history.length}건</p>${[...history].reverse().map(o=>`<article class="result-history"><strong>${esc(outcomeLabels[o.outcome]||'이전 처리 결과')} / ${esc(count(o.confirmed_count))}</strong><p>${esc(o.note||'')}</p><small>확정 ${esc(date(o.confirmed_at||o.created_at,true))} / ${esc(o.actor||'')}</small><p>재개 이유: ${esc(o.reopen_reason||'새 정보 접수')}</p><small>재개 ${esc(date(o.reopened_at,true))} / ${esc(o.reopened_by||'')}</small></article>`).join('')}`:''}<p class="history-label">사건 변경 기록</p>${audit.length?audit.map(a=>{const before=a.before||{},after=a.after||{},changes=Object.keys(fieldLabels).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])&&(k in before||k in after));return `<details class="audit-item"><summary><strong>${esc(actionLabels[a.action]||'업무 기록')} / ${esc(a.actor)}</strong><span>${esc(date(a.created_at,true))}</span></summary><p class="audit-reason">${esc(a.reason||'업무 기록을 저장했습니다.')}</p>${changes.length?`<div class="audit-changes"><div class="change-row"><span>변경 항목</span><span>이전</span><span>변경 후</span></div>${changes.map(k=>`<div class="change-row"><span>${fieldLabels[k]}</span><span>${esc(displayValue(k,before[k]))}</span><span>${esc(displayValue(k,after[k]))}</span></div>`).join('')}</div>`:''}</details>`;}).join(''):'<p class="empty">변경 이력이 없습니다.</p>'}<p class="history-label">전체 현장 진행 기록</p>${progressList(i.progress||[],Infinity)}</div>`;}
function inputField(name,label,{value='',type='text',required=false,full=false,help='',optional=false,min,placeholder='',options,rows=3}={}){
 const attrs=`id="f-${esc(name)}" name="${esc(name)}" ${required?'required':''}`;
 const control=options?`<select ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:type==='textarea'?`<textarea ${attrs} rows="${rows}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input ${attrs} type="${esc(type)}" value="${esc(value)}" ${min!==undefined?`min="${min}" step="1"`:''} placeholder="${esc(placeholder)}">`;
 return `<div class="field ${full?'full':''}"><label for="f-${esc(name)}">${esc(label)}${optional?'<span class="optional">선택</span>':''}</label>${control}${help?`<small>${esc(help)}</small>`:''}</div>`;
}
const actorField=()=>inputField('actor','담당자',{value:'상황실 김담당',required:true});
const uploadField=()=>`<div class="field full"><label for="f-files">첨부 자료<span class="optional">선택</span></label><input type="file" id="f-files" name="files" multiple accept="image/png,image/jpeg,audio/wav,audio/mpeg,video/mp4"><small>PNG, JPG, WAV, MP3, MP4 / 파일당 최대 ${window.RescueCloud?.mode==='cloud'?'3MiB':'8MiB'}. 실제 개인정보가 없는 훈련 자료를 사용하세요.</small><div id="upload-list" class="upload-list"></div></div>`;
function openTask(kind,{teamId}={}){
 const i=state.incident,closed=i?.status==='closed';if(kind!=='new'&&!i)return;if(kind==='progress'&&closed){toast('완료 사건은 먼저 재개한 뒤 진행을 변경하세요.');return;}
 restoreFocus=document.activeElement;modal={kind,incidentId:i?.id,revision:i?.revision,pendingFiles:[],attachments:[],busy:false};
 const cfg={new:['신규 사건 접수','신고 원문과 구조 대상 정보를 접수합니다.','사건 접수'],report:['추가 정보 등록','원문을 추가합니다. 인원·위치 변경은 정정으로 선택하세요.','정보 등록'],'field-report':['현장 보고 등록','해당 사건의 현장 확인 내용과 확인 인원을 기록하세요.','현장 보고 등록'],edit:['사건 정보 수정','원래 값은 이력에 남습니다. 수정 이유를 함께 기록하세요.','수정 저장'],progress:['현장 진행 변경','진행 상황과 담당팀을 기록합니다. 배정은 완료 확인이 아닙니다.','진행 저장'],outcome:['처리 결과 확인','현장 근거와 현재 접수 인원을 대조한 뒤 확정합니다.','처리 결과 확정'],reopen:['완료 재개 · 결과 정정','이전 결과를 보존하고 확인 필요 상태로 재개합니다.','사건 재개']}[kind];
 $('dialog-title').textContent=cfg[0];$('dialog-description').textContent=cfg[1];$('dialog-save').textContent=cfg[2];$('dialog-error').hidden=true;$('dialog-error').replaceChildren();let fields='';
 if(kind==='new')fields=inputField('title','사건명',{required:true,full:true,placeholder:'예: 새봄빌라 201호 침수 고립'})+inputField('category','사건 분류',{value:'flood',options:Object.entries(categoryLabels)})+inputField('priority','담당자 우선도',{value:'normal',options:Object.entries(priorityLabels)})+inputField('location','구조 대상 위치',{required:true,full:true,placeholder:'가상동·건물·층·호수'})+inputField('people_count','신고 인원',{type:'number',min:0,optional:true,help:'불명확하면 비워 두고 확인하세요.'})+inputField('channel','접수 채널',{value:'sms',options:Object.entries(channelLabels).filter(([v])=>v!=='field')})+inputField('text','신고 원문',{type:'textarea',required:true,full:true,rows:4})+inputField('summary','사건 요약',{type:'textarea',optional:true,full:true,rows:2})+actorField()+uploadField();
 if(kind==='report'||kind==='field-report')fields=`<p class="form-note">${closed?'완료 사건에 새 정보가 등록되면 확인 필요 상태로 다시 열립니다. 이전 결과는 이력에 보존됩니다.':'접수 인원 '+esc(count(i.people_count))+' / 현재 위치 '+esc(i.location)}</p>`+inputField('kind','등록 종류',{value:kind==='field-report'?'field':'additional',options:[['additional','추가 정보'],['field','현장 보고'],['correction','인원·위치 정정']]})+inputField('channel','정보 출처',{value:kind==='field-report'?'field':'sms',options:Object.entries(channelLabels)})+inputField('text','보고 원문',{type:'textarea',required:true,full:true,rows:4,help:'관찰한 사실과 미확인 사항을 구분해 기록하세요.'})+inputField('people_count','보고·정정 인원',{type:'number',min:0,optional:true,help:'현장 인원은 결과 확정 근거로 사용됩니다.'})+inputField('location','보고·정정 위치',{optional:true})+actorField()+uploadField();
 if(kind==='edit')fields=inputField('title','사건명',{value:i.title,required:true,full:true})+inputField('location','구조 대상 위치',{value:i.location,required:true,full:true})+inputField('people_count','접수 인원',{value:i.people_count??'',type:'number',min:0,optional:true})+inputField('priority','담당자 우선도',{value:i.priority,options:Object.entries(priorityLabels)})+inputField('reason','수정 이유',{type:'textarea',required:true,full:true,placeholder:'확인한 원문과 수정 사유를 기록하세요.'})+actorField()+`<p class="form-note">${closed?'완료된 사건의 인원·위치가 바뀌면 다시 확인 상태로 열립니다.':'기존 접수 원문을 바꾸지 않고 사건 정보의 변경 이력을 남깁니다.'}</p>`;
 if(kind==='progress'){
  const eligible=state.resources.filter(r=>r.status==='available'||r.incident_id===i.id),team=teamId||i.assigned_team_id||'';
  fields=inputField('status','진행 상태',{value:teamId?'dispatched':['dispatched','on_scene','rescuing','reviewing'].includes(i.status)?i.status:'dispatched',options:Object.entries(statusLabels).filter(([v])=>!['received','closed'].includes(v))})+inputField('team_id','담당팀',{value:team,options:[['',i.assigned_team_id?'현재 담당팀 유지':'미배정'],...eligible.map(r=>[r.id,`${r.name} (${r.crew_count}명 / ${r.status==='available'?'가용':'현재 담당'})`])]})+inputField('note','진행 내용',{type:'textarea',required:true,full:true,placeholder:'현장 도착·배정·구조 진행 내용을 기록하세요.'})+actorField()+`<p class="form-note">다른 사건에 배정된 팀은 선택할 수 없습니다. 구조 보고는 별도로 등록한 뒤 결과를 확인하세요.</p>`;
 }
 if(kind==='outcome'){
  const previous=(i.outcome_history||[]).at(-1);
  const reports=(i.reports||[]).filter(r=>{
   if(r.kind!=='field'&&r.channel!=='field')return false;
   if(Array.isArray(previous?.report_ids_at_reopen))return !previous.report_ids_at_reopen.includes(r.id);
   if(previous?.reopened_at)return new Date(r.received_at)>new Date(previous.reopened_at);
   return true;
  }).sort((a,b)=>new Date(b.received_at)-new Date(a.received_at));
  const eligible=reports.filter(r=>r.people_count===i.people_count),selected=eligible[0]?.id||'';
  modal.noBasis=reports.length===0;
  fields=(previous?.reopened_at?'<p class="form-note">재개 이후 새 현장 보고만 선택할 수 있습니다. 이전 근거는 원문과 변경 이력에서 확인하세요.</p>':'')+`<p class="form-note">현재 접수 인원 <strong>${esc(count(i.people_count))}</strong>. 현장 보고의 인원과 일치해야 완료할 수 있습니다.</p>`+inputField('outcome','확정 결과',{value:'rescued',options:Object.entries(outcomeLabels)})+inputField('confirmed_count','확인 인원',{type:'number',min:0,value:i.people_count??'',required:true})+inputField('basis_report_id','현장 근거 보고',{value:selected,required:true,full:true,options:[['','근거 현장 보고 선택'],...reports.map(r=>[r.id,`${r.id} / ${count(r.people_count)} / ${date(r.received_at)} ${String(r.text).slice(0,40)}`])]})+'<div id="basis-preview" class="basis-preview"></div>'+inputField('note','담당자 확인 내용',{type:'textarea',required:true,full:true,placeholder:'대상 요청·전체 인원·현장 근거를 어떻게 대조했는지 기록하세요.'})+actorField();
 }
 if(kind==='reopen')fields=`<p class="form-note">현재 결과: ${esc(outcomeLabels[i.outcome?.outcome]||'처리 완료')} / ${esc(count(i.outcome?.confirmed_count))}. 재개 후 새 현장 근거로 결과를 다시 확인하세요.</p>`+inputField('reason','재개·정정 이유',{type:'textarea',required:true,full:true,rows:4,placeholder:'새 정보 또는 잘못된 결과를 확인한 사유'})+actorField();
 $('dialog-save').disabled=Boolean(modal.noBasis);$('dialog-fields').innerHTML=fields;$('task-form').querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('input',()=>x.removeAttribute('aria-invalid')));
 $('task-dialog').showModal();const first=$('dialog-fields').querySelector('input,select,textarea');if(first)first.focus();
 if($('f-files'))$('f-files').addEventListener('change',onFiles);
 if(kind==='outcome'){$('f-basis_report_id').addEventListener('change',updateBasisPreview);updateBasisPreview();}
 if(kind==='report'||kind==='field-report')$('f-kind').addEventListener('change',()=>{if($('f-kind').value==='field')$('f-channel').value='field';});
}
function updateBasisPreview(){const r=(state.incident?.reports||[]).find(x=>x.id===$('f-basis_report_id').value);$('basis-preview').innerHTML=r?`<strong>${esc(r.actor)} / 확인 ${esc(count(r.people_count))}</strong><span>${esc(r.text)}</span>`:(modal?.noBasis?'<strong>새 현장 보고를 등록하세요.</strong><span>선택할 수 있는 현장 근거가 없습니다. 전체 인원과 대상 요청을 확인한 새 보고가 필요합니다.</span><div class="button-row"><button type="button" class="small" data-register-basis>현장 보고 등록</button></div>':'<strong>현장 근거를 선택하세요.</strong><span>현재 인원과 일치하는 현장 보고를 선택하고 전체 인원을 대조하세요.</span>');}
function closeTask(){if(modal?.busy)return;$('task-dialog').close();}
$('task-dialog').addEventListener('close',()=>{modal=null;$('task-form').reset();$('dialog-error').hidden=true;const focus=restoreFocus;if(focus?.isConnected)focus.focus();restoreFocus=null;});
$('task-dialog').addEventListener('cancel',e=>{if(modal?.busy)e.preventDefault();});
$('task-dialog').querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeTask));
function showFormError(message,field){const box=$('dialog-error');box.replaceChildren();box.textContent=message;box.hidden=false;if(field){field.setAttribute('aria-invalid','true');field.focus();}}
function onFiles(e){if(!modal)return;const files=[...e.target.files];const invalid=files.find(f=>f.size>(window.RescueCloud?.mode==='cloud'?3:8)*1024*1024||!(/\.(png|jpe?g|wav|mp3|mp4)$/i).test(f.name));if(invalid){showFormError(`${invalid.name}: PNG, JPG, WAV, MP3, MP4 파일을 ${window.RescueCloud?.mode==='cloud'?'3MiB':'8MiB'} 이하로 선택하세요.`,e.target);e.target.value='';return;}for(const f of files)if(!modal.pendingFiles.some(x=>x.name===f.name&&x.size===f.size)&&!modal.attachments.some(x=>x.filename===f.name))modal.pendingFiles.push(f);e.target.value='';renderUploads();}
function renderUploads(){const list=$('upload-list');if(!list||!modal)return;list.innerHTML=[...modal.attachments.map((a,n)=>`<div class="upload-item"><span>${esc(a.filename)} / 업로드 완료</span><button type="button" data-remove-upload="${n}" aria-label="${esc(a.filename)} 첨부 제거">제거</button></div>`),...modal.pendingFiles.map((f,n)=>`<div class="upload-item"><span>${esc(f.name)} / ${(f.size/1024).toFixed(0)}KB</span><button type="button" data-remove-file="${n}" aria-label="${esc(f.name)} 첨부 제거">제거</button></div>`)].join('');}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('첨부 파일을 읽지 못했습니다. 다시 선택하세요.'));reader.readAsDataURL(file);});}
async function uploadPending(){while(modal.pendingFiles.length){const file=modal.pendingFiles[0],data_base64=await fileBase64(file),type=file.type||({wav:'audio/wav',mp3:'audio/mpeg',mp4:'video/mp4',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg'}[file.name.split('.').pop().toLowerCase()]);const a=await api('/api/uploads',{method:'POST',body:{filename:file.name,content_type:type,data_base64}});modal.attachments.push(a);modal.pendingFiles.shift();renderUploads();}}
function setBusy(value){if(!modal)return;modal.busy=value;$('task-form').querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=value);if(!value)$('dialog-save').disabled=Boolean(modal.noBasis);$('dialog-save').textContent=value?'저장 중…':{new:'사건 접수',report:'정보 등록','field-report':'현장 보고 등록',edit:'수정 저장',progress:'진행 저장',outcome:'처리 결과 확정',reopen:'사건 재개'}[modal.kind];}
$('task-form').addEventListener('submit',async e=>{
 e.preventDefault();if(!modal||modal.busy)return;
 const form=$('task-form'),required=[...form.querySelectorAll('[required]')];for(const field of required){if(!field.value.trim()){showFormError(`${form.querySelector(`label[for="${field.id}"]`)?.textContent||'필수 항목'}을 입력하세요.`,field);return;}}
 for(const field of form.querySelectorAll('input[type=number]'))if(field.value!==''&&(!/^\d+$/.test(field.value)||!Number.isSafeInteger(Number(field.value)))){showFormError('인원은 0 이상의 정수로 입력하세요.',field);return;}
 const values=Object.fromEntries(new FormData(form));let body={actor:values.actor.trim()},path='/api/incidents',method='POST';const kind=modal.kind;
 if(kind==='new'){Object.assign(body,{title:values.title.trim(),location:values.location.trim(),category:values.category,priority:values.priority,channel:values.channel,text:values.text.trim(),summary:values.summary.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);}
 else {body.expected_revision=modal.revision;path+=`/${encodeURIComponent(modal.incidentId)}`;
  if(kind==='report'||kind==='field-report'){path+='/reports';Object.assign(body,{kind:values.kind,channel:values.channel,text:values.text.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);if(values.location.trim())body.location=values.location.trim();}
  if(kind==='edit'){method='PATCH';Object.assign(body,{title:values.title.trim(),location:values.location.trim(),priority:values.priority,reason:values.reason.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);}
  if(kind==='progress'){path+='/progress';Object.assign(body,{status:values.status,note:values.note.trim()});if(values.team_id)body.team_id=values.team_id;}
  if(kind==='outcome'){path+='/outcome';Object.assign(body,{outcome:values.outcome,confirmed_count:Number(values.confirmed_count),basis_report_id:values.basis_report_id,note:values.note.trim()});}
  if(kind==='reopen'){path+='/reopen';body.reason=values.reason.trim();}
 }
 $('dialog-error').hidden=true;setBusy(true);
 try {
  if(kind==='new'||kind==='report'||kind==='field-report'){await uploadPending();body.attachments=[...modal.attachments];}
  const updated=await api(path,{method,body});setBusy(false);$('task-dialog').close();
  state.incident=updated;try{await loadList();}catch(error){toast('업무는 저장됐지만 목록 갱신에 실패했습니다. 새로고침하세요.');}
  const target=incidentLink(updated);if(location.hash!==target)location.hash=target;else renderDetail();
  toast({new:'새 사건을 접수했습니다.',report:updated.status==='reviewing'?'추가 정보를 등록했습니다. 확인 필요 상태를 확인하세요.':'추가 정보를 등록했습니다.','field-report':'현장 보고를 등록했습니다.',edit:'사건 정보와 수정 이유를 저장했습니다.',progress:'담당팀과 현장 진행을 저장했습니다.',outcome:'근거를 대조한 처리 결과를 확정했습니다.',reopen:'사건을 재개했습니다. 이전 결과는 이력에 보존했습니다.'}[kind]);
 }catch(error){setBusy(false);showFormError(error.message);if(error.status===409){const b=document.createElement('button');b.type='button';b.textContent='최신 사건 정보 대조';b.addEventListener('click',async()=>{b.disabled=true;try{state.incident=await api(`/api/incidents/${encodeURIComponent(modal.incidentId)}`);modal.revision=state.incident.revision;await loadList();renderDetail();showFormError(`최신 정보를 불러왔습니다. 현재 접수 인원 ${count(state.incident.people_count)}, 상태 ${statusLabels[state.incident.status]}. 입력값을 확인하고 다시 저장하세요.`);}catch(err){showFormError(err.message);}finally{b.disabled=false;}});$('dialog-error').append(b);}}
});
function showImage(rid,index){const a=(state.incident?.reports||[]).find(r=>r.id===rid)?.attachments?.[index],url=a&&safeMedia(a.url);if(!url)return;restoreFocus=document.activeElement;$('media-title').textContent=a.filename||'첨부 사진';$('media-content').innerHTML=`<img src="${esc(url)}" alt="${esc(a.caption||'신고 첨부 사진')}"><p>${esc(a.caption||'')}</p>`;$('media-dialog').showModal();$('media-dialog').querySelector('[data-media-close]').focus();}
$('media-dialog').querySelector('[data-media-close]').addEventListener('click',()=>$('media-dialog').close());
$('media-dialog').addEventListener('close',()=>{$('media-content').replaceChildren();if(restoreFocus?.isConnected)restoreFocus.focus();restoreFocus=null;});
function openBackgroundIncident(event){
 if(event.defaultPrevented||event.button!==0||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;
 if(event.target.closest('a,button,input,select,textarea,summary,audio,video,label,[contenteditable],[data-no-navigation]'))return;
 if(window.getSelection()?.toString().trim())return;
 const surface=event.target.closest('[data-incident-surface]');
 const link=surface?.querySelector('[data-incident-link]');
 if(link)link.click();
}
function focusReport(id){state.detailTab='reports';state.reportTab='all';renderDetail();const r=document.getElementById(`report-${id}`);if(r){r.scrollIntoView({behavior:'auto',block:'start'});r.focus({preventScroll:true});}}
$('attention-strip').addEventListener('click',async e=>{const button=e.target.closest('button[data-attention-incident]');if(button)await openAttentionWork(button);else openBackgroundIncident(e);});
$('view').addEventListener('click',async e=>{
 const target=e.target.closest('button');if(!target){openBackgroundIncident(e);return;}
 if(target.dataset.attentionIncident){await openAttentionWork(target);return;}
 if(target.dataset.filter){state.filters.status=target.dataset.filter;updateTable();return;}
 if(target.dataset.detailTab){state.detailTab=target.dataset.detailTab;renderDetail();document.querySelector(`[data-detail-tab="${state.detailTab}"]`)?.focus();return;}
 if(target.dataset.reportTab){state.reportTab=target.dataset.reportTab;renderDetailContent();document.querySelector(`[data-report-tab="${state.reportTab}"]`)?.focus();return;}
 if(target.dataset.reportLink){focusReport(target.dataset.reportLink);return;}
 if(target.dataset.imageReport){showImage(target.dataset.imageReport,Number(target.dataset.imageIndex));return;}
 const action=target.dataset.action;if(!action)return;
 if(action==='ai-new'||action==='ai-report'){openAI(action==='ai-new'?null:state.incident);return;}
 if(action==='clear-filters'){state.filters={query:'',status:'all',channel:'all',priority:'all'};renderDashboard();return;}
 if(action==='assign-resource'){
  if(target.disabled)return;
  const teamId=target.dataset.resource,id=document.getElementById(`assign-${teamId}`).value;if(!id){toast('배정할 사건을 먼저 선택하세요.');return;}
  target.disabled=true;
  try{
   await loadList();
   const hash=`#incident/${encodeURIComponent(id)}`;if(location.hash!==hash)history.pushState(null,'',hash);
   await route(false);
   if(state.view!=='detail'||state.incident?.id!==id||!Number.isInteger(state.incident.revision))return;
   if(state.incident.status==='closed'){toast('이미 완료된 사건입니다. 최신 처리 결과를 확인하세요.');return;}
   const team=state.resources.find(r=>r.id===teamId);
   if(!team||(team.status!=='available'&&team.incident_id!==id)){toast('선택한 팀을 배정할 수 없습니다. 최신 대응 자원을 확인하세요.');return;}
   openTask('progress',{teamId});
  }catch(err){pageError(err.message);}finally{target.disabled=false;}return;
 }
 openTask(action);
});
$('dialog-fields').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!modal||modal.busy)return;if(b.hasAttribute('data-register-basis')){$('task-dialog').addEventListener('close',()=>openTask('field-report'),{once:true});closeTask();return;}if(b.dataset.removeFile!==undefined)modal.pendingFiles.splice(Number(b.dataset.removeFile),1);if(b.dataset.removeUpload!==undefined)modal.attachments.splice(Number(b.dataset.removeUpload),1);renderUploads();});
$('refresh').addEventListener('click',refresh);window.addEventListener('hashchange',()=>route().catch(e=>pageError(e.message)));
if(window.RescuePages)$('pages-notice').hidden=false;
(async()=>{try{await initializeWorkspace();}catch(error){pageError(error.message);renderDisconnected();}})();

$('view').addEventListener('keydown',e=>{if(!e.target.matches('[data-detail-tab]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();state.detailTab=e.key==='Home'?'reports':e.key==='End'?'history':state.detailTab==='reports'?'history':'reports';renderDetail();document.querySelector(`[data-detail-tab="${state.detailTab}"]`)?.focus();});

function renderConnection(){
 const cloud=window.RescueCloud,box=$('connection-status');if(!box||!cloud)return;box.hidden=false;
 const ai=cloud.config?.ai||{},labels={cloud:aiEnabled()?`공유 저장 연결 · ${providerLabel(ai.provider||'openai')} 서버 설정 연결`:'공유 저장 연결 · AI 분석 비활성 (담당자 직접 입력 가능)',local:'로컬 서버 연결 · SQLite 저장 · 이 서버는 AI 분석 미지원',unconfigured:'공유 저장·AI가 아직 설정되지 않았습니다.',unavailable:'서버 연결을 확인하지 못했습니다. 자동으로 합성 자료를 대신 표시하지 않습니다.'};
 box.innerHTML=`<strong class="connection-label">${esc(labels[cloud.mode]||'연결 확인 중')}</strong>${cloud.mode==='cloud'&&aiEnabled()?'<p>서버 설정이 연결되었습니다. 실제 분석 가능 여부는 각 작업의 성공·오류 상태를 확인하세요.</p>':''}<a href="#settings">설정 · AI 연결</a>${['unconfigured','unavailable'].includes(cloud.mode)?'<button type="button" id="browse-offline">합성 사례 둘러보기</button>':''}`;
 $('browse-offline')?.addEventListener('click',activateOffline);
}
function renderDisconnected(){if(!$('view'))return;$('view').innerHTML='<section class="panel service-intro"><h1>업무 서버 연결 확인</h1><p>공유 저장·AI 연결을 사용할 수 없습니다. 원문을 등록하려면 서버 설정과 연결을 확인하세요. 별도 합성 사례 둘러보기에서 브라우저에만 저장되는 사례를 체험할 수 있습니다.</p><p><a href="/guide/">이용법</a> · <a href="/judge/">심사 안내와 실행 범위</a></p></section>';renderConnection();}
async function activateOffline(){
 const button=$('browse-offline');if(button)button.disabled=true;
 try{const offline=window.RescuePagesOffline;if(!offline)throw new Error('합성 사례 어댑터를 불러오지 못했습니다.');window.RescuePages=typeof offline==='function'?offline():offline;$('pages-notice').hidden=false;$('connection-status').innerHTML='<strong>합성 사례 둘러보기 · 이 브라우저만 저장 · AI 분석 미지원</strong>';await loadList();await route(false);}catch(error){pageError(error.message);}finally{if(button?.isConnected)button.disabled=false;}
}
function renderField(){
 const list=state.incidents.filter(i=>i.status!=='closed');
 $('view').innerHTML=`<div class="page-head"><div><h1>현장 정보</h1><p>진행 사건을 선택해 추가 신고·사진·음성을 분석하고 인계할 정보를 검토합니다.</p></div></div><div class="resource-grid">${list.length?list.map(i=>`<section class="resource-card" data-incident-surface>${featuredBadge(i)}<h2><a href="${incidentLink(i)}" data-incident-link>${esc(i.title)}</a></h2><p>${esc(i.location)}</p><p>${statusBadge(i.status)} · ${esc(teamName(i.assigned_team_id))}</p><div class="button-row"><button type="button" data-ai-incident="${esc(i.id)}">추가 신고·현장 정보 AI 분석</button><button type="button" data-field-progress="${esc(i.id)}">담당팀·진행 수정</button><a href="${incidentLink(i)}">원문·진행 확인 →</a></div></section>`).join(''):'<div class="empty">진행 사건이 없습니다. 신규 접수 후 현장 정보를 등록하세요.</div>'}</div>`;
}
$('view').addEventListener('click',async e=>{const b=e.target.closest('[data-ai-incident],[data-field-progress]');if(!b)return;b.disabled=true;try{const id=b.dataset.aiIncident||b.dataset.fieldProgress;if(b.dataset.aiIncident&&!aiEnabled()){openAI();return;}if(b.dataset.fieldProgress){await loadList();history.pushState(null,'',`#incident/${encodeURIComponent(id)}`);await route(false);if(state.incident?.id===id)openTask('progress');}else{const i=await api('/api/incidents/'+encodeURIComponent(id));openAI(i);}}catch(error){pageError(error.message);}finally{b.disabled=false;}});
let aiState=null,aiStop=null,aiGeneration=0,aiRestoreFocus=null;
const AI_INPUT_KEY='rescue-ai-input-v1';
function storeAIInput(){if(!aiState)return;try{const formValues=Object.fromEntries(new FormData($('ai-form'))),values=aiState.draft?(aiState.draft.report||aiState.sourceValues||savedAIInput()?.values||{}):aiState.busy?(aiState.sourceValues||savedAIInput()?.values||{}):formValues;sessionStorage.setItem(AI_INPUT_KEY,JSON.stringify({incident_id:aiState.incidentId,expected_revision:aiState.revision,values,review_values:aiState.draft?.status==='ready'?(aiState.busy?savedAIInput()?.review_values||formValues:formValues):null,attachments:aiState.attachments,analysis_id:aiState.draft?.id||null}));}catch(_){}}
function savedAIInput(){try{return JSON.parse(sessionStorage.getItem(AI_INPUT_KEY)||'null');}catch(_){return null;}}
function aiError(message){const box=$('ai-error');box.textContent=message||'';box.hidden=!message;}
function renderDraftRecovery(){const id=window.RescueCloud?.remembered();if(!id||window.RescuePages)return;const box=$('connection-status');if(!box)return;const wrap=document.createElement('div');wrap.className='draft-recovery';wrap.innerHTML='<span>미등록 AI 초안이 있습니다. 원문과 분석 상태를 다시 확인할 수 있습니다.</span><button type="button">AI 초안 복구</button>';wrap.querySelector('span').textContent='미등록 AI 초안이 있습니다. 원문과 분석 상태를 다시 확인할 수 있습니다.';wrap.querySelector('button').addEventListener('click',()=>recoverAI(id));box.append(wrap);}
function openAI(incident=null,{recover=false}={}){
 if((!recover&&!aiEnabled())||window.RescueCloud?.mode!=='cloud'||window.RescuePages){toast('AI 연결 설정에서 로컬 Codex 시연 또는 서버 API 설정을 확인하세요. 담당자 직접 입력은 계속 사용할 수 있습니다.');location.hash='#settings';return;}
 const saved=savedAIInput(),match=saved&&saved.incident_id===(incident?.id||null);if(match&&saved.analysis_id&&!recover){recoverAI(saved.analysis_id);return;}aiStop?.();aiGeneration++;aiRestoreFocus=document.activeElement;
 aiState={sourceValues:match?saved.values||{}:{},incidentId:incident?.id||null,revision:incident?.revision??null,attachments:match?saved.attachments||[]:[],files:[],draft:null,busy:false,stale:false};
 $('ai-title').textContent=incident?'추가 신고·현장 정보 AI 분석':'신규 신고 AI 분석';aiError(null);$('ai-submit').hidden=false;$('ai-submit').disabled=false;$('ai-submit').textContent='AI 분석 시작';$('ai-retry').hidden=true;$('ai-retry').disabled=false;
 const v=match?saved.values||{}:{};
 $('ai-fields').innerHTML=`<p class="form-note">${incident?`${esc(incident.id)} · ${esc(incident.location)} · revision ${esc(incident.revision)}`:'신규 접수'} / ${esc(providerLabel(window.RescueCloud?.config?.ai?.provider||'openai'))} · AI는 분석 초안만 만들며, 등록 전 담당자 확인이 필요합니다.</p>`+inputField('channel','접수 채널',{value:v.channel||'sms',options:Object.entries(channelLabels)})+inputField('kind','보고 종류',{value:v.kind||(incident?'additional':'initial'),options:incident?[['additional','추가 신고'],['field','현장 정보']]:[['initial','최초 접수']]})+inputField('actor','담당자',{value:v.actor||'상황실 김담당',required:true})+inputField('text','신고·현장 원문',{value:v.text||'',type:'textarea',required:true,full:true,rows:5,help:'원문을 그대로 보존합니다. 실제 개인정보 없는 합성 자료만 입력하세요.'})+`<div class="field full"><label for="ai-files">사진·음성 첨부 (선택)</label><input id="ai-files" type="file" multiple accept="image/png,image/jpeg,audio/wav,audio/mpeg"><small>PNG/JPG/WAV/MP3 · 파일당 최대 3MiB · 영상 직접 분석 미지원. 이미 업로드한 첨부는 아래에 표시됩니다. 새로고침 전 업로드되지 않은 파일은 다시 선택해야 합니다.</small><div id="ai-uploads"></div></div>`;
 renderAIUploads();$('ai-dialog').showModal();$('ai-fields').querySelector('select,input,textarea')?.focus();$('ai-files').addEventListener('change',e=>{for(const file of e.target.files){if(file.size>3*1024*1024||!/\.(png|jpe?g|wav|mp3)$/i.test(file.name)){aiError(`${file.name}: 지원하는 사진·음성을 3MiB 이하로 선택하세요.`);continue;}aiState.files.push(file);}e.target.value='';renderAIUploads();storeAIInput();});if(!recover)storeAIInput();
}
function renderAIUploads(){const box=$('ai-uploads');if(!box||!aiState)return;box.innerHTML=aiState.attachments.map((a,n)=>`<div class="upload-item"><span>${esc(a.filename)} · 업로드 완료</span><button type="button" data-ai-remove="${n}" aria-label="${esc(a.filename)} 첨부 제거">제거</button></div>`).join('')+aiState.files.map(f=>`<p>${esc(f.name)} · 업로드 대기</p>`).join('');}
$('ai-fields').addEventListener('input',storeAIInput);
$('ai-fields').addEventListener('click',e=>{const b=e.target.closest('[data-ai-remove]');if(b&&!aiState?.busy){aiState.attachments.splice(Number(b.dataset.aiRemove),1);renderAIUploads();storeAIInput();}});
function stopAI(){storeAIInput();setAIBusy(false);aiStop?.();aiStop=null;aiGeneration++;$('ai-dialog').close();}
$('ai-dialog').querySelectorAll('[data-ai-close]').forEach(b=>b.addEventListener('click',stopAI));
$('ai-dialog').addEventListener('cancel',e=>{e.preventDefault();stopAI();});
$('ai-dialog').addEventListener('close',()=>{if($('ai-dialog').open)return;setAIBusy(false);aiStop?.();aiStop=null;aiGeneration++;if(aiRestoreFocus?.isConnected)aiRestoreFocus.focus();});
function setAIBusy(value){if(!aiState)return;aiState.busy=value;$('ai-fields').querySelectorAll('input,select,textarea,button').forEach(e=>e.disabled=value);$('ai-submit').disabled=value||!!aiState.stale;$('ai-retry').disabled=value;}
function aiStage(draft){setAIBusy(true);$('ai-fields').innerHTML=`<p class="ai-stage" role="status">${draft.status==='running'?'원문·첨부를 분석하고 있습니다.':'분석 작업이 접수되었습니다.'}<br>작업 ${esc(draft.id)} · 사건은 아직 변경되지 않았습니다. 취소하면 폴링이 멈추며 초안을 복구할 수 있습니다.</p><section class="ai-review-block"><h3>접수 원문</h3><p>${esc(draft.report?.text||savedAIInput()?.values?.text||'')}</p></section>`;$('ai-submit').hidden=true;$('ai-retry').hidden=true;}
async function beginAI(){
 if(!aiState||aiState.busy)return;const values=Object.fromEntries(new FormData($('ai-form')));if(!values.text?.trim()||!values.actor?.trim()){aiError('담당자와 신고 원문을 입력하세요.');return;}aiState.sourceValues=values;storeAIInput();const generation=aiGeneration;setAIBusy(true);aiError(null);
 try{const attachments=[...aiState.attachments];while(aiState.files.length){const file=aiState.files[0],data_base64=await fileBase64(file);if(generation!==aiGeneration)return;const ext=file.name.split('.').pop().toLowerCase(),content_type=file.type||({wav:'audio/wav',mp3:'audio/mpeg',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg'}[ext]);const a=await api('/api/uploads',{method:'POST',body:{filename:file.name,content_type,data_base64}});if(generation!==aiGeneration)return;attachments.push(a);aiState.attachments=attachments;aiState.files.shift();storeAIInput();renderAIUploads();}
 aiState.sourceValues=values;const payload={synthetic:true,incident_id:aiState.incidentId,expected_revision:aiState.revision,report:{channel:values.channel,kind:values.kind,actor:values.actor.trim(),text:values.text,attachments}};const draft=await window.RescueCloud.createAnalysis(payload);if(generation!==aiGeneration)return;aiState.draft=draft;storeAIInput();renderAIStatus(draft);if(['queued','running'].includes(draft.status))watchAI(draft.id,generation);
 }catch(error){if(generation!==aiGeneration)return;setAIBusy(false);aiError(error.message);}
}
function renderAIStatus(draft){
 if(draft.status==='ready')renderAIReview(draft);
 else if(draft.status==='failed')renderAIFailure(draft.error||'분석 실패 원인을 확인하세요.');
 else if(draft.status==='confirmed'){setAIBusy(false);$('ai-fields').innerHTML='<p class="ai-stage" role="status">담당자 확인이 이미 등록된 분석입니다. 사건 목록에서 원문과 등록 이력을 확인하세요.</p>';aiError(null);$('ai-submit').hidden=true;$('ai-retry').hidden=true;}
 else if(['queued','running'].includes(draft.status))aiStage(draft);
 else renderAIFailure('분석 상태를 확인하지 못했습니다.');
}
function watchAI(id,generation){aiStop=window.RescueCloud.startPolling(id,{onUpdate:draft=>{if(generation!==aiGeneration||!$('ai-dialog').open)return;aiState.draft=draft;renderAIStatus(draft);},onError:error=>{if(generation===aiGeneration&&$('ai-dialog').open)renderAIFailure(error.message);}});}
function renderAIFailure(message){
 setAIBusy(false);const report=aiState.draft?.report||aiState.sourceValues||savedAIInput()?.values||{},attachments=report.attachments||aiState.attachments||[];
 $('ai-fields').innerHTML=`<p class="ai-stage" role="status">분석을 완료하지 못했습니다. 원문으로 재분석을 눌러 입력을 수정하고 다시 시도할 수 있습니다.</p><section class="ai-review-block"><h3>보존된 신고 원문</h3><p>${esc(report.text||'')}</p><small>${esc(report.channel||'')} · ${esc(report.actor||'')}</small>${attachments.map(at=>{const u=safeMedia(at.url);return u?`<p><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(at.filename)} 원본 첨부 열기</a></p>`:'';}).join('')}</section>`;
 aiError(`${message} 원문은 보존되어 있습니다. 결과를 대신 생성하지 않았습니다.`);$('ai-submit').hidden=true;$('ai-retry').hidden=false;
}
async function recoverAI(id){const recoveryGeneration=++aiGeneration;aiStop?.();aiStop=null;try{const draft=await window.RescueCloud.getAnalysis(id);if(recoveryGeneration!==aiGeneration)return;const incident=draft.incident_id?await api('/api/incidents/'+encodeURIComponent(draft.incident_id)):null;if(recoveryGeneration!==aiGeneration)return;openAI(incident,{recover:true});if(!aiState||!$('ai-dialog').open)return;aiState.revision=draft.expected_revision;aiState.draft=draft;aiState.sourceValues=draft.report||aiState.sourceValues;aiState.attachments=draft.report?.attachments||[];aiState.stale=!!incident&&incident.revision!==draft.expected_revision;const generation=aiGeneration;renderAIStatus(draft);storeAIInput();if(['queued','running'].includes(draft.status))watchAI(id,generation);}catch(error){if(recoveryGeneration===aiGeneration){setAIBusy(false);pageError(error.message);}}}
const intakeNames={reporter:'신고자',location:'위치',situation:'상황',rescue:'요구조자',hazards:'위험 요인',review:'추가 확인'};
const intakeFieldNames={display_name:'합성 신고자 이름',reply_channel:'회신 채널',phone:'합성 연락처',relationship:'대상과 관계',address_landmark:'주소·랜드마크',floor_unit:'층·호수',access_point:'접근 지점',gps:'GPS (JSON)',source:'위치 출처',verification:'위치 확인 상태',category:'사건 분류',occurred_at:'발생 시각',summary:'상황 요약',people_count:'인원',injury:'부상',consciousness:'의식',breathing:'호흡',isolation:'고립',reported:'신고된 위험',observed:'관찰된 위험',unconfirmed:'미확인 위험',missing_information:'추가 확인할 정보',priority_warnings:'우선 확인 경고'};
function listAI(values){return Array.isArray(values)&&values.length?`<ul>${values.map(v=>`<li>${esc(typeof v==='string'?v:JSON.stringify(v))}</li>`).join('')}</ul>`:'<p class="muted">보고된 내용 없음 · 확인 필요</p>';}
function renderAIReview(draft){
 const a=draft.analysis;if(!a){renderAIFailure('완료된 분석 내용이 없습니다.');return;}const p=a.proposed_changes||{},original=state.incidents.find(i=>i.id===draft.incident_id)||{},changes={...original,...Object.fromEntries(Object.entries(p).filter(([,v])=>v!==null&&v!==undefined))};setAIBusy(false);$('ai-submit').hidden=false;$('ai-submit').disabled=aiState.stale;$('ai-submit').textContent='담당자 최종 확인 · 원자 등록';$('ai-retry').hidden=false;aiError(aiState.stale?'분석 후 사건이 변경되었습니다. 최신 사건을 확인하고 원문으로 재분석하세요.':null);
 let html=`<p class="ai-stage">AI 분석 초안 · 아직 미등록 · ${esc(draft.execution?.mode||'실행 정보 확인 필요')}  / ${esc(providerLabel(draft.execution?.provider))} / ${esc(draft.execution?.model||'모델 정보 없음')} / 실제 전사 ${esc(draft.execution?.asr_model||'실행 정보 없음')}<br>담당자가 원문·근거를 확인하고 수정합니다. 중복 후보·미확인 인원은 자동 병합·차감되지 않습니다.</p><section class="ai-review-block"><h3>보존된 신고 원문</h3><p>${esc(draft.report?.text)}</p><small>${esc(draft.report?.channel)} · ${esc(draft.report?.actor)}</small>${(draft.report?.attachments||[]).map(at=>{const u=safeMedia(at.url);return u?`<p><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(at.filename)} 원본 첨부 열기</a></p>`:'';}).join('')}</section><section class="ai-review-block"><h3>분석 요약</h3><p>${esc(a.summary)}</p></section>`;
 html+=inputField('title','확인할 사건명',{value:changes.title||'',required:!draft.incident_id,full:true})+inputField('category','사건 분류',{value:changes.category||'other',options:Object.entries(categoryLabels)})+inputField('priority','담당자 우선도',{value:changes.priority||'normal',options:Object.entries(priorityLabels)})+inputField('location','구조 대상 위치',{value:changes.location||'',required:!draft.incident_id,full:true})+inputField('people_count','확인할 인원',{value:changes.people_count??'',type:'number',min:0,optional:true})+inputField('summary','확인할 사건 요약',{value:changes.summary||a.summary||'',type:'textarea',full:true});
 html+='<section class="ai-review-block"><h3>119 접수 항목 추출 · 담당자 수정</h3><p>AI가 찾지 못한 값은 미확인입니다. 접수번호·접수시각·처리 상태는 서버 기록을 따릅니다.</p>';
 for(const [group,fields] of Object.entries(a.intake119||{})){html+=`<details><summary>${esc(intakeNames[group]||group)}</summary>`;for(const [key,value] of Object.entries(fields)){const name=`intake_${group}_${key}`,val=Array.isArray(value)?value.join('\n'):typeof value==='object'&&value!==null?JSON.stringify(value):value??'';html+=inputField(name,intakeFieldNames[key]||key,{value:val,type:Array.isArray(value)?'textarea':'text',optional:true,help:Array.isArray(value)?'한 줄에 한 항목':key==='gps'?'신고자 GPS를 대상 위치로 확정하지 마세요.':key==='verification'?'unverified — AI가 위치를 확정하지 않습니다.':''});}html+='</details>';}html+='</section>';
 html+=`<section class="ai-review-block"><h3>근거 · 출처</h3>${(a.evidence||[]).map(e=>`<blockquote><p>${esc(e.quote||e.observation||'')}</p><footer>${esc(e.field)} / ${esc(e.source_id)} / ${esc(e.type)}</footer></blockquote>`).join('')||'<p>근거가 없습니다. 추가 확인하세요.</p>'}</section><section class="ai-review-block"><h3>실제 음성 전사</h3>${(a.transcripts||[]).map(t=>`<p>${esc(t.text)}</p><small>${esc(t.attachment_id)} · ${esc(t.model)}</small>`).join('')||'<p>이 초안에 실제 전사 결과가 없습니다.</p>'}</section><section class="ai-review-block"><h3>중복 후보 · 동일인 가능성 (사람 확인)</h3>${(a.duplicate_candidates||[]).map(c=>`<p>${esc(c.incident_id)} / ${esc(c.report_id||'')} · ${esc(c.reason)}</p>`).join('')||'<p>중복 후보 없음</p>'}${(a.person_overlap||[]).map(o=>`<p>${esc(o.reason)}<br><small>출처 ${(o.source_ids||[]).map(esc).join(', ')} · 동일인 연결은 담당자 확인 필요</small></p>`).join('')}</section><section class="ai-review-block"><h3>미확인 인원</h3><p>${esc(count(a.remaining_people?.count))} · ${esc(a.remaining_people?.basis)}</p><p>인원을 자동 차감하거나 완료 처리하지 않습니다.</p><h3>원문 진위 확인 질문</h3><p>${esc(a.authenticity?.status||'unverified')} — 진실·허위 판정 없음</p>${listAI(a.authenticity?.signals)}${listAI(a.authenticity?.questions)}</section><section class="ai-review-block"><h3>현장 인계 메모</h3>${listAI(a.handoff)}<h3>추가 확인 · 시급한 이유</h3>${listAI(a.missing_information)}${listAI(a.urgent_reasons)}<h3>분석 한계</h3>${listAI(a.limitations)}</section>`;
 html+=inputField('actor','최종 확인 담당자',{value:draft.report?.actor||'상황실 김담당',required:true})+inputField('reason','확인·수정 근거',{type:'textarea',required:true,full:true,help:'원문·전사·관찰 근거와 수정한 이유를 기록하세요.'})+'<label class="field full ai-confirm-check"><input type="checkbox" name="reviewed" value="yes">원문·근거·미확인 사항을 검토했고 담당자 판단으로 등록합니다.</label>';
 $('ai-fields').innerHTML=html;const stored=savedAIInput();if(stored?.analysis_id===draft.id&&stored.review_values){for(const el of $('ai-fields').querySelectorAll('input,select,textarea')){if(!(el.name in stored.review_values))continue;if(el.type==='checkbox')el.checked=stored.review_values[el.name]==='yes';else el.value=stored.review_values[el.name];}}
}
function intakeChanges(values,original){const result=JSON.parse(JSON.stringify(original||{}));for(const [group,fields] of Object.entries(result))for(const [key,value] of Object.entries(fields)){const raw=values[`intake_${group}_${key}`]??'';if(key==='verification')result[group][key]='unverified';else if(Array.isArray(value))result[group][key]=raw.split('\n').map(s=>s.trim()).filter(Boolean);else if(key==='gps'){result[group][key]=raw.trim()?JSON.parse(raw):null;}else if(key==='people_count'){if(raw.trim()&&!/^\d+$/.test(raw))throw new Error('119 인원은 0 이상의 정수로 입력하세요.');result[group][key]=raw.trim()?Number(raw):null;}else result[group][key]=raw.trim()||null;}return result;}
async function confirmAI(){
 const values=Object.fromEntries(new FormData($('ai-form')));if(!values.actor?.trim()||!values.reason?.trim()||values.reviewed!=='yes'){aiError('최종 확인 담당자, 확인 근거와 검토 체크가 필요합니다.');return;}if(!aiState.draft.incident_id&&(!values.title?.trim()||!values.location?.trim())){aiError('신규 사건명과 구조 대상 위치를 확인하세요.');return;}if(values.people_count!==''&&!/^\d+$/.test(values.people_count)){aiError('인원은 0 이상의 정수로 입력하세요.');return;}
 const generation=aiGeneration;let changes;try{changes={title:values.title.trim(),location:values.location.trim(),category:values.category,priority:values.priority,summary:values.summary,people_count:values.people_count===''?null:Number(values.people_count),intake119:intakeChanges(values,aiState.draft.analysis.intake119)};}catch(error){aiError(error.message);return;}
 storeAIInput();aiError(null);setAIBusy(true);try{const result=await window.RescueCloud.confirm(aiState.draft.id,{synthetic:true,actor:values.actor.trim(),expected_revision:aiState.draft.expected_revision,reason:values.reason.trim(),changes});if(generation!==aiGeneration)return;setAIBusy(false);try{sessionStorage.removeItem(AI_INPUT_KEY);}catch(_){}aiStop?.();$('ai-dialog').close();try{await loadList();location.hash=incidentLink(result.incident);await route(false);}catch(refreshError){pageError('AI 확인은 저장됐습니다. 목록 연결을 다시 확인하세요. '+refreshError.message);}renderConnection();toast('원문·AI 초안·담당자 확인을 함께 등록했습니다. 진행·처리 결과는 별도 업무에서 확인하세요.');}catch(error){if(generation!==aiGeneration)return;setAIBusy(false);aiError(error.status===409?'분석 후 사건이 변경되었습니다. 입력과 원문은 보존했습니다. 최신 사건을 확인하고 재분석하세요.':error.message);if(error.status===409){aiState.stale=true;$('ai-submit').disabled=true;}}
}
$('ai-form').addEventListener('submit',e=>{e.preventDefault();if(!aiState||aiState.busy)return;if(aiState.draft?.status==='ready'&&!aiState.stale)confirmAI();else if(!aiState.draft)beginAI();});
$('ai-retry').addEventListener('click',async()=>{if(!aiState||aiState.busy)return;storeAIInput();const generation=aiGeneration,draft=aiState.draft,incidentId=draft?.incident_id||aiState.incidentId;setAIBusy(true);try{const incident=incidentId?await api('/api/incidents/'+encodeURIComponent(incidentId)):null;if(generation!==aiGeneration)return;try{sessionStorage.setItem(AI_INPUT_KEY,JSON.stringify({incident_id:incidentId,expected_revision:incident?.revision??null,values:draft?.report||aiState.sourceValues||savedAIInput()?.values||{},attachments:draft?.report?.attachments||aiState.attachments}));}catch(_){}aiStop?.();setAIBusy(false);$('ai-dialog').close();openAI(incident);}catch(error){if(generation===aiGeneration){setAIBusy(false);aiError(error.message);}}});
window.addEventListener('pagehide',()=>{storeAIInput();aiStop?.();});
function confirmedAIRecord(meta){const a=meta.analysis||{};return `<details class="transcript"><summary>등록된 AI 초안 · 담당자 확인 근거</summary><p>${esc(a.summary||'분석 요약 기록 없음')}</p><p>최종 확인: ${esc(meta.confirmed_by||'기록 확인 필요')} · ${esc(meta.confirmed_reason||'')}</p><small>분석 ${esc(meta.analysis_id||'')} / ${esc(meta.execution?.mode||'')} / ${esc(providerLabel(meta.execution?.provider))} / ${esc(meta.execution?.model||'모델 기록 없음')} / 실제 전사 ${esc(meta.execution?.asr_model||'실행 정보 없음')}</small>${(a.evidence||[]).map(e=>`<blockquote><p>${esc(e.quote||e.observation||'')}</p><small>${esc(e.source_id)} / ${esc(e.type)}</small></blockquote>`).join('')}${(a.transcripts||[]).map(t=>`<p>음성 전사: ${esc(t.text)}</p><small>${esc(t.attachment_id)} / ${esc(t.model)}</small>`).join('')}<p>인계 메모</p>${listAI(a.handoff)}<p>미확인 인원: ${esc(count(a.remaining_people?.count))} · ${esc(a.remaining_people?.basis||'확인 필요')}</p>${listAI(a.limitations)}</details>`;}
function confirmedIntake(i){if(!i.intake119)return '';return `<details class="panel confirmed-intake"><summary>담당자 확인 119 접수 항목</summary>${Object.entries(i.intake119).map(([group,fields])=>`<h3>${esc(intakeNames[group]||group)}</h3><dl>${Object.entries(fields).map(([key,value])=>`<div><dt>${esc(intakeFieldNames[key]||key)}</dt><dd>${esc(value===null?'미확인':Array.isArray(value)?value.join(', ')||'기록 없음':typeof value==='object'?`위도 ${value.latitude??'미확인'}, 경도 ${value.longitude??'미확인'}`:value)}</dd></div>`).join('')}</dl>`).join('')}<p class="operation-note">접수 시각과 처리 상태는 사건 기록을 따릅니다. 위치·인원·결과는 별도 확인이 필요합니다.</p></details>`;}
function aiEnabled(){const ai=window.RescueCloud?.config?.ai;return !!(ai?.enabled??ai?.configured)&&!window.RescuePages;}
function providerLabel(provider){return {codex_cli:'Codex CLI (ChatGPT 로그인)',openai:'OpenAI API',disabled:'AI 비활성'}[provider]||'제공자 확인 필요';}
let settingsToken=0;
function capabilityText(value,yes,no){return value===true?yes:value===false?no:'확인되지 않음';}
async function renderSettings(){
 const token=++settingsToken;$('view').innerHTML='<div class="loading" role="status">AI 연결 설정과 실행 지원 상태를 확인하고 있습니다.</div>';
 let settings,error=null;try{if(window.RescuePages)throw new Error('브라우저 합성 사례 모드입니다. 로컬 시연 서버에서 실행 상태를 확인하세요.');settings=await window.RescueCloud?.getSettings();if(!settings)throw new Error('설정 API가 제공되지 않습니다.');}catch(e){error=e.message;const ai=window.RescueCloud?.config?.ai||{};settings={provider:ai.provider||'disabled',local_demo:!!ai.local_demo,mutable:false,capabilities:{codex_cli:ai.login||{},openai:{configured:ai.configured&&ai.provider==='openai'},asr:ai.asr||{}}};}
 if(token!==settingsToken||state.view!=='settings')return;
 const caps=settings.capabilities||{},cli=caps.codex_cli||{},asr=caps.asr||{},isLocal=settings.local_demo===true,mutable=isLocal&&settings.mutable===true;
 $('view').innerHTML=`<div class="page-head"><div><h1>설정 · AI 연결</h1><p>현재 선택된 분석 제공자는 ${esc(providerLabel(settings.provider))}입니다. 실제 분석 성공은 작업별 상태에서 확인합니다.</p></div><button type="button" id="settings-refresh">연결 상태 다시 확인</button></div>${error?`<p class="ai-stage ai-state-failed" role="status">${esc(error)}</p>`:''}<div class="settings-grid"><section class="panel service-intro"><h2>현재 실행 방식</h2><dl class="settings-facts"><div><dt>분석 제공자</dt><dd>${esc(providerLabel(settings.provider))}</dd></div><div><dt>서버 위치</dt><dd>${isLocal?'로컬 시연 · 같은 출처 loopback 서버':'공개 서비스 · 서버 API 설정 후 선택 활성화'}</dd></div><div><dt>Codex CLI 설치</dt><dd>${esc(capabilityText(cli.installed,'설치 확인','미설치'))}</dd></div><div><dt>ChatGPT CLI 로그인</dt><dd>${esc(capabilityText(cli.logged_in,'CLI 로그인 확인','로그인 필요'))}${cli.login_status?` · ${esc(cli.login_status)}`:''}</dd></div><div><dt>음성 전사</dt><dd>${esc(capabilityText(asr.available,'전사 설정 연결','로컬 전사 미설치·미지원'))}${asr.provider?` · ${esc(asr.provider)}`:''}${asr.model?` / ${esc(asr.model)}`:''}</dd></div><div><dt>OpenAI API 설정</dt><dd>${esc(capabilityText(caps.openai?.configured,'서버 key/model 설정 존재 (실제 성공 확인 필요)','서버 설정 없음 · 나중 설정'))}</dd></div></dl><p class="operation-note">로그인과 모델 실행은 별개입니다. CLI는 현재 사용자의 모델 설정을 상속합니다. 기존 초안의 실제 제공자·전사 기록은 설정 변경 뒤에도 유지됩니다.</p>${mutable?`<form id="provider-form" class="settings-provider"><label for="settings-provider">다음 분석에 사용할 제공자</label><select id="settings-provider" name="provider">${['codex_cli','openai','disabled'].map(p=>`<option value="${p}"${p===settings.provider?' selected':''}>${esc(providerLabel(p))}</option>`).join('')}</select><button type="submit" class="primary">로컬 제공자 변경</button><p id="provider-status" role="status" aria-live="polite"></p></form>`:'<p class="form-note">공개 사이트에서는 분석 제공자나 서버 키를 변경할 수 없습니다. AI 없이 담당자 직접 입력으로 업무를 등록할 수 있습니다.</p>'}</section><section class="panel service-intro"><h2>로컬 Codex 시연 열기</h2><p>별도 로컬 서버를 직접 실행한 뒤 엽니다. 공개 사이트에서 로컬 서버를 자동 호출하지 않습니다.</p><a class="settings-demo-link" href="http://127.0.0.1:8769/#settings" target="_blank" rel="noopener noreferrer">로컬 시연 열기 · 127.0.0.1:8769 ↗</a><h3>CLI 설치 · ChatGPT 로그인</h3><pre class="settings-command">npm install -g @openai/codex
codex login
codex login status</pre><p>Codex CLI의 ChatGPT 로그인을 사용합니다. 로그인 토큰을 앱이나 클라우드로 복사하지 않습니다.</p><h3>프로젝트에서 로컬 서버 시작</h3><pre class="settings-command">python3 -B scripts/build_pages.py --output dist/cloud --mode cloud
node scripts/serve_codex_demo.mjs --static dist/cloud</pre><p>Node.js 22 이상, Supabase 서버 환경 설정이 필요합니다. 안전한 메모리 환경 전달과 설치 절차는 <a href="/guide/">이용법</a>과 <a href="https://github.com/namojo/codexhack2026/blob/main/docs/ai-setup.md" target="_blank" rel="noopener noreferrer">저장소 실행 안내 ↗</a>에서 확인하세요.</p></section><section class="panel service-intro"><h2>OpenAI API 서버 설정</h2><p>관리자가 서버 환경변수 OPENAI_API_KEY와 OPENAI_MODEL을 설정하고 AI_PROVIDER=openai로 활성화합니다. 초기 설정은 AI_PROVIDER=disabled이며, 관리자가 검증 후 활성화한 현재 제공자는 위 실행 방식에 표시됩니다.</p><p>키값을 입력하거나 브라우저·DB에 저장하는 기능은 제공하지 않습니다. 로컬 제공자 변경은 이미 서버에 있는 설정만 선택합니다. 할당량·잔액·네트워크 오류는 각 분석 작업에 그대로 표시합니다.</p></section><section class="panel service-intro"><h2>음성·사진 분석 범위</h2><p>Codex CLI를 선택하면 사진의 실제 PNG/JPG 바이트를 전달합니다. 음성은 설치된 로컬 Whisper가 실제 WAV/MP3를 전사한 후 텍스트를 Codex에 전달합니다.</p><p>Codex가 음성을 직접 들었다고 표시하지 않습니다. 전사가 미설치되면 실패·미지원 상태를 보여주며, 담당자가 입력한 전사는 신고 원문으로 구분합니다. 합성 대본을 실제 ASR 결과로 대신 표시하지 않습니다. 영상 직접 분석은 미지원입니다.</p><p>API 제공자를 선택한 경우 실제 OpenAI 전사 모듈을 사용합니다. 실행된 제공자·ASR 모델과 분석 한계는 초안과 등록 이력에 남습니다.</p></section></div>`;
 $('settings-refresh').addEventListener('click',async()=>{try{await window.RescueCloud?.boot();renderConnection();await renderSettings();}catch(e){pageError(e.message);}});
 $('provider-form')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button'),status=$('provider-status');button.disabled=true;try{await window.RescueCloud.setProvider($('settings-provider').value);renderConnection();await renderSettings();toast('다음 분석의 제공자를 변경했습니다. 기존 초안은 원래 실행 기록을 유지합니다.');}catch(e){status.textContent=e.message;}finally{if(button.isConnected)button.disabled=false;}});
}
