'use strict';
const $ = id => document.getElementById(id);
const statusLabels = {received:'접수',dispatched:'출동',on_scene:'현장 도착',rescuing:'구조 진행',reviewing:'확인 필요',closed:'처리 완료'};
const channelLabels = {voice:'음성 신고',sms:'문자',mms:'사진·영상',app:'앱 신고',video_call:'영상통화',web:'인터넷',field:'현장 보고'};
const categoryLabels = {flood:'침수·고립',fire:'화재',rescue:'구조',medical:'구급',other:'기타'};
const priorityLabels = {urgent:'긴급',high:'높음',normal:'보통'};
const outcomeLabels = {rescued:'구조 완료',self_evacuated:'자력 대피 확인',transferred:'다른 팀 인계'};
const kindLabels = {initial:'최초 접수',additional:'추가 정보',field:'현장 보고',correction:'인원·위치 정정'};
const actionLabels = {incident_updated:'사건 수정',progress_added:'진행 변경',progress_changed:'진행 변경',outcome_confirmed:'처리 결과 확정',incident_reopened:'완료 사건 재개',create:'사건 접수',created:'사건 접수',report:'보고 등록',report_added:'보고 등록',add_report:'보고 등록',update:'사건 수정',updated:'사건 수정',edit:'사건 수정',progress:'진행 변경',outcome:'처리 결과 확정',reopen:'완료 사건 재개',auto_reopen:'새 정보로 재개'};
const fieldLabels = {title:'사건명',location:'위치',people_count:'인원',priority:'우선도',status:'진행 상태',assigned_team_id:'담당팀',summary:'요약',outcome:'처리 결과'};
const state = {incidents:[],resources:[],incident:null,view:'dashboard',filters:{query:'',status:'all',channel:'all',priority:'all'},reportTab:'all',detailTab:'reports',loading:false};
let toastTimer, loadToken=0, modal=null, restoreFocus=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function date(v,full=false){if(!v)return '기록 없음';const d=new Date(v);if(Number.isNaN(d.valueOf()))return String(v);return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',...(full?{month:'2-digit',day:'2-digit'}:{}),hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function count(v){return v===null||v===undefined?'확인 필요':`${v}명`;}
function teamName(id){return state.resources.find(r=>r.id===id)?.name||'미배정';}
function statusBadge(s){return `<span class="status ${esc(s)}">${esc(statusLabels[s]||s)}</span>`;}
function priorityBadge(p){return `<span class="priority ${esc(p)}">${esc(priorityLabels[p]||p)}</span>`;}
function incidentLink(i){return `#incident/${encodeURIComponent(i.id)}`;}
function notices(i){return (i.checks||[]).filter(c=>c.level==='warning');}
const attentionLevels={immediate:'즉시 확인',decision:'판단 필요',follow_up:'후속 확인'};
const attentionOrder={immediate:0,decision:1,follow_up:2};
const operatorOrder={urgent:0,high:1,normal:2};
function tasks(i){return i.status==='closed'?[]:[...(i.attention||[])].sort((a,b)=>(attentionOrder[a.level]??3)-(attentionOrder[b.level]??3));}
function actionOrder(a,b){return (attentionOrder[tasks(a)[0]?.level]??3)-(attentionOrder[tasks(b)[0]?.level]??3)||(operatorOrder[a.priority]??3)-(operatorOrder[b.priority]??3)||new Date(a.created_at)-new Date(b.created_at)||String(a.id).localeCompare(String(b.id));}
function attentionIncidents(){return state.incidents.filter(i=>tasks(i).length).sort(actionOrder);}
function taskBadge(t){return `<span class="attention-level ${esc(t.level)}">${esc(attentionLevels[t.level]||'확인 필요')}</span>`;}
function renderAttentionStrip(){
 const targets=attentionIncidents(),top=targets[0],task=top&&tasks(top)[0],immediate=targets.filter(i=>tasks(i)[0].level==='immediate').length,decision=targets.filter(i=>tasks(i)[0].level==='decision').length;
 $('attention-nav-count').textContent=targets.length;
 const box=$('attention-strip');box.hidden=false;box.className=`attention-strip ${esc(task?.level||'clear')}`;
 box.innerHTML=`<div class="attention-strip-counts"><span class="strip-label">현재 미처리 사건 알림</span><div><strong>즉시 확인 ${immediate}건</strong><span>판단 필요 ${decision}건</span>${targets.length?`<span>전체 대상 ${targets.length}건</span>`:''}</div></div>${top?`<div class="attention-strip-top" data-incident-surface><span class="strip-label">최우선 확인 · ${esc(attentionLevels[task.level])}</span><a href="${incidentLink(top)}" data-incident-link>${esc(top.title)} <small>${esc(top.id)}</small></a><p>${esc(task.reason)}</p></div><a class="strip-open" href="#attention">전체 판단·조치 보기 →</a>`:'<p class="strip-clear">현재 판단·조치 과제가 없습니다.</p>'}`;
}
function attentionTask(i,t){return `<article class="attention-task ${esc(t.level)}"><div class="attention-task-head">${taskBadge(t)}<span class="rule-label">규칙 기반 권고 · 담당자 판단 필요</span></div><h3>${esc(t.title)}</h3><dl class="attention-explanation"><div><dt>현재 상황</dt><dd>${esc(t.situation)}</dd></div><div><dt>확인이 시급한 이유</dt><dd>${esc(t.reason)}</dd></div></dl><div class="attention-evidence">${(t.evidence||[]).length?t.evidence.map(e=>`<blockquote><p>“${esc(e.quote)}”</p><footer><span>접수 ${esc(date(e.received_at,true))}</span><button type="button" class="link-button" data-attention-incident="${esc(i.id)}" data-attention-report="${esc(e.report_id)}" aria-label="${esc(e.report_id)} 원문 보기">원문 보기 →</button></footer></blockquote>`).join(''):'<p class="attention-no-evidence">인용할 신고 원문이 없습니다. 담당자가 현재 사건 정보를 확인하세요.</p>'}</div><div class="attention-next"><span class="strip-label">다음 업무</span><p>${esc(t.next_action)}</p><button type="button" data-attention-incident="${esc(i.id)}" data-attention-action="${esc(t.action)}">${esc({progress:'담당팀·진행 확인', 'field-report':'현장 보고 등록',report:'추가 정보 확인·등록',edit:'사건 정보 대조·수정'}[t.action]||'사건 확인')} →</button></div></article>`;}
function attentionCard(i,{allTasks=false}={}){const list=tasks(i);return `<section class="attention-card"${allTasks?'':' data-incident-surface'}><div class="attention-card-head"><span class="incident-id">${esc(i.id)}</span><h2>${allTasks?`<span>${esc(i.title)}</span>`:`<a href="${incidentLink(i)}" data-incident-link>${esc(i.title)}</a>`}</h2><p>${esc(i.location)}</p><div class="attention-context">${statusBadge(i.status)}<span>${esc(teamName(i.assigned_team_id))}</span><span class="operator-priority">담당자 우선도 ${priorityBadge(i.priority)}</span></div></div>${(allTasks?list:list.slice(0,1)).map(t=>attentionTask(i,t)).join('')}${!allTasks&&list.length>1?`<a class="attention-more" href="${incidentLink(i)}" tabindex="-1">이 사건의 판단 과제 ${list.length}개 모두 보기 →</a>`:''}</section>`;}
function attentionSection({detail=false}={}){
 const targets=detail?(tasks(state.incident).length?[state.incident]:[]):attentionIncidents(),all=state.view==='attention'||detail,shown=all?targets:targets.slice(0,3);
 return `<section class="attention-section" aria-label="${detail?'이 사건의 판단·조치':'우선 판단·조치 사건'}"><div class="attention-section-head"><div><h2>${detail?'이 사건의 판단·조치':'지금 판단·조치할 사건'} <span>${detail?tasks(state.incident).length:targets.length}${detail?'개 과제':'건'}</span></h2><p>${detail?'현재 확인할 과제와 원문 근거를 대조하고 다음 업무를 기록하세요.':'즉시 확인 → 판단 필요 → 후속 확인 순. 같은 단계에서는 담당자 우선도와 접수 순으로 표시합니다.'}</p></div>${all?'':`<a href="#attention">전체 ${targets.length}건 보기 →</a>`}</div>${shown.length?`<div class="attention-grid ${detail?'detail-attention':all?'all-attention':''}">${shown.map(i=>attentionCard(i,{allTasks:detail})).join('')}</div>`:'<div class="attention-empty"><strong>현재 판단·조치 과제가 없습니다.</strong><p>새 보고 또는 사건 변경 후 최신 과제가 표시됩니다.</p></div>'}</section>`;
}
function renderAttention(){ $('view').innerHTML=`<div class="page-head"><div><h1>지금 판단·조치</h1><p>담당자 판단이 필요한 현재 미처리 사건과 다음 업무를 확인합니다.</p></div><button type="button" class="primary" data-action="new">＋ 신규 사건 접수</button></div>${attentionSection()}`; }
async function openAttentionWork(button){
 const id=button.dataset.attentionIncident,action=button.dataset.attentionAction,reportId=button.dataset.attentionReport;
 if(action&&!['progress','field-report','report','edit'].includes(action))return;
 button.disabled=true;
 try{
  await loadList();
  const hash=`#incident/${encodeURIComponent(id)}`;if(location.hash!==hash)history.pushState(null,'',hash);
  await route(false);
  if(state.incident?.id!==id||state.view!=='detail')return;
  if(reportId)focusReport(reportId);else if(state.incident.status==='closed')toast('이미 완료된 사건입니다. 최신 처리 결과를 확인하세요.');else openTask(action);
 }catch(error){pageError(error.message);}finally{button.disabled=false;}
}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
async function api(path,{method='GET',body}={}){
 if(window.RescuePages)return window.RescuePages.request(path,{method,body});
 const response=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});
 let data;try{data=await response.json();}catch(_){throw new Error('서버 응답을 읽지 못했습니다. 연결 상태를 확인하세요.');}
 if(!response.ok){const error=new Error(data.error||'정보를 저장하지 못했습니다. 다시 확인하세요.');error.status=response.status;throw error;}return data;
}
function pageError(message){const box=$('page-error');box.replaceChildren();box.hidden=!message;if(message){const span=document.createElement('span');span.textContent=message;const retry=document.createElement('button');retry.type='button';retry.textContent='다시 불러오기';retry.className='small';retry.addEventListener('click',()=>refresh());box.append(span,retry);}}
async function loadList(){const d=await api('/api/incidents');if(!Array.isArray(d.incidents)||!Array.isArray(d.resources))throw new Error('사건 목록 형식을 확인할 수 없습니다.');state.incidents=d.incidents;state.resources=d.resources;$('active-nav-count').textContent=d.incidents.filter(i=>i.status!=='closed').length;$('refreshed-at').textContent=`${date(new Date().toISOString())} 갱신`;renderAttentionStrip();}
async function refresh(){const b=$('refresh');b.disabled=true;try{await loadList();await route(false);pageError(null);toast('최신 사건 정보를 불러왔습니다.');}catch(e){pageError(e.message);}finally{b.disabled=false;}}
function routeTarget(){const h=location.hash.slice(1)||'dashboard';if(h.startsWith('incident/'))return {view:'detail',id:decodeURIComponent(h.slice(9))};return {view:['dashboard','attention','active','results','resources'].includes(h)?h:'dashboard'};}
async function route(focus=true){
 const token=++loadToken;const target=routeTarget();state.view=target.view;document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===target.view||(target.view==='detail'&&a.dataset.nav==='active');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});pageError(null);
 if(target.view==='detail'){
  state.incident=null;
  $('view').innerHTML='<div class="loading">사건 원문과 진행 기록을 불러오고 있습니다.</div>';
  try{const i=await api(`/api/incidents/${encodeURIComponent(target.id)}`);if(token!==loadToken)return;state.incident=i;state.incidents=state.incidents.map(existing=>existing.id===i.id?i:existing);renderAttentionStrip();state.detailTab='reports';state.reportTab='all';renderDetail();}catch(e){if(token!==loadToken)return;pageError(e.message);$('view').innerHTML='<div class="empty"><strong>사건을 열 수 없습니다.</strong><a href="#dashboard">사건 목록으로 돌아가기</a></div>';}
 }else {state.incident=null;if(target.view==='resources')renderResources();else if(target.view==='attention')renderAttention();else renderDashboard();}
 if(focus){$('workspace').focus({preventScroll:true});window.scrollTo(0,0);}
}
function statSummary(){const open=state.incidents.filter(i=>i.status!=='closed'),review=open.filter(i=>tasks(i).length),closed=state.incidents.filter(i=>i.status==='closed'),available=state.resources.filter(r=>r.status==='available');return `<div class="stats" aria-label="업무 요약"><div class="stat"><span class="stat-label">미처리 사건</span><span class="stat-number">${open.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">판단·조치 대상</span><span class="stat-number warning">${review.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">처리 완료</span><span class="stat-number done">${closed.length}<small> 건</small></span></div><div class="stat"><span class="stat-label">가용 대응팀</span><span class="stat-number">${available.length}<small> 팀</small></span></div></div>`;}
function optionList(labels,selected,allLabel){return `${allLabel?`<option value="all">${esc(allLabel)}</option>`:''}${Object.entries(labels).map(([v,l])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(l)}</option>`).join('')}`;}
function renderDashboard(){
 const title=state.view==='results'?'처리 결과':state.view==='active'?'진행 사건':'상황 대시보드';
 const desc=state.view==='results'?'담당자 확인 결과와 이전 처리 이력을 조회합니다.':state.view==='active'?'접수부터 현장 진행까지, 남아 있는 사건을 확인합니다.':'접수 현황과 현장 진행을 대조하고, 다음 인계를 준비합니다.';
 $('view').innerHTML=`<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><button type="button" class="primary" data-action="new">＋ 신규 사건 접수</button></div>${statSummary()}${state.view==='results'?'':attentionSection()}<div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>${state.view==='results'?'완료 사건 목록':'사건 목록'}</h2><small>${state.view==='results'?'최근 변경 순':'판단·조치 순'}</small></div><div class="filters"><div class="filter-row"><div class="search-wrap"><label for="incident-search"><span aria-hidden="true">⌕</span><span class="sr-only">사건 검색</span></label><input id="incident-search" type="search" placeholder="사건번호, 신고 내용, 위치 검색" value="${esc(state.filters.query)}"></div><label class="sr-only" for="channel-filter">접수 채널 필터</label><select id="channel-filter" class="filter-select">${optionList(channelLabels,state.filters.channel,'모든 채널')}</select><label class="sr-only" for="priority-filter">우선도 필터</label><select id="priority-filter" class="filter-select">${optionList(priorityLabels,state.filters.priority,'모든 우선도')}</select></div><div class="filter-row">${[['all','전체'],['unresolved','미처리'],['review','확인 필요'],['closed','처리 완료']].map(([v,l])=>`<button type="button" class="filter-chip ${state.filters.status===v?'active':''}" data-filter="${v}" aria-pressed="${state.filters.status===v}">${l}</button>`).join('')}<span class="filter-count" id="filtered-count"></span><button type="button" class="link-button" data-action="clear-filters">필터 초기화</button></div></div><div class="table-container"><table><thead><tr><th scope="col">사건 / 핵심 판단 과제</th><th scope="col">위치 / 인원</th><th scope="col">신고 채널</th><th scope="col">담당자 우선도</th><th scope="col">진행 상태</th><th scope="col">담당팀</th><th scope="col">최근 변경</th></tr></thead><tbody id="incident-rows"></tbody></table></div><div class="table-foot"><span id="table-total"></span><span>사건을 선택하면 원문과 처리 이력을 볼 수 있습니다.</span></div></section><aside class="side-stack" aria-label="자원과 인계 확인">${resourcePanel()}${handoffPanel()}</aside></div>`;
 updateTable();$('incident-search').addEventListener('input',e=>{state.filters.query=e.target.value;updateTable();});$('channel-filter').addEventListener('change',e=>{state.filters.channel=e.target.value;updateTable();});$('priority-filter').addEventListener('change',e=>{state.filters.priority=e.target.value;updateTable();});
}
function visibleIncidents(){const f=state.filters,q=f.query.trim().toLocaleLowerCase();return state.incidents.filter(i=>{
 if(state.view==='results'&&i.status!=='closed'||state.view==='active'&&i.status==='closed')return false;
 if(f.status==='unresolved'&&i.status==='closed'||f.status==='closed'&&i.status!=='closed'||f.status==='review'&&!tasks(i).length)return false;
 if(f.channel!=='all'&&!(i.reports||[]).some(r=>r.channel===f.channel))return false;
 if(f.priority!=='all'&&i.priority!==f.priority)return false;
 if(q&&![i.id,i.title,i.location,i.summary,...(i.reports||[]).map(r=>r.text)].join(' ').toLocaleLowerCase().includes(q))return false;return true;
 }).sort(state.view==='results'?((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)):actionOrder);}
function updateTable(){const rows=visibleIncidents();$('filtered-count').textContent=`${rows.length}건`;$('table-total').textContent=`조회 ${rows.length}건 / 전체 ${state.incidents.length}건`;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===state.filters.status);b.setAttribute('aria-pressed',b.dataset.filter===state.filters.status);});$('incident-rows').innerHTML=rows.length?rows.map(i=>`<tr data-incident-surface><td class="incident-cell"><a class="incident-link" href="${incidentLink(i)}" data-incident-link>${esc(i.title)}</a><span class="incident-id">${esc(i.id)}</span>${tasks(i).length?`<span class="table-attention ${esc(tasks(i)[0].level)}">${esc(attentionLevels[tasks(i)[0].level])} · ${esc(tasks(i)[0].title)}</span>`:''}</td><td class="location-cell">${esc(i.location)}<small>${esc(count(i.people_count))}</small></td><td class="channel-cell">${esc([...new Set((i.reports||[]).map(r=>channelLabels[r.channel]||r.channel))].join(', '))}</td><td>${priorityBadge(i.priority)}</td><td>${statusBadge(i.status)}</td><td class="channel-cell">${esc(teamName(i.assigned_team_id))}</td><td class="cell-time">${esc(date(i.updated_at,true))}</td></tr>`).join(''):`<tr><td colspan="7"><div class="empty"><strong>조회 조건에 맞는 사건이 없습니다.</strong>검색어와 필터를 변경하거나 새 사건을 접수하세요.</div></td></tr>`;}
function resourcePanel(){const available=state.resources.filter(r=>r.status==='available');return `<section class="panel"><div class="panel-head"><h2>대응 자원</h2><a href="#resources" class="muted">전체 보기</a></div><div class="side-body">${state.resources.slice(0,5).map(r=>`<div class="resource-row"><div><strong>${esc(r.name)}</strong><small>${esc(r.type)} / ${r.crew_count}명</small></div><span class="${r.status==='available'?'available':'assigned'}">${r.status==='available'?'가용':'배정 중'}</span></div>`).join('')||'<p class="empty">등록된 대응팀이 없습니다.</p>'}<p class="operation-note">가용 ${available.length}팀 / 전체 ${state.resources.length}팀</p></div></section>`;}
function handoffPanel(){const targets=attentionIncidents().slice(0,4);return `<section class="panel"><div class="panel-head"><h2>판단·조치 요약</h2><a href="#attention" class="muted">전체 보기</a></div><div class="side-body">${targets.length?targets.map(i=>`<a class="handoff-link" href="${incidentLink(i)}"><span class="incident-id">${esc(i.id)}</span><strong>${esc(i.title)}</strong><small>${esc(tasks(i)[0].title)}</small></a>`).join(''):'<p class="empty">현재 판단·조치 과제가 없습니다.</p>'}</div></section>`;}
function renderResources(){
 $('view').innerHTML=`<div class="page-head"><div><h1>대응 자원</h1><p>가용팀을 확인하고 진행 중인 사건에 배정합니다.</p></div><a href="#active">진행 사건 보기</a></div>${statSummary()}<div class="resource-grid">${state.resources.map(r=>{const i=state.incidents.find(x=>x.id===r.incident_id);return `<section class="resource-card"${i?' data-incident-surface':''}><span class="${r.status==='available'?'available':'assigned'}">${r.status==='available'?'배정 가능':'사건 대응 중'}</span><h2>${esc(r.name)}</h2><span class="resource-type">${esc(r.type)} / 대원 ${r.crew_count}명</span><p>${i?esc(i.title)+'<br>'+esc(i.location):'새로운 사건에 배정할 수 있습니다.'}</p>${i?`<div class="button-row"><a href="${incidentLink(i)}" data-incident-link aria-label="${esc(r.name)} 배정 사건 ${esc(i.title)} 열기">배정 사건 열기</a>${statusBadge(i.status)}</div>`:`<label class="sr-only" for="assign-${esc(r.id)}">${esc(r.name)} 배정할 사건</label><select id="assign-${esc(r.id)}"><option value="">배정할 사건 선택</option>${state.incidents.filter(x=>x.status!=='closed').map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')}</select><div class="button-row"><button type="button" class="small" data-action="assign-resource" data-resource="${esc(r.id)}">팀 배정</button></div>`}</section>`;}).join('')||'<div class="empty">등록된 대응 자원이 없습니다.</div>'}</div>`;
}
function renderDetail(){const i=state.incident;if(!i)return;const closed=i.status==='closed';
 $('view').innerHTML=`<div class="page-head"><div><div class="page-meta"><a href="#${closed?'results':'active'}">‹ 사건 목록</a><span>/</span><span>${esc(i.id)}</span><span>${esc(categoryLabels[i.category]||i.category)}</span></div><h1>${esc(i.title)}</h1><p>${esc(i.summary||'접수 원문과 최신 현장 정보를 대조하세요.')}</p></div><div class="head-actions"><span class="operator-priority">담당자 우선도 ${priorityBadge(i.priority)}</span>${statusBadge(i.status)}<button type="button" data-action="edit">사건 수정</button></div></div><dl class="facts-strip"><div class="fact"><dt>구조 대상 위치</dt><dd>${esc(i.location)}</dd></div><div class="fact"><dt>접수 인원</dt><dd>${esc(count(i.people_count))}</dd></div><div class="fact"><dt>담당팀</dt><dd>${esc(teamName(i.assigned_team_id))}</dd></div><div class="fact"><dt>접수 / 최근 변경</dt><dd>${esc(date(i.created_at,true))}<small>최근 ${esc(date(i.updated_at,true))}</small></dd></div></dl>${attentionSection({detail:true})}<div class="detail-grid"><div class="detail-main"><section class="panel"><div class="panel-head"><h2>접수 원문과 보고</h2><span class="muted">${(i.reports||[]).length}개 기록</span></div><div class="section-tabs" role="tablist" aria-label="사건 기록">${[['reports','신고·현장 보고'],['history','변경·결과 이력']].map(([v,l])=>`<button type="button" role="tab" id="tab-${v}" aria-controls="detail-content" aria-selected="${state.detailTab===v}" class="${state.detailTab===v?'active':''}" data-detail-tab="${v}">${l}</button>`).join('')}</div><div id="detail-content" role="tabpanel" aria-labelledby="tab-${state.detailTab}"></div></section></div><aside class="detail-side"><section class="panel"><div class="panel-head"><h2>근거 대조 · 확인 사항</h2><span class="rule-label">규칙 기반 대조</span></div><div class="check-list">${(i.checks||[]).length?(i.checks||[]).map(c=>`<article class="check ${esc(c.level)}"><div class="check-title"><span class="check-marker" aria-hidden="true">${c.level==='warning'?'!':'i'}</span><strong>${esc(c.title)}</strong></div><p>${esc(c.detail)}</p><div class="check-links">${(c.report_ids||[]).map((id,index)=>`<button type="button" data-report-link="${esc(id)}" aria-label="${esc(id)} 원문 보기">원문 ${index+1} 보기</button>`).join('')}</div></article>`).join(''):'<div class="empty">추가 대조 사항이 없습니다.<br>결과 확정 전 현장 근거를 확인하세요.</div>'}</div></section>${closed?outcomePanel():operationsPanel()}${closed?'':`<section class="panel"><div class="panel-head"><h2>처리 결과</h2><span class="muted">미확정</span></div><div class="outcome-body"><p class="operation-note">구조·자력 대피·인계의 현장 근거와 접수 인원을 대조한 뒤 담당자가 확정합니다.</p><div class="action-stack"><button type="button" class="primary" data-action="outcome">처리 결과 확인</button></div></div></section>`}</aside></div>`;
 renderDetailContent();
}
function operationsPanel(){const i=state.incident;return `<section class="panel"><div class="panel-head"><h2>현장 진행</h2>${statusBadge(i.status)}</div><div class="operations-body"><div class="team-assignment"><div><strong>${esc(teamName(i.assigned_team_id))}</strong><small>${i.assigned_team_id?'담당팀의 보고를 대조하세요.':'대응팀을 배정하고 진행 상황을 기록하세요.'}</small></div><button type="button" class="small" data-action="progress">진행 변경</button></div>${progressList(i.progress||[])}<div class="action-stack"><button type="button" data-action="report">추가 정보 등록</button><button type="button" data-action="field-report">현장 보고 등록</button></div><p class="operation-note">배정·현장 도착·부분 구조만으로 처리 완료가 되지 않습니다.</p></div></section>`;}
function progressList(items,limit=4){return items.length?`<ol class="progress-list">${[...items].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,limit).map(p=>`<li class="progress-item"><strong>${esc(statusLabels[p.status]||p.status)}${p.team_id?' / '+esc(teamName(p.team_id)):''}</strong><p>${esc(p.note)}</p><small>${esc(p.actor)} / ${esc(date(p.created_at,true))}</small></li>`).join('')}</ol>`:'<p class="muted">등록된 현장 진행 기록이 없습니다.</p>';}
function outcomePanel(){const i=state.incident,o=i.outcome||{},basis=(i.reports||[]).find(r=>r.id===o.basis_report_id);return `<section class="panel"><div class="panel-head"><h2>확정 처리 결과</h2>${statusBadge('closed')}</div><div class="outcome-body"><div class="outcome-summary"><strong>${esc(outcomeLabels[o.outcome]||'처리 완료')}</strong><p>확인 인원 ${esc(count(o.confirmed_count))}</p></div><dl class="outcome-detail"><dt>확정 담당자</dt><dd>${esc(o.actor||'기록 확인 필요')}</dd><dt>확정 시각</dt><dd>${esc(date(o.confirmed_at||o.created_at,true))}</dd><dt>현장 근거</dt><dd>${o.basis_report_id?`<button type="button" class="link-button" data-report-link="${esc(o.basis_report_id)}" aria-label="현장 근거 ${esc(o.basis_report_id)} 원문 보기">근거 원문 보기</button>`:'기록 확인 필요'}</dd><dt>확인 내용</dt><dd>${esc(o.note||basis?.text||'기록 확인 필요')}</dd></dl><div class="action-stack"><button type="button" data-action="reopen">완료 재개 · 결과 정정</button><button type="button" data-action="report">추가 정보 등록</button></div><p class="operation-note">결과를 정정하면 재개 이유와 이전 결과를 보존하고 새 근거로 다시 확정합니다.</p></div></section>`;}
function renderDetailContent(){const i=state.incident,target=$('detail-content');if(!target)return;if(state.detailTab==='history'){target.innerHTML=historyContent(i);return;}
 const reports=[...(i.reports||[])].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).filter(r=>state.reportTab==='all'||state.reportTab==='field'&&(r.kind==='field'||r.channel==='field')||state.reportTab==='media'&&(r.attachments||[]).length);
 target.innerHTML=`<div class="report-toolbar">${[['all','전체 원문'],['field','현장 보고'],['media','첨부 자료']].map(([v,l])=>`<button type="button" class="filter-chip ${state.reportTab===v?'active':''}" data-report-tab="${v}" aria-pressed="${state.reportTab===v}">${l}</button>`).join('')}<span class="filter-count">최신 접수 순</span></div><div class="timeline">${reports.length?reports.map(reportCard).join(''):'<div class="empty">이 분류에 등록된 보고가 없습니다.</div>'}</div>`;
}
function safeMedia(url){if(window.RescuePages)return window.RescuePages.mediaUrl(url);return typeof url==='string'&&/^\/media\/[a-zA-Z0-9._\-/]+$/.test(url)&&!url.split('/').includes('..')?url:null;}
function reportCard(r){return `<article class="report" id="report-${esc(r.id)}" tabindex="-1"><div class="report-head"><div class="report-source"><span class="channel-tag">${esc(channelLabels[r.channel]||r.channel)}</span><span class="report-kind">${esc(kindLabels[r.kind]||'접수 기록')}</span><span>${esc(r.actor)}</span></div><span>${esc(r.id)}</span></div><p class="report-text">${esc(r.text)}</p>${r.people_count!==undefined||r.location?`<div class="report-proposal">${r.people_count!==undefined?`<span>보고 인원 ${esc(count(r.people_count))}</span>`:''}${r.location?`<span>보고 위치 ${esc(r.location)}</span>`:''}</div>`:''}<p class="report-time">발생 ${esc(date(r.occurred_at,true))} / 접수 ${esc(date(r.received_at,true))}</p>${(r.attachments||[]).length?`<div class="attachments">${r.attachments.map((a,idx)=>mediaCard(a,r.id,idx)).join('')}</div>`:''}</article>`;}
function mediaCard(a,rid,idx){const url=safeMedia(a.url);if(!url)return '<p class="media-caption">첨부 경로를 확인할 수 없습니다. 담당자에게 자료를 요청하세요.</p>';const caption=a.caption||a.filename||'첨부 자료';const source={ai_generated:'생성 사진',tts_synthetic:'합성 음성',operator_upload:'담당자 업로드'}[a.source]||'접수 첨부';
 if(a.media_type==='image')return `<div><button type="button" class="image-preview" data-image-report="${esc(rid)}" data-image-index="${idx}" aria-label="${esc(caption)} 확대"><img src="${esc(url)}" alt="${esc(caption)}" loading="lazy"><span>사진 확대</span></button><p class="media-caption">${esc(caption)} / ${source}</p></div>`;
 if(a.media_type==='audio')return `<div class="audio-box"><strong>${esc(a.filename||'신고 음성')}</strong><audio controls preload="metadata" src="${esc(url)}" aria-label="${esc(caption)}">브라우저에서 음성 재생을 지원하지 않습니다.</audio><p class="media-caption">${esc(caption)} / ${source}</p>${a.transcript?`<details class="transcript"><summary>음성 원문 보기</summary><p>${esc(a.transcript)}</p><small>합성 대본 또는 담당자 기록입니다. 자동 음성 인식 결과가 아닙니다.</small></details>`:''}</div>`;
 if(a.media_type==='video')return `<div><video controls preload="metadata" src="${esc(url)}" aria-label="${esc(caption)}">브라우저에서 영상 재생을 지원하지 않습니다.</video><p class="media-caption">${esc(caption)} / ${source}</p>${a.transcript?`<details class="transcript"><summary>영상 기록 보기</summary><p>${esc(a.transcript)}</p></details>`:''}</div>`;return '<p class="media-caption">첨부 형식을 확인할 수 없습니다.</p>';}
function displayValue(k,v){if(v===null||v===undefined)return '없음';if(k==='status')return statusLabels[v]||v;if(k==='priority')return priorityLabels[v]||v;if(k==='people_count')return count(v);if(k==='assigned_team_id')return teamName(v);if(k==='outcome')return typeof v==='object'?outcomeLabels[v.outcome]||'처리 결과':outcomeLabels[v]||v;return typeof v==='object'?'기록 보존':String(v);}
function historyContent(i){const history=i.outcome_history||[],audit=[...(i.audit||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return `<div class="audit-list">${history.length?`<p class="history-label">이전 처리 결과 ${history.length}건</p>${[...history].reverse().map(o=>`<article class="result-history"><strong>${esc(outcomeLabels[o.outcome]||'이전 처리 결과')} / ${esc(count(o.confirmed_count))}</strong><p>${esc(o.note||'')}</p><small>확정 ${esc(date(o.confirmed_at||o.created_at,true))} / ${esc(o.actor||'')}</small><p>재개 이유: ${esc(o.reopen_reason||'새 정보 접수')}</p><small>재개 ${esc(date(o.reopened_at,true))} / ${esc(o.reopened_by||'')}</small></article>`).join('')}`:''}<p class="history-label">사건 변경 기록</p>${audit.length?audit.map(a=>{const before=a.before||{},after=a.after||{},changes=Object.keys(fieldLabels).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])&&(k in before||k in after));return `<details class="audit-item"><summary><strong>${esc(actionLabels[a.action]||'업무 기록')} / ${esc(a.actor)}</strong><span>${esc(date(a.created_at,true))}</span></summary><p class="audit-reason">${esc(a.reason||'업무 기록을 저장했습니다.')}</p>${changes.length?`<div class="audit-changes"><div class="change-row"><span>변경 항목</span><span>이전</span><span>변경 후</span></div>${changes.map(k=>`<div class="change-row"><span>${fieldLabels[k]}</span><span>${esc(displayValue(k,before[k]))}</span><span>${esc(displayValue(k,after[k]))}</span></div>`).join('')}</div>`:''}</details>`;}).join(''):'<p class="empty">변경 이력이 없습니다.</p>'}<p class="history-label">전체 현장 진행 기록</p>${progressList(i.progress||[],Infinity)}</div>`;}
function inputField(name,label,{value='',type='text',required=false,full=false,help='',optional=false,min,placeholder='',options,rows=3}={}){
 const attrs=`id="f-${esc(name)}" name="${esc(name)}" ${required?'required':''}`;
 const control=options?`<select ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:type==='textarea'?`<textarea ${attrs} rows="${rows}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input ${attrs} type="${esc(type)}" value="${esc(value)}" ${min!==undefined?`min="${min}" step="1"`:''} placeholder="${esc(placeholder)}">`;
 return `<div class="field ${full?'full':''}"><label for="f-${esc(name)}">${esc(label)}${optional?'<span class="optional">선택</span>':''}</label>${control}${help?`<small>${esc(help)}</small>`:''}</div>`;
}
const actorField=()=>inputField('actor','담당자',{value:'상황실 김담당',required:true});
const uploadField=()=>`<div class="field full"><label for="f-files">첨부 자료<span class="optional">선택</span></label><input type="file" id="f-files" name="files" multiple accept="image/png,image/jpeg,audio/wav,audio/mpeg,video/mp4"><small>PNG, JPG, WAV, MP3, MP4 / 파일당 최대 8MB. 실제 개인정보가 없는 훈련 자료를 사용하세요.</small><div id="upload-list" class="upload-list"></div></div>`;
function openTask(kind,{teamId}={}){
 const i=state.incident,closed=i?.status==='closed';if(kind!=='new'&&!i)return;if(kind==='progress'&&closed){toast('완료 사건은 먼저 재개한 뒤 진행을 변경하세요.');return;}
 restoreFocus=document.activeElement;modal={kind,incidentId:i?.id,revision:i?.revision,pendingFiles:[],attachments:[],busy:false};
 const cfg={new:['신규 사건 접수','신고 원문과 구조 대상 정보를 접수합니다.','사건 접수'],report:['추가 정보 등록','원문을 추가합니다. 인원·위치 변경은 정정으로 선택하세요.','정보 등록'],'field-report':['현장 보고 등록','해당 사건의 현장 확인 내용과 확인 인원을 기록하세요.','현장 보고 등록'],edit:['사건 정보 수정','원래 값은 이력에 남습니다. 수정 이유를 함께 기록하세요.','수정 저장'],progress:['현장 진행 변경','진행 상황과 담당팀을 기록합니다. 배정은 완료 확인이 아닙니다.','진행 저장'],outcome:['처리 결과 확인','현장 근거와 현재 접수 인원을 대조한 뒤 확정합니다.','처리 결과 확정'],reopen:['완료 재개 · 결과 정정','이전 결과를 보존하고 확인 필요 상태로 재개합니다.','사건 재개']}[kind];
 $('dialog-title').textContent=cfg[0];$('dialog-description').textContent=cfg[1];$('dialog-save').textContent=cfg[2];$('dialog-error').hidden=true;$('dialog-error').replaceChildren();let fields='';
 if(kind==='new')fields=inputField('title','사건명',{required:true,full:true,placeholder:'예: 새봄빌라 201호 침수 고립'})+inputField('category','사건 분류',{value:'flood',options:Object.entries(categoryLabels)})+inputField('priority','담당자 우선도',{value:'normal',options:Object.entries(priorityLabels)})+inputField('location','구조 대상 위치',{required:true,full:true,placeholder:'가상동·건물·층·호수'})+inputField('people_count','신고 인원',{type:'number',min:0,optional:true,help:'불명확하면 비워 두고 확인하세요.'})+inputField('channel','접수 채널',{value:'sms',options:Object.entries(channelLabels).filter(([v])=>v!=='field')})+inputField('text','신고 원문',{type:'textarea',required:true,full:true,rows:4})+inputField('summary','사건 요약',{type:'textarea',optional:true,full:true,rows:2})+actorField()+uploadField();
 if(kind==='report'||kind==='field-report')fields=`<p class="form-note">${closed?'완료 사건에 새 정보가 등록되면 확인 필요 상태로 다시 열립니다. 이전 결과는 이력에 보존됩니다.':'접수 인원 '+esc(count(i.people_count))+' / 현재 위치 '+esc(i.location)}</p>`+inputField('kind','등록 종류',{value:kind==='field-report'?'field':'additional',options:[['additional','추가 정보'],['field','현장 보고'],['correction','인원·위치 정정']]})+inputField('channel','정보 출처',{value:kind==='field-report'?'field':'sms',options:Object.entries(channelLabels)})+inputField('text','보고 원문',{type:'textarea',required:true,full:true,rows:4,help:'관찰한 사실과 미확인 사항을 구분해 기록하세요.'})+inputField('people_count','보고·정정 인원',{type:'number',min:0,optional:true,help:'현장 인원은 결과 확정 근거로 사용됩니다.'})+inputField('location','보고·정정 위치',{optional:true})+actorField()+uploadField();
 if(kind==='edit')fields=inputField('title','사건명',{value:i.title,required:true,full:true})+inputField('location','구조 대상 위치',{value:i.location,required:true,full:true})+inputField('people_count','접수 인원',{value:i.people_count??'',type:'number',min:0,optional:true})+inputField('priority','담당자 우선도',{value:i.priority,options:Object.entries(priorityLabels)})+inputField('reason','수정 이유',{type:'textarea',required:true,full:true,placeholder:'확인한 원문과 수정 사유를 기록하세요.'})+actorField()+`<p class="form-note">${closed?'완료된 사건의 인원·위치가 바뀌면 다시 확인 상태로 열립니다.':'기존 접수 원문을 바꾸지 않고 사건 정보의 변경 이력을 남깁니다.'}</p>`;
 if(kind==='progress'){
  const eligible=state.resources.filter(r=>r.status==='available'||r.incident_id===i.id),team=teamId||i.assigned_team_id||'';
  fields=inputField('status','진행 상태',{value:teamId?'dispatched':['dispatched','on_scene','rescuing','reviewing'].includes(i.status)?i.status:'dispatched',options:Object.entries(statusLabels).filter(([v])=>!['received','closed'].includes(v))})+inputField('team_id','담당팀',{value:team,options:[['',i.assigned_team_id?'현재 담당팀 유지':'미배정'],...eligible.map(r=>[r.id,`${r.name} (${r.crew_count}명 / ${r.status==='available'?'가용':'현재 담당'})`])]})+inputField('note','진행 내용',{type:'textarea',required:true,full:true,placeholder:'현장 도착·배정·구조 진행 내용을 기록하세요.'})+actorField()+`<p class="form-note">다른 사건에 배정된 팀은 선택할 수 없습니다. 구조 보고는 별도로 등록한 뒤 결과를 확인하세요.</p>`;
 }
 if(kind==='outcome'){
  const previous=(i.outcome_history||[]).at(-1);
  const reports=(i.reports||[]).filter(r=>{
   if(r.kind!=='field'&&r.channel!=='field')return false;
   if(Array.isArray(previous?.report_ids_at_reopen))return !previous.report_ids_at_reopen.includes(r.id);
   if(previous?.reopened_at)return new Date(r.received_at)>new Date(previous.reopened_at);
   return true;
  }).sort((a,b)=>new Date(b.received_at)-new Date(a.received_at));
  const eligible=reports.filter(r=>r.people_count===i.people_count),selected=eligible[0]?.id||'';
  modal.noBasis=reports.length===0;
  fields=(previous?.reopened_at?'<p class="form-note">재개 이후 새 현장 보고만 선택할 수 있습니다. 이전 근거는 원문과 변경 이력에서 확인하세요.</p>':'')+`<p class="form-note">현재 접수 인원 <strong>${esc(count(i.people_count))}</strong>. 현장 보고의 인원과 일치해야 완료할 수 있습니다.</p>`+inputField('outcome','확정 결과',{value:'rescued',options:Object.entries(outcomeLabels)})+inputField('confirmed_count','확인 인원',{type:'number',min:0,value:i.people_count??'',required:true})+inputField('basis_report_id','현장 근거 보고',{value:selected,required:true,full:true,options:[['','근거 현장 보고 선택'],...reports.map(r=>[r.id,`${r.id} / ${count(r.people_count)} / ${date(r.received_at)} ${String(r.text).slice(0,40)}`])]})+'<div id="basis-preview" class="basis-preview"></div>'+inputField('note','담당자 확인 내용',{type:'textarea',required:true,full:true,placeholder:'대상 요청·전체 인원·현장 근거를 어떻게 대조했는지 기록하세요.'})+actorField();
 }
 if(kind==='reopen')fields=`<p class="form-note">현재 결과: ${esc(outcomeLabels[i.outcome?.outcome]||'처리 완료')} / ${esc(count(i.outcome?.confirmed_count))}. 재개 후 새 현장 근거로 결과를 다시 확인하세요.</p>`+inputField('reason','재개·정정 이유',{type:'textarea',required:true,full:true,rows:4,placeholder:'새 정보 또는 잘못된 결과를 확인한 사유'})+actorField();
 $('dialog-save').disabled=Boolean(modal.noBasis);$('dialog-fields').innerHTML=fields;$('task-form').querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('input',()=>x.removeAttribute('aria-invalid')));
 $('task-dialog').showModal();const first=$('dialog-fields').querySelector('input,select,textarea');if(first)first.focus();
 if($('f-files'))$('f-files').addEventListener('change',onFiles);
 if(kind==='outcome'){$('f-basis_report_id').addEventListener('change',updateBasisPreview);updateBasisPreview();}
 if(kind==='report'||kind==='field-report')$('f-kind').addEventListener('change',()=>{if($('f-kind').value==='field')$('f-channel').value='field';});
}
function updateBasisPreview(){const r=(state.incident?.reports||[]).find(x=>x.id===$('f-basis_report_id').value);$('basis-preview').innerHTML=r?`<strong>${esc(r.actor)} / 확인 ${esc(count(r.people_count))}</strong><span>${esc(r.text)}</span>`:(modal?.noBasis?'<strong>새 현장 보고를 등록하세요.</strong><span>선택할 수 있는 현장 근거가 없습니다. 전체 인원과 대상 요청을 확인한 새 보고가 필요합니다.</span><div class="button-row"><button type="button" class="small" data-register-basis>현장 보고 등록</button></div>':'<strong>현장 근거를 선택하세요.</strong><span>현재 인원과 일치하는 현장 보고를 선택하고 전체 인원을 대조하세요.</span>');}
function closeTask(){if(modal?.busy)return;$('task-dialog').close();}
$('task-dialog').addEventListener('close',()=>{modal=null;$('task-form').reset();$('dialog-error').hidden=true;const focus=restoreFocus;if(focus?.isConnected)focus.focus();restoreFocus=null;});
$('task-dialog').addEventListener('cancel',e=>{if(modal?.busy)e.preventDefault();});
$('task-dialog').querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeTask));
function showFormError(message,field){const box=$('dialog-error');box.replaceChildren();box.textContent=message;box.hidden=false;if(field){field.setAttribute('aria-invalid','true');field.focus();}}
function onFiles(e){if(!modal)return;const files=[...e.target.files];const invalid=files.find(f=>f.size>8*1024*1024||!(/\.(png|jpe?g|wav|mp3|mp4)$/i).test(f.name));if(invalid){showFormError(`${invalid.name}: PNG, JPG, WAV, MP3, MP4 파일을 8MB 이하로 선택하세요.`,e.target);e.target.value='';return;}for(const f of files)if(!modal.pendingFiles.some(x=>x.name===f.name&&x.size===f.size)&&!modal.attachments.some(x=>x.filename===f.name))modal.pendingFiles.push(f);e.target.value='';renderUploads();}
function renderUploads(){const list=$('upload-list');if(!list||!modal)return;list.innerHTML=[...modal.attachments.map((a,n)=>`<div class="upload-item"><span>${esc(a.filename)} / 업로드 완료</span><button type="button" data-remove-upload="${n}" aria-label="${esc(a.filename)} 첨부 제거">제거</button></div>`),...modal.pendingFiles.map((f,n)=>`<div class="upload-item"><span>${esc(f.name)} / ${(f.size/1024).toFixed(0)}KB</span><button type="button" data-remove-file="${n}" aria-label="${esc(f.name)} 첨부 제거">제거</button></div>`)].join('');}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('첨부 파일을 읽지 못했습니다. 다시 선택하세요.'));reader.readAsDataURL(file);});}
async function uploadPending(){while(modal.pendingFiles.length){const file=modal.pendingFiles[0],data_base64=await fileBase64(file),type=file.type||({wav:'audio/wav',mp3:'audio/mpeg',mp4:'video/mp4',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg'}[file.name.split('.').pop().toLowerCase()]);const a=await api('/api/uploads',{method:'POST',body:{filename:file.name,content_type:type,data_base64}});modal.attachments.push(a);modal.pendingFiles.shift();renderUploads();}}
function setBusy(value){if(!modal)return;modal.busy=value;$('task-form').querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=value);if(!value)$('dialog-save').disabled=Boolean(modal.noBasis);$('dialog-save').textContent=value?'저장 중…':{new:'사건 접수',report:'정보 등록','field-report':'현장 보고 등록',edit:'수정 저장',progress:'진행 저장',outcome:'처리 결과 확정',reopen:'사건 재개'}[modal.kind];}
$('task-form').addEventListener('submit',async e=>{
 e.preventDefault();if(!modal||modal.busy)return;
 const form=$('task-form'),required=[...form.querySelectorAll('[required]')];for(const field of required){if(!field.value.trim()){showFormError(`${form.querySelector(`label[for="${field.id}"]`)?.textContent||'필수 항목'}을 입력하세요.`,field);return;}}
 for(const field of form.querySelectorAll('input[type=number]'))if(field.value!==''&&(!/^\d+$/.test(field.value)||!Number.isSafeInteger(Number(field.value)))){showFormError('인원은 0 이상의 정수로 입력하세요.',field);return;}
 const values=Object.fromEntries(new FormData(form));let body={actor:values.actor.trim()},path='/api/incidents',method='POST';const kind=modal.kind;
 if(kind==='new'){Object.assign(body,{title:values.title.trim(),location:values.location.trim(),category:values.category,priority:values.priority,channel:values.channel,text:values.text.trim(),summary:values.summary.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);}
 else {body.expected_revision=modal.revision;path+=`/${encodeURIComponent(modal.incidentId)}`;
  if(kind==='report'||kind==='field-report'){path+='/reports';Object.assign(body,{kind:values.kind,channel:values.channel,text:values.text.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);if(values.location.trim())body.location=values.location.trim();}
  if(kind==='edit'){method='PATCH';Object.assign(body,{title:values.title.trim(),location:values.location.trim(),priority:values.priority,reason:values.reason.trim()});if(values.people_count!=='')body.people_count=Number(values.people_count);}
  if(kind==='progress'){path+='/progress';Object.assign(body,{status:values.status,note:values.note.trim()});if(values.team_id)body.team_id=values.team_id;}
  if(kind==='outcome'){path+='/outcome';Object.assign(body,{outcome:values.outcome,confirmed_count:Number(values.confirmed_count),basis_report_id:values.basis_report_id,note:values.note.trim()});}
  if(kind==='reopen'){path+='/reopen';body.reason=values.reason.trim();}
 }
 $('dialog-error').hidden=true;setBusy(true);
 try {
  if(kind==='new'||kind==='report'||kind==='field-report'){await uploadPending();body.attachments=[...modal.attachments];}
  const updated=await api(path,{method,body});setBusy(false);$('task-dialog').close();
  state.incident=updated;try{await loadList();}catch(error){toast('업무는 저장됐지만 목록 갱신에 실패했습니다. 새로고침하세요.');}
  const target=incidentLink(updated);if(location.hash!==target)location.hash=target;else renderDetail();
  toast({new:'새 사건을 접수했습니다.',report:updated.status==='reviewing'?'추가 정보를 등록했습니다. 확인 필요 상태를 확인하세요.':'추가 정보를 등록했습니다.','field-report':'현장 보고를 등록했습니다.',edit:'사건 정보와 수정 이유를 저장했습니다.',progress:'담당팀과 현장 진행을 저장했습니다.',outcome:'근거를 대조한 처리 결과를 확정했습니다.',reopen:'사건을 재개했습니다. 이전 결과는 이력에 보존했습니다.'}[kind]);
 }catch(error){setBusy(false);showFormError(error.message);if(error.status===409){const b=document.createElement('button');b.type='button';b.textContent='최신 사건 정보 대조';b.addEventListener('click',async()=>{b.disabled=true;try{state.incident=await api(`/api/incidents/${encodeURIComponent(modal.incidentId)}`);modal.revision=state.incident.revision;await loadList();renderDetail();showFormError(`최신 정보를 불러왔습니다. 현재 접수 인원 ${count(state.incident.people_count)}, 상태 ${statusLabels[state.incident.status]}. 입력값을 확인하고 다시 저장하세요.`);}catch(err){showFormError(err.message);}finally{b.disabled=false;}});$('dialog-error').append(b);}}
});
function showImage(rid,index){const a=(state.incident?.reports||[]).find(r=>r.id===rid)?.attachments?.[index],url=a&&safeMedia(a.url);if(!url)return;restoreFocus=document.activeElement;$('media-title').textContent=a.filename||'첨부 사진';$('media-content').innerHTML=`<img src="${esc(url)}" alt="${esc(a.caption||'신고 첨부 사진')}"><p>${esc(a.caption||'')}</p>`;$('media-dialog').showModal();$('media-dialog').querySelector('[data-media-close]').focus();}
$('media-dialog').querySelector('[data-media-close]').addEventListener('click',()=>$('media-dialog').close());
$('media-dialog').addEventListener('close',()=>{$('media-content').replaceChildren();if(restoreFocus?.isConnected)restoreFocus.focus();restoreFocus=null;});
function openBackgroundIncident(event){
 if(event.defaultPrevented||event.button!==0||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;
 if(event.target.closest('a,button,input,select,textarea,summary,audio,video,label,[contenteditable],[data-no-navigation]'))return;
 if(window.getSelection()?.toString().trim())return;
 const surface=event.target.closest('[data-incident-surface]');
 const link=surface?.querySelector('[data-incident-link]');
 if(link)link.click();
}
function focusReport(id){state.detailTab='reports';state.reportTab='all';renderDetail();const r=document.getElementById(`report-${id}`);if(r){r.scrollIntoView({behavior:'auto',block:'start'});r.focus({preventScroll:true});}}
$('attention-strip').addEventListener('click',async e=>{const button=e.target.closest('button[data-attention-incident]');if(button)await openAttentionWork(button);else openBackgroundIncident(e);});
$('view').addEventListener('click',async e=>{
 const target=e.target.closest('button');if(!target){openBackgroundIncident(e);return;}
 if(target.dataset.attentionIncident){await openAttentionWork(target);return;}
 if(target.dataset.filter){state.filters.status=target.dataset.filter;updateTable();return;}
 if(target.dataset.detailTab){state.detailTab=target.dataset.detailTab;renderDetail();document.querySelector(`[data-detail-tab="${state.detailTab}"]`)?.focus();return;}
 if(target.dataset.reportTab){state.reportTab=target.dataset.reportTab;renderDetailContent();document.querySelector(`[data-report-tab="${state.reportTab}"]`)?.focus();return;}
 if(target.dataset.reportLink){focusReport(target.dataset.reportLink);return;}
 if(target.dataset.imageReport){showImage(target.dataset.imageReport,Number(target.dataset.imageIndex));return;}
 const action=target.dataset.action;if(!action)return;
 if(action==='clear-filters'){state.filters={query:'',status:'all',channel:'all',priority:'all'};renderDashboard();return;}
 if(action==='assign-resource'){
  if(target.disabled)return;
  const teamId=target.dataset.resource,id=document.getElementById(`assign-${teamId}`).value;if(!id){toast('배정할 사건을 먼저 선택하세요.');return;}
  target.disabled=true;
  try{
   await loadList();
   const hash=`#incident/${encodeURIComponent(id)}`;if(location.hash!==hash)history.pushState(null,'',hash);
   await route(false);
   if(state.view!=='detail'||state.incident?.id!==id||!Number.isInteger(state.incident.revision))return;
   if(state.incident.status==='closed'){toast('이미 완료된 사건입니다. 최신 처리 결과를 확인하세요.');return;}
   const team=state.resources.find(r=>r.id===teamId);
   if(!team||(team.status!=='available'&&team.incident_id!==id)){toast('선택한 팀을 배정할 수 없습니다. 최신 대응 자원을 확인하세요.');return;}
   openTask('progress',{teamId});
  }catch(err){pageError(err.message);}finally{target.disabled=false;}return;
 }
 openTask(action);
});
$('dialog-fields').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!modal||modal.busy)return;if(b.hasAttribute('data-register-basis')){$('task-dialog').addEventListener('close',()=>openTask('field-report'),{once:true});closeTask();return;}if(b.dataset.removeFile!==undefined)modal.pendingFiles.splice(Number(b.dataset.removeFile),1);if(b.dataset.removeUpload!==undefined)modal.attachments.splice(Number(b.dataset.removeUpload),1);renderUploads();});
$('refresh').addEventListener('click',refresh);window.addEventListener('hashchange',()=>route().catch(e=>pageError(e.message)));
if(window.RescuePages)$('pages-notice').hidden=false;
(async()=>{try{await loadList();await route(false);}catch(error){pageError(error.message);$('view').innerHTML='<div class="empty"><strong>업무 자료를 불러오지 못했습니다.</strong>서버 연결을 확인하고 다시 불러오기를 선택하세요.</div>';}})();

$('view').addEventListener('keydown',e=>{if(!e.target.matches('[data-detail-tab]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();state.detailTab=e.key==='Home'?'reports':e.key==='End'?'history':state.detailTab==='reports'?'history':'reports';renderDetail();document.querySelector(`[data-detail-tab="${state.detailTab}"]`)?.focus();});
